from pathlib import Path
import shutil
p=Path('OutlineLab_v5.html');s=p.read_text(encoding='utf-8')
s=s.replace('<button class="btn" id="removeBgBtn"', '<label class="small">Rimozione sfondo</label><select id="bgMethod"><option value="ai">AI · soggetti e fotografie</option><option value="solid">Sfondo uniforme · disegni e lineart</option></select><div id="solidBgOptions" class="hidden"><div class="row" style="margin-top:8px"><input id="bgColor" type="color" value="#ffffff" title="Colore da rimuovere"><label class="grow">Tolleranza <input id="bgTolerance" type="range" min="0" max="150" value="35"></label></div><label class="check"><input id="bgEverywhere" type="checkbox"><span>Rimuovi il colore anche nelle aree interne chiuse</span></label></div><button class="btn" id="removeBgBtn"')
s=s.replace("if(location.protocol==='file:'){toast('Avvia il launcher per rimuovere lo sfondo');return}", "if(location.protocol==='file:'&&$('bgMethod').value==='ai'){toast('Avvia il launcher per la rimozione AI; Sfondo uniforme funziona anche da file');return}")
s=s.replace("const mod=await loadBackgroundModule();const raster", "const mod=$('bgMethod').value==='ai'?await loadBackgroundModule():null;const raster")
s=s.replace("const out=await mod.removeBackground(srcBlob,", "const out=mod?await mod.removeBackground(srcBlob,")
s=s.replace("output:{format:'image/png',quality:1}});const dataUrl", "output:{format:'image/png',quality:1}}):await removeSolidBackground(srcBlob);const dataUrl")
s=s.replace("$('rebuildTextBtn').onclick=async()=>", "$('bgMethod').onchange=()=>{$('solidBgOptions').classList.toggle('hidden',$('bgMethod').value!=='solid');$('removeBgStatus').textContent=$('bgMethod').value==='solid'?'Rimuove lo sfondo collegato ai bordi. Per rimuovere anche il bianco dentro le forme abilita le aree interne. Funziona anche da file, senza rete.':'AI per fotografie e soggetti: elaborazione locale, primo download circa 56 MB. Per contorni e disegni usa Sfondo uniforme.'};$('rebuildTextBtn').onclick=async()=>")
helper="""
async function removeSolidBackground(blob){const im=new Image(),url=URL.createObjectURL(blob);try{im.src=url;await im.decode();const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);const image=ctx.getImageData(0,0,c.width,c.height),d=image.data,w=c.width,h=c.height,n=w*h,color=$('bgColor').value,r=parseInt(color.slice(1,3),16),g=parseInt(color.slice(3,5),16),b=parseInt(color.slice(5,7),16),t=Number($('bgTolerance').value);const matches=i=>d[i*4+3]===0||Math.max(Math.abs(d[i*4]-r),Math.abs(d[i*4+1]-g),Math.abs(d[i*4+2]-b))<=t;if($('bgEverywhere').checked){for(let i=0;i<n;i++)if(matches(i))d[i*4+3]=0}else{const seen=new Uint8Array(n),queue=new Uint32Array(n);let head=0,tail=0;const add=i=>{if(i>=0&&i<n&&!seen[i]){seen[i]=1;if(matches(i))queue[tail++]=i}};for(let x=0;x<w;x++){add(x);add((h-1)*w+x)}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1)}while(head<tail){const i=queue[head++];d[i*4+3]=0;if(i%w)add(i-1);if(i%w<w-1)add(i+1);add(i-w);add(i+w)}}ctx.putImageData(image,0,0);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('PNG non creato')),'image/png'))}finally{URL.revokeObjectURL(url)}}
"""
s=s.replace("let pageLoadId=0;",helper+"\nlet pageLoadId=0;")
p.write_text(s,encoding='utf-8');shutil.copy2(p,Path('build/OutlineLab_v5')/p.name)
test=Path('tests.js');t=test.read_text();t=t.replace("canvas.setActiveObject(img);await removeBackgroundSelected()", "canvas.setActiveObject(img);$('bgMethod').value='solid';await removeBackgroundSelected()")
# Photograph fixture checks actual AI inference independently from line-art processing.
t=t.replace("const payload=projectPayload();", "const photoId=await assetFromUrl('test-photo.png',{name:'Public scikit-image astronaut fixture'});await addImageAsset(photoId,'image');$('bgMethod').value='ai';await removeBackgroundSelected();ok('AI photograph removal completed',$('removeBgStatus').textContent.startsWith('Background rimosso'));const photo=canvas.getObjects().filter(o=>o.objectType==='bgremoved').at(-1),pc=document.createElement('canvas');pc.width=photo.width;pc.height=photo.height;const px=pc.getContext('2d');px.drawImage(photo._element,0,0);const pd=px.getImageData(0,0,pc.width,pc.height).data;let pt=0,po=0;for(let i=3;i<pd.length;i+=4){if(pd[i]<20)pt++;if(pd[i]>200)po++}ok('AI photo keeps foreground and removes background',pt>100&&po>100);const payload=projectPayload();")
test.write_text(t)
