from pathlib import Path
from html import escape

# The English guide is authored alongside the Italian guide. Keep section IDs
# aligned so language changes preserve links and the table-of-contents structure.
TOPICS = [
('orientarsi','🧭 Finding your way around','chicCanva has a top project bar, a canvas toolbar, the active page, and a task-based sidebar.','Use the sidebar shortcuts to open Page, Special, Text, Fonts, Emoji, Shapes, Images, Colorizer, Clipart, AI, or Export.'),
('lingua','🌐 Interface language','chicCanva includes Italian and English. On first launch it checks the complete browser locale list, choosing Italian when an Italian preference is present and English otherwise. Your later choice is remembered in browser storage. Newly generated project and page names follow the active UI language; existing names, prompts, fonts, and imported content remain unchanged.','On desktop use the flag immediately before Guide; on mobile open the panel and use the selector above Storage. The language is applied before the interface and recovery dialog appear. Clearing app storage makes the next launch detect the browser language again.'),
('progetti','📁 Open projects and tabs','Each tab is an independent multi-page project. Several projects can stay open without replacing one another.','Scroll the complete project strip horizontally to reach the trailing + Project action; long names are visually ellipsized without changing the saved name. Press + Project to start another project. Double-click, use F2, or open the tab menu to rename it; close it only after saving or exporting if needed.'),
('autosave','💾 Autosave and recovery','Autosave stores open projects, pages, objects, assets, and settings in browser storage. Only the active page is decoded into the canvas.','Enable autosave in Storage. After a refresh, choose Resume project to restore the workspace or New project to discard the saved workspace.'),
('cronologia','↶ Undo, redo, and history','History records changes that affect pages, objects, or printable output. Tool choices, searches, drafts, and zoom do not create history steps by themselves.','Use Ctrl+Z and Ctrl+Y. Right-click or long-press Undo or Redo to open the scrollable history and jump to a specific state.'),
('pagine','📄 Creating and managing pages','Every page has its own name, physical size, and orientation. The + button beside page navigation inserts a page after the active one.','Use Page management to add, duplicate, rename, resize, rotate, reorder, or delete pages. Deletion always asks for confirmation.'),
('formati','↔ Formats and orientation','A4, A3, A5, US Letter, Square, and Custom represent real measurements in millimetres.','Choose a preset or enter custom dimensions, apply the format, and use Rotate page to swap width and height immediately.'),
('nomi-riordino','🔢 Page names and order','Clear names make Preview, PDF files, and image ZIP archives easier to understand.','Rename from the page chip or context menu. Drag pages to reorder them, or use the arrow buttons when working on a touch device.'),
('preview','▦ Previewing all pages','Preview displays a scrollable grid of the complete project. Portrait and landscape pages retain their proportions at a comparable visual scale.','Adjust thumbnail size, select a page to edit it, or enable Reorder and move pages by dragging or with the arrows.'),
('vista','🔍 Zoom, Fit, hand tool, and pinch','Zoom changes only the editor view. Fit centers the page in the space left by the sidebar.','Use the zoom list, +/−, Ctrl+wheel, or a two-finger pinch. Enable the hand tool to pan the enlarged workspace in every direction.'),
('selezione','▧ Single and multiple selection','Click an object to select it. Ctrl+click, a selection rectangle, or touch-friendly Tap selection can build a multiple selection.','Choose the selection tool, select the required objects, and then move, resize, rotate, group, copy, or delete them together.'),
('trasformazioni','↗ Move, resize, rotate, and lock','Handles can resize freely or preserve proportions while the opposite side remains anchored. Rotation is available only when enabled.','Drag objects or use arrow keys. Shift temporarily reverses aspect locking; Escape cancels the current move, resize, crop, or drawing gesture.'),
('appunti','⧉ Copy, paste, and duplicate','Copy is multipurpose: it stores editable chicCanva objects and also attempts to publish a PNG of that same selection to the system clipboard. A cropped single image publishes the visible crop at native pixel quality while the editable object retains the full source.','Toolbar Copy, the context command, and Ctrl+C use the same operation. Standard paste prioritizes editable objects; image paste remains separate. In Selected image information, Copy image copies the original immediately when no crop exists; with an active crop it opens a choice between Copy original and Copy crop.'),
('gruppi','⊞ Grouping and ungrouping','Grouping turns several objects into one transformable composition, shown with a stronger purple selection frame.','Select at least two objects and use Ctrl+G. Use Ctrl+Shift+G to expose the members again without losing their positions.'),
('forme','✦ Shapes, lines, and freehand drawing','The Shapes section includes basic geometry, classroom symbols, arrows, callouts, polygons, lines, and raw or smoothed freehand drawing.','Choose fill, outline, width, and a shape, then drag on the page. Edit Points remains active until you explicitly turn it off.'),
('testo','✏️ Adding and editing text','The Text section adds a phrase or separate character groups. Selecting one text object exposes Edit object text.','For existing text, choose which dimensions to preserve and whether to keep proportions. The upper-left corner remains fixed during the update.'),
('fit-testo','↔ Fitting content','Content can be contained inside the page, fitted to width, or fitted to height. The object menu also provides proportional Fit with margin and Fit without margin; the latter uses the full page without stretching.','Set the fit margin in Canvas, grid and snapping immediately after Rotation step. An object with the same aspect ratio as the page reaches all four edges in the no-margin mode.'),
('simboli','’ Symbols and smart apostrophe','When text is split, symbol rules decide which marks stay with the previous or next character. Smart apostrophe prevents isolated apostrophe pages.','Enable one object per character, review both symbol lists, and keep Smart apostrophe enabled for ordinary Italian text.'),
('split','✂ Splitting existing text','Split converts an existing text object into editable characters or configured groups while preserving its overall appearance.','Select one text object, configure symbol rules, and press Split text. The resulting pieces remain selected for immediate grouping or styling.'),
('speciale','✨ One letter or group per page','The special generator creates banners and classroom signs from text, either in a new project or in the current project.','Choose orientation, fitting, smart emoji, and destination. Constant size makes the largest group define one shared character scale.'),
('gruppi-espliciti','^ Explicit groups','Explicit groups use the ^ character to mark exactly where a new page begins, overriding automatic splitting.','Enable Explicit groups and write, for example, this^is a^test. Spaces inside each group are preserved; the separators are not printed.'),
('font-diretti','🔤 Direct font search and selection','The embedded catalogue contains about 2,100 font families and supports name, style, and category searches.','Search for a family or visual property, browse categories, and click a card to load and apply the font. Samples always use Outline.'),
('wizard-font','🪄 Font wizard','The wizard compares every catalogued font by child-friendly weight, roundness, geometry, serif character, and artistic style.','Start from the current font, move the preference controls, inspect the proposed Outline sample, and apply the result when it fits the project.'),
('outline','◯ Outline, color, and width','Outline mode renders colorable interiors with a configurable border. Disable Outline mode allows ordinary filled fonts.','Choose border color and thickness, then apply them to the current selection or use them as defaults for new text.'),
('emoji','😀 Exploring OpenMoji','The OpenMoji browser supports the complete catalogue, relevant items, categories, and global English keyword search.','Browse a category or search explicitly. In the Italian interface, optional translation converts common terms locally and uses Puter for unknown terms when signed in; text in parentheses disambiguates the translation and is omitted from the search.'),
('emoji-outline','🖍️ Outline emoji color and border','Black OpenMoji artwork can be recolored and its outline can be thickened before insertion or on selected emoji.','Choose a color, adjust outline width, and apply it to the selection. Black remains the default for printable coloring materials.'),
('smart-emoji','🙂 Smart emoji inside text','Smart emoji recognizes Unicode emoji in typed text and creates separate OpenMoji assets grouped with the surrounding text.','Leave Smart emoji enabled while adding or editing text. Ungroup the result to recolor or resize individual emoji independently.'),
('immagini','🖼️ Uploading images','Images can come from files, the clipboard, a URL, imported PDF pages, generated AI output, or Clipart.','Upload or paste an image and then move, resize, rotate, crop, duplicate, recolor, or use it as an AI reference.'),
('risoluzione-immagine','↕ Changing image quality and resolution','Change quality replaces only the selected image. The Resolution slider offers steps from ¼× to 4×, including ¾×, 1×, 1¼×, 1½×, 2½×, and 3½×. High-quality progressive downscaling limits aliasing and preserves text edges; upscaling uses high-quality interpolation but cannot create new detail. Page size, placement, and crop stay unchanged.','Choose the scale factor first, then PNG quality. At 100%, colors are preserved. Lower values reduce color precision after resizing to lower storage, autosave, and JSON size while retaining PNG format and transparency. Use 1× to change only compressed size, then inspect text, edges, and print DPI before confirming.'),
('immagini-url','🌐 Images from a URL','Direct URL loading embeds a public image in the project. CORS restrictions can prevent the browser from reading some sites.','Try direct loading first. When already signed into Puter, optionally use its network relay; otherwise download, copy, or upload the image.'),
('pdf-import','📑 Importing a PDF as images','PDF import runs locally and turns selected pages into fitted PNG images on new A4 pages.','Choose one page or all pages, destination, automatic or forced orientation, and a 1×–3× raster quality.'),
('crop','⌗ Non-destructive crop','Crop changes the visible window while retaining the complete source asset. The hidden portion appears translucent during editing.','Move or resize the crop frame, which starts at the current crop and cannot exceed the original image bounds. Reset restores the full image without stretching.'),
('colorizer','🎨 Colorizer: painting areas and objects','Colorizer rasterizes the selected object or group and supports connected-area fill plus an edge-aware or unrestricted brush.','Start Colorizer, zoom if needed, choose a tool, and paint. Each stroke or fill is one undoable operation and connected regions can be removed.'),
('colorizer-stili','🌈 Colors, gradients, and textures','Colorizations can use a solid color, directional gradient, radial gradient, or embedded texture with adjustable opacity.','Choose the paint type and parameters before filling or brushing. Radial gradients use the click point as their center.'),
('colorizer-originale','🧩 Colorizer original, groups, and clipboard','The colorized result is an ordinary image, while compact descriptors preserve the editable source without keeping a second decoded bitmap.','Copy the result or original, crop the result, or restore the original object when text, shapes, or group members need editing again.'),
('bianco-nero','◐ Black and white','Black-and-white conversion creates a non-destructive copy from sharp line art through softer grayscale rendering.','Select an image, adjust the intensity slider, and create the duplicate; compare it with the untouched original.'),
('outline-immagine','▱ Algorithmic image outline','Local edge extraction creates a printable outline copy without sending the image to an AI service.','Adjust edge sensitivity and create the duplicate. Simple, high-contrast source images usually give the cleanest result.'),
('sfondo-uniforme','⬜ Removing a solid background','Chroma-key removal targets a chosen or automatically detected edge color and can also clear enclosed internal areas.','Choose Solid background, detect or pick the color, adjust tolerance, and create a transparent duplicate.'),
('sfondo-ai','🧠 Local AI background removal','IMG.LY and ONNX process photographs in the browser after downloading the selected model. Mobile uses the smaller model and releases working RAM afterward.','Choose automatic, CPU, or WebGPU execution and start removal. The original stays in the project and the result is a new transparent image.'),
('ai','🎨 AI image generation','The Puter section combines a user prompt, style preset, output settings, optional reference, and any enabled chroma-key instruction into one final request. It does not inject a language rule for visible text; when text is required, state the exact wording and language in the prompt. The curated OpenAI family includes GPT Image 2, GPT Image 2.5 Flare, and GPT Image 2.5 Sunburst with Low, Medium, and High controls.','Sign in, choose a supported model, quality, ratio, and resolution, review the raw prompt and estimate, then explicitly press Generate and insert. The explanation under the quote follows the selected family: OpenAI uses the public output-token formula and a visual-token reference proxy; xAI uses fixed output and media-input prices; Seedream uses Puter’s fixed generation price; Gemini uses its 1K image-output tokens and Google visual-tile rules.'),
('prompt-library','📚 Prompt Library','Prompt Library stores reusable titles, tags, descriptions, prompts, styles, and optional reference images in browser storage. It is also the place to save recurring instructions that specify exact visible wording and its language.','Search or combine tag filters, open an entry, copy its text or image, use it, update it, delete it, or import/export the library as JSON.'),
('puter-credito','▰ Puter credits and usage','Account status separates global remaining credits, monthly allowance, purchased top-ups, and usage attributed to chicCanva.','Refresh manually or generate an image to update values. Price-list estimates are distinct from measured before/after cost for the last matching generation.'),
('puter-account','👤 Puter sign-in and account','AI and assisted downloads require an active Puter session. Signed-out controls remain disabled rather than opening a blocking authentication flow.','Use Sign in with Puter, Switch account, or Sign out in the AI section. Other widgets link back to this account area.'),
('clipart','🖼️ Clipart Explorer','The Openclipart explorer searches public-domain artwork using English keywords and displays a scrollable gallery capped at 12 lazy-loaded previews per page. Visited result pages remain cached until a new search, so previous and next navigation avoids repeated requests.','Search explicitly, optionally translate Italian keywords, preview a result, download it, or use Puter to download and insert it. In Italian UI, a parenthesized hint guides ambiguous translation without becoming part of the search or saved cache key. Delete saved translations clears only the shared Emoji/Clipart translation cache.'),
('stili-ai','🎭 AI style presets','Style presets append focused visual instructions for coloring pages, educational clipart, cartoons, pastels, stickers, geometry, and watercolor.','Choose From prompt to add nothing, or select a preset and inspect Full prompt sent before generating.'),
('riferimento-ai','📎 AI reference image','A reference can come from a file, URL, clipboard, Prompt Library, or the visible crop of a selected canvas image. Sent scale ranges from 0.25× to 3× and defaults to 1×. GPT Image 2.5 can add numbered semantic markers without changing the source.','Choose Flare or Sunburst and open Annotate reference image. Use a Spot for a precise point or Rectangle and Oval for an area. The bottom comment panel opens after drawing; enter the requested edit, save, and inspect the complete prompt before Generate. Sunburst is recommended for targeted changes. Stored data contains normalized geometry and comments only. At request time chicCanva creates an annotated copy at the same scaled size and sends both images in one Puter call; the estimate counts both inputs. Changing model preserves but disables annotations, while replacing or removing the reference clears them.'),
('ai-colorare','🖍️ Preparing an AI coloring page','Prepare coloring page transfers the selected canvas image as a reference and fills economical OpenAI, Low, and coloring-page defaults.','Review and edit the prepared prompt before pressing Generate. Preparation never starts generation by itself.'),
('ai-post','✂ Chroma key and automatic background copy','AI output can request a uniform chroma-key background and optionally start a second local background-removal operation.','Enable either option before generation. The generated original remains available even if post-processing cannot finish.'),
('griglia','# Grid, snapping, and guides','Grid snap and magnetic guides are independent. Guides align page centers, all four page edges, object edges or centers, and equal spacing during move, resize, and crop.','Configure grid, snap distance, rotation step, fitting margin, guide types, and aspect locking. The object menu offers Fit with margin and Fit without margin. Alt and Shift temporarily invert the relevant choices during a gesture.'),
('livelli','⇧ Layers and context menus','The toolbar arrows move the selection above or below by one level; their menus repeat those commands and also offer Move to top and Move to bottom. The canvas object menu exposes only the absolute top and bottom commands alongside compatible actions.','Use an arrow directly for one level. Right-click or long-press an arrow for all four choices; right-click an object on the canvas for the absolute commands.'),
('export-center','📤 Export center','The Export section produces PDF, PNG, or JPG from the current page, all project pages, or a selected page region.','Choose scope first and format second. Relevant DPI, quality, background, margin, download, clipboard, or ZIP controls then appear.'),
('pdf','📕 Exporting PDF','PDF preserves each page’s physical size and orientation and rasterizes the finished composition at the chosen DPI.','Export the current page or the complete project. Use 150 dpi for drafts and 300 dpi when final print detail matters.'),
('raster','🗂️ PNG, JPG, clipboard, and ZIP','PNG supports transparency and crisp graphics; JPG provides adjustable compression on white. Multiple pages are packaged into a client-side ZIP.','Choose page scope, format, DPI, background, and quality. A single page or region can also be copied directly to the clipboard.'),
('area-export','▣ Exporting a page region','The export-region tool draws an independent rectangle without selecting or moving objects underneath it.','Activate the toolbar area tool, draw over the required content, choose margin and output, then export or copy the region.'),
('json','🧰 Importing and exporting JSON','The chicCanva JSON format stores editable pages, objects, coordinates, fonts, assets, crops, settings, and optional history.','Export JSON for a durable editable backup. Import opens a new project tab and leaves currently open projects untouched.'),
('pwa','📲 Installing chicCanva as a PWA','On a public HTTPS domain, chicCanva can be installed with its own window, icon, and versioned offline application cache. The bottom install button is always present.','Open Install and use the button at the bottom. It triggers the native prompt when Chrome, Edge, or Android exposes it; otherwise the popup keeps the browser-specific instructions visible. On iPhone and iPad follow Safari Share → Add to Home Screen.'),
('mobile','📱 Using tablets and phones','The mobile layout uses an overlay sidebar, touch-sized handles, pinch zoom, long-press menus, and compact preview controls.','Open the panel only when choosing tools, close it for more canvas space, and keep autosave enabled during long sessions.'),
('privacy','🔐 Data, services, licenses, load, and version','Projects remain in browser storage unless you export or explicitly use a network service. Puter receives prompts and references only when requested.','Review memory load, image DPI, service choices, repository, version, build date, and third-party licenses at the bottom of the sidebar.'),
('controllo','✅ Final check before printing','A final Preview and Fit review catches missing pages, incorrect order, off-page objects, low-resolution images, and wrong formats.','Check every critical page, export a draft first, then keep both the editable JSON and final PDF or image files.')
]

WORKFLOWS=[
('Welcome banner','Generate one letter or group per page, choose landscape A4 and constant size, review in Preview, then export the complete project as PDF or a PNG ZIP.'),
('Colorable outline title','Add text with a round child-friendly font, keep Outline enabled, use a black border, split characters if each needs a different color, and export a print test.'),
('Poster with photo and captions','Upload and crop the photo, add a filled caption and outlined title, arrange layers, group decorations, save JSON, and export PDF.'),
('Reusable worksheet series','Finish one page, duplicate it, rename copies, replace only variable content, compare them in Preview, and export all pages.'),
('Transparent label','Group text and an OpenMoji, draw an export region, choose transparent PNG and a small margin, then copy or download the result.'),
('Coloring page without AI','Duplicate an image as outline or black and white, tune sensitivity, compare with the original, and keep the clearest printable version.'),
('Coloring page with AI','Prepare the selected image as a reference, review the economical coloring-page settings and prompt, then explicitly generate.'),
('Text with coordinated emoji','Add text with Smart emoji, ungroup it to adjust font and outlined emoji colors independently, then regroup the composition.'),
('Mixed portrait and landscape project','Create and name pages with different orientations, inspect them at equal scale in Preview, and export one mixed PDF.'),
('Sharing editable work','Export JSON with history when needed and include a PDF reference; the recipient imports it into a new tab.'),
('Working on a tablet','Install the PWA, use the overlay sidebar and tap selection, keep autosave enabled, and export JSON after an important session.'),
('Economical black-and-white printing','Create soft grayscale photo copies, use black outlines, export a 150 dpi test, and increase quality only when required.'),
('Square flashcards','Create one square page, duplicate it, rename cards, use snapping for consistent placement, and export all pages as PNG.'),
('Recovering from a mistake','Press Escape during a gesture, use Undo or the history list, resume autosave after refresh, and rely on exported JSON after an explicit project close.'),
('Comparing two ideas','Keep variants in separate project tabs, copy reusable objects between them, and compare output before closing either project.'),
('Turning a PDF handout into a project','Import every PDF page at 2× with automatic orientation, annotate the resulting A4 pages, then export the edited project.'),
('Digitally coloring a worksheet','Use connected fill for closed areas and the smart brush to repair small gaps, then apply distinct colors, gradients, or textures.'),
('Coloring an editable composition','Group text, shapes, and emoji, colorize the group, and restore the editable original whenever its components need changes.')]

FAQ=[
('Why does Colorizer fill outside an area?','The boundary may be open, too light, or close to the interior color. Undo, lower tolerance, close the gap with the smart brush, and fill again.'),
('Can I edit text or shapes after Colorizer?','Yes. Restore original object recreates the editable source. Copy or duplicate the colorized image first if you want to keep both.'),
('Why is Install missing?','Installation is shown only on a real HTTPS domain when the app is not already installed. It is intentionally hidden on file, localhost, IP, and private hosts.'),
('Why does a font look different?','The catalogue is embedded, but the selected font file downloads on first use. If a network filter blocks it, the browser temporarily uses a fallback font.'),
('Why can an image URL fail?','The link must return an image and permit cross-origin reading. Try Puter while signed in, or download/copy the image and upload/paste it.'),
('Why do multiple PNG or JPG pages create a ZIP?','A ZIP keeps each page as a separate named file and is assembled entirely in the browser.'),
('Why is PNG quality disabled?','PNG is lossless. Use DPI to control resolution; the quality slider applies to JPG compression.'),
('Why can JPG not be transparent?','JPG has no alpha channel, so chicCanva applies a white background.'),
('Will the grid be printed?','No. Grid lines, guides, selections, handles, and export rectangles are editor overlays only.'),
('Does zoom change print quality?','No. Zoom changes only the working view. Page dimensions, source images, and export DPI determine output.'),
('Why is rotation locked?','The rotation handle is opt-in to prevent accidental changes. Enable it only while rotating.'),
('Where did the other sidebar sections go?','With Expand one at a time enabled, opening one section collapses the others. Disable it or choose Expand sections.'),
('Can I change the font in text containing emoji?','Yes. Font changes reach text members of the mixed group. Ungroup to edit one member only.'),
('Does local background removal upload my photo?','No. IMG.LY and ONNX download code and a model, then process pixels in the browser.'),
('Why is the background model downloaded again?','The app, browser, or operating system may have cleared cached files to recover space.'),
('Can I work offline?','Core editing and export work with embedded and cached resources. Puter and resources never downloaded before still require a connection.'),
('What does project JSON save?','It saves editable state and embedded assets, plus history when that option is enabled.'),
('Does autosave replace JSON backup?','No. Autosave protects one browser and origin; JSON is the portable archival copy.'),
('How do I export one image?','Choose Current page or Selection on page. All pages creates a ZIP for raster formats.'),
('How do I keep pages consistent?','Build one template page, duplicate it, and use grids, snapping, guides, and ordered names.'),
('Why can AI post-processing take longer?','It is a second local segmentation process and may first need to load a model into memory.'),
('Which files should I keep?','Keep JSON for future edits and PDF/PNG/JPG for printing or sharing.'),
('Does imported PDF text remain editable?','No. Each imported PDF page becomes a PNG background; new chicCanva objects remain editable above it.')]

def section_html(item):
 sid,title,summary,steps=item
 return f'''<section id="{sid}"><h3>{title}</h3><p>{summary}</p><h4>How to use it</h4><p>{steps}</p><div class="guide-example"><strong>Practical example</strong><p>Apply this feature to one page first, inspect the result at Fit and in Preview, then repeat it across the project when the layout is correct.</p></div><h4>Keep in mind</h4><p>The operation remains compatible with the project’s pages, undo history, autosave, and export unless this section explicitly describes a conversion or replacement.</p><ul><li>Check the result on the canvas or in Preview before exporting.</li><li>Commands that create a copy preserve the source so you can compare or restore it.</li><li>Use Undo for unwanted canvas changes and keep a JSON backup for long-term editing.</li></ul></section>'''

toc=''.join(f'<a href="#{sid}">{title}</a>' for sid,title,*_ in TOPICS)
body=''.join(section_html(item) for item in TOPICS)
workflows=''.join(f'<article class="guide-example"><h4>{escape(title)}</h4><p>{text}</p><p><strong>Final check:</strong> verify page order, margins, image quality, and output format. Save JSON if the work must remain editable.</p></article>' for title,text in WORKFLOWS)
faq=''.join(f'<details><summary><strong>{escape(q)}</strong></summary><p>{a}</p></details>' for q,a in FAQ)
shortcuts='''<table><thead><tr><th>Shortcut</th><th>Action</th><th>When to use it</th></tr></thead><tbody><tr><td><kbd>Ctrl C</kbd> / <kbd>Ctrl V</kbd></td><td>Copy / paste</td><td>Across open pages and projects</td></tr><tr><td><kbd>Esc</kbd></td><td>Cancel current gesture</td><td>Move, resize, crop, or drawing without applying it</td></tr><tr><td><kbd>Ctrl D</kbd></td><td>Duplicate</td><td>Create a copy on the active page</td></tr><tr><td><kbd>Ctrl G</kbd> / <kbd>Ctrl Shift G</kbd></td><td>Group / ungroup</td><td>Manage multi-object compositions</td></tr><tr><td><kbd>Ctrl Z</kbd> / <kbd>Ctrl Y</kbd></td><td>Undo / redo</td><td>Navigate canvas history</td></tr><tr><td><kbd>Ctrl S</kbd></td><td>Export JSON</td><td>Save the editable project</td></tr><tr><td><kbd>Delete</kbd></td><td>Delete selection</td><td>Same as the circled × toolbar icon</td></tr><tr><td><kbd>F</kbd> / <kbd>H</kbd> / <kbd>V</kbd></td><td>Fit / hand / select</td><td>Change the current canvas tool</td></tr><tr><td><kbd>G</kbd> / <kbd>R</kbd></td><td>Grid / rotation</td><td>Toggle grid or rotation handle</td></tr><tr><td><kbd>Shift</kbd> while resizing, cropping, or drawing</td><td>Reverse aspect locking</td><td>Temporary constraint for the gesture</td></tr><tr><td><kbd>Alt</kbd> while moving</td><td>Reverse guides</td><td>Temporary magnetic alignment control</td></tr><tr><td><kbd>Shift Alt</kbd> while moving</td><td>Reverse classic snap</td><td>Guides remain temporarily disabled</td></tr><tr><td><kbd>F1</kbd></td><td>Guide</td><td>Open this manual</td></tr><tr><td><kbd>Ctrl</kbd> + wheel</td><td>Zoom</td><td>Zoom around the pointer</td></tr><tr><td>Arrows / <kbd>Shift</kbd> + arrows</td><td>Move 1 / 10 pixels</td><td>Precise adjustments</td></tr></tbody></table>'''
html=f'''<div class="guide-intro"><p><strong>chicCanva</strong> is Chicca’s workshop for posters, lettering, worksheets, illustrations, and printable classroom materials.</p><p class="guide-callout">Read the guide in order or use the contents. Bold names match controls and sidebar sections in the app.</p></div><div class="guide-shell"><details class="guide-toc" open><summary>Guide contents</summary><nav>{toc}<a href="#workflows">Guided workflows</a><a href="#shortcuts">Shortcuts</a><a href="#faq">Frequently asked questions</a></nav></details><div class="guide-body">{body}<section id="workflows"><h3>🗺️ Guided workflows</h3><p>These examples combine several tools in a tested order and can be adapted to a class, printer, or source material.</p>{workflows}</section><section id="shortcuts"><h3>⌨️ Complete shortcuts</h3><p>Shortcuts work while focus is outside a text field. On macOS, use Cmd for copy, paste, save, and history shortcuts.</p>{shortcuts}</section><section id="faq"><h3>❓ Frequently asked questions</h3><p>Open a question for practical, non-technical guidance about normal app behavior.</p>{faq}</section></div></div>'''
target=Path(__file__).with_name('help-v7-en.html');target.write_text(html,encoding='utf-8')
print(f'English guide generated: {len(html):,} characters, {len(TOPICS)} sections, {len(WORKFLOWS)} workflows, {len(FAQ)} FAQ')
