from pathlib import Path
from html import escape

SECTIONS = [
('orientarsi','🧭 Orientarsi nell’interfaccia','chicCanva divide il lavoro in quattro zone: barra principale, barra degli strumenti, foglio centrale e pannello laterale. La barra principale raccoglie le operazioni sul progetto; la barra del foglio controlla vista e oggetti; il centro mostra la pagina attiva; la sidebar contiene i widget ordinati per attività.','Apri il pannello con il pulsante in alto. Usa i collegamenti Pagina, Speciali, Testo, Font, Emoji, Immagini, Clipart, AI ed Export per raggiungere subito il widget desiderato. Se Espandi singolarmente è attivo, il widget scelto rimane l’unico aperto e lascia più spazio verticale.','Durante una lezione puoi tenere aperto Testo mentre prepari i titoli, passare a Clipart per cercare un’illustrazione e tornare a Pagina senza cercare la sezione scorrendo.','Le barre possono scorrere orizzontalmente sugli schermi piccoli. I tooltip compaiono passando il mouse sulle icone; su mobile la stessa informazione è riportata nei widget e in questa guida.'),
('progetti','📁 Progetti aperti e schede','Ogni scheda sopra il foglio rappresenta un progetto indipendente. Puoi tenere aperti più lavori, passare dall’uno all’altro e copiare oggetti fra progetti senza sovrascrivere ciò che era già sullo schermo.','Premi + Progetto, assegna un nome chiaro e conferma. Un doppio clic sul nome, F2 o il menu contestuale permettono di rinominarlo. La × chiude la scheda dopo un riepilogo sullo stato di esportazione; Esporta JSON e chiudi salva una copia prima della rimozione.','Puoi tenere aperti “Cartellone accoglienza”, “Etichette armadietti” e “Scheda numeri”, riutilizzando lo stesso stile mentre confronti i risultati.','Chiudere esplicitamente una scheda la rimuove anche dall’autosalvataggio. Se il progetto è importante, esporta sempre il JSON prima di chiuderlo o cancellare la memoria del browser.'),
('autosave','💾 Autosalvataggio e recupero','L’autosalvataggio conserva insieme tutti i progetti aperti, le pagine, gli oggetti e gli asset. Serve come rete di sicurezza contro refresh o chiusure accidentali; il JSON resta il formato corretto per archiviare e trasferire un lavoro.','Apri Memoria, lascia attivo Salva automaticamente e continua a lavorare. Alla successiva apertura scegli Riprendi progetto per recuperare lo spazio precedente oppure Nuovo progetto per cancellare la copia automatica e iniziare da zero.','Se il browser viene aggiornato mentre stai componendo un festone, al ritorno chicCanva propone data, ora e numero di progetti trovati.','La memoria appartiene all’indirizzo e al browser: file://, localhost e un dominio pubblico hanno archivi separati. La modalità privata può cancellare i dati alla chiusura.'),
('cronologia','↶ Annulla, ripristina e storico','La cronologia registra modifiche significative a oggetti, pagine e progetti. Annulla torna a uno stato precedente; Ripristina riapplica un passo annullato. Il contatore mostra la posizione nello storico disponibile.','Usa Ctrl+Z o ↶ dopo uno spostamento sbagliato. Usa Ctrl+Y, Ctrl+Maiusc+Z o ↷ per tornare avanti. In Memoria scegli quanti passi conservare e se includere lo storico nel JSON.','Dopo aver diviso un gruppo, cambiato font e spostato tre lettere puoi tornare indietro un passaggio alla volta, poi recuperare solo le operazioni desiderate.','Uno storico ampio occupa più memoria, soprattutto con molte immagini. Quando esegui una nuova modifica dopo Annulla, i passi successivi vengono sostituiti dalla nuova direzione di lavoro.'),
('pagine','📄 Creare e gestire le pagine','Ogni pagina ha nome, larghezza e altezza propri. Il pulsante + vicino al navigatore inserisce una nuova pagina subito dopo quella attiva e ne eredita formato e orientamento. Il widget Gestione pagina offre anche duplicazione ed eliminazione.','Premi +, rinomina la pagina, scegli un formato oppure scrivi dimensioni personalizzate e premi Applica formato. Usa Duplica quando vuoi conservare una base grafica; Elimina richiede prudenza e può essere recuperato con Annulla.','Prepara una copertina A4 verticale, una fascia panoramica personalizzata e alcune schede quadrate nello stesso progetto.','Il formato modifica l’area stampabile. Se riduci molto una pagina con oggetti già presenti, usa Adatta oggetti e controlla che nulla sia rimasto fuori dal foglio.'),
('formati','↔ Formati e orientamento','A4, A3, A5, US Letter, quadrato e Custom sono scorciatoie per dimensioni reali in millimetri. Ruota pagina scambia larghezza e altezza e aggiorna subito il canvas; non ruota gli oggetti singolarmente.','Seleziona il formato, usa ↔ Ruota pagina per passare da verticale a orizzontale e premi Applica formato quando modifichi a mano larghezza o altezza. Fit ricentra il nuovo foglio nello spazio disponibile.','Un cartellone può usare A3 orizzontale, mentre una scheda da consegnare ai bambini usa A4 verticale.','La stampante può aggiungere margini propri. chicCanva esporta le dimensioni indicate; verifica nel dialogo di stampa che la scala sia 100% se vuoi misure precise.'),
('nomi-riordino','🔢 Nomi e ordine delle pagine','Nomi descrittivi rendono leggibili anteprima, PDF e archivi ZIP. Le pagine possono essere riordinate dal navigatore con trascinamento o frecce e dalla Preview quando attivi Riordina.','Fai doppio clic sul pallino della pagina o usa il clic destro per rinominarla. Trascina il pallino nella nuova posizione; su mobile usa Prima e Dopo. In Preview seleziona Riordina e sposta la miniatura con drag oppure frecce.','Nomi come “01 Copertina”, “02 Regole”, “03 Attività” aiutano anche quando esporti le pagine come immagini.','Il numero visualizzato segue sempre l’ordine attuale. Il nome resta associato alla pagina e viene ripulito automaticamente dai caratteri non validi quando diventa un nome file.'),
('preview','▦ Preview di tutte le pagine','Preview apre una griglia scorrevole dell’intero progetto. Pagine verticali e orizzontali mantengono la propria forma e usano la stessa scala del lato lungo, così un progetto misto rimane confrontabile.','Apri Preview, regola Dimensione, clicca una miniatura per modificarla. Per cambiare ordine attiva Riordina, seleziona una pagina e usa le frecce oppure trascina. Doppio clic e menu destro rinominano senza uscire.','Prima di esportare un quaderno di attività controlla coerenza dei titoli, alternanza degli orientamenti e presenza di pagine vuote.','Le miniature sono anteprime leggere. L’export finale usa i DPI scelti e può risultare più nitido della griglia.'),
('vista','🔍 Zoom, Fit, manina e pinch','Zoom modifica soltanto la vista di lavoro. Fit calcola lo spazio realmente libero fra toolbar e sidebar e centra il foglio. La manina usa un’ampia area libera attorno alla pagina, così puoi portare ogni bordo al centro anche con forti ingrandimenti. Su telefoni, tablet e computer touch il pinch combina zoom e spostamento.','Scegli Fit dal menu oppure premi F. Usa +, − o Ctrl+rotella per ingrandire. Premi H o l’icona manina e trascina il piano in ogni direzione; premi V per tornare alla selezione. Con due dita, allontanale o avvicinale per cambiare zoom e muovi contemporaneamente il punto medio per spostare il foglio.','Ingrandisci al 200% per rifinire un apostrofo, trascina fino a portare anche il bordo destro al centro e torna a Fit per controllare l’impaginazione. Su tablet puoi ottenere la stessa regolazione con un solo gesto a due dita.','Lo zoom non altera dimensioni, qualità o stampa. Durante il pinch chicCanva usa una vista leggera e stabile, poi ridisegna una sola volta alla qualità corretta quando sollevi le dita. La modifica degli oggetti resta sospesa durante il gesto.'),
('selezione','▧ Selezione singola e multipla','Un clic seleziona un oggetto. Ctrl+clic aggiunge o rimuove elementi dalla selezione. La modalità selection box permette di trascinare un rettangolo sul vuoto e prendere più oggetti insieme.','Attiva V o l’icona ▧. Clicca un elemento, usa Ctrl per aggiungerne altri oppure trascina attorno al gruppo. Ctrl+A seleziona gli oggetti della pagina. Clicca il fondo per deselezionare.','Seleziona titolo, stelline e immagine per spostarli insieme senza creare subito un gruppo permanente.','Il rettangolo di export è un oggetto guida separato. Se vuoi selezionare elementi normali, esci dalla modalità area di export e riattiva V.'),
('trasformazioni','↗ Spostare, ridimensionare e ruotare','Le maniglie angolari ridimensionano mantenendo le proporzioni; il trascinamento interno sposta. La rotazione è bloccata all’avvio per evitare errori e compare solo quando attivi Rotate.','Seleziona l’oggetto, trascinalo o usa le frecce per movimenti di 1 pixel; Maiusc+freccia usa 10 pixel. Trascina un angolo per la scala. Premi R e usa la maniglia superiore per ruotare.','Allinea a occhio una parola inclinata e poi disattiva Rotate per continuare a ridimensionare senza girarla accidentalmente.','Per le scritte outline lo scaling resta vettoriale. Le foto mantengono il file sorgente: la qualità finale dipende dalla risoluzione originale e dai DPI di export.'),
('appunti','⧉ Copia, incolla e duplica','Copia conserva negli appunti interni dell’app gli oggetti selezionati e gli asset necessari. Incolla funziona su un’altra pagina o scheda progetto. Duplica crea subito una copia spostata nella pagina corrente. Incolla speciale legge invece un’immagine copiata da un sito o da un’altra applicazione.','Usa Ctrl+C e Ctrl+V oppure le icone per gli oggetti. Ctrl+D duplica. Se negli appunti di sistema è presente un’immagine, Ctrl+V la inserisce nel canvas; puoi anche usare l’icona Incolla speciale o i pulsanti nei widget Immagini e Riferimento AI.','Copia una cornice fra pagine con gli appunti interni; poi copia una fotografia dal browser e incollala direttamente nel foglio o come riferimento AI.','La lettura degli appunti di sistema richiede il permesso del browser e funziona in un contesto sicuro, come HTTPS o localhost. Se il permesso viene negato, usa Carica immagine.'),
('gruppi','⊞ Raggruppare e dividere','Raggruppa trasforma una selezione multipla in un solo oggetto composito. Il bordo viola più spesso segnala il gruppo. Dividi gruppo restituisce i componenti, mantenendoli selezionati per un intervento immediato.','Seleziona almeno due elementi e usa Ctrl+G o ⊞. Sposta, scala o ruota il gruppo. Usa Ctrl+Maiusc+G o ⊟ per separarlo. Puoi poi selezionare solo una parte e creare un nuovo gruppo.','Raggruppa un titolo con due emoji decorative; in seguito dividi il gruppo per cambiare solo il colore delle emoji outlined.','Un gruppo può contenere altri tipi di oggetto, incluse immagini e scritte. Il font viene applicato ai testi contenuti senza trasformare le immagini.'),
('testo','✏️ Aggiungere testo','Il widget Aggiungi testo è l’unico punto di ingresso per le scritte. Può inserire una frase come oggetto unico oppure produrre un oggetto per lettera o gruppo, senza cancellare ciò che esiste già sulla pagina.','Scrivi il contenuto, scegli MAIUSCOLO se serve, seleziona l’adattamento e premi Aggiungi testo. Attiva Un oggetto per lettera/gruppo solo quando vuoi manipolare le parti separatamente.','Inserisci “BENVENUTI” come frase per una copertina oppure come lettere separate per creare un arco colorato.','Il font, il colore e il contorno correnti valgono per i nuovi testi. Se alcuni oggetti sono selezionati, i comandi di stile possono aggiornare la selezione esistente.'),
('fit-testo','↔ Adattare il contenuto','L’adattamento può contenere tutto nel foglio, riempire la larghezza o riempire l’altezza. Contieni è sicuro; larghezza e altezza privilegiano un asse e possono far uscire l’altro dal foglio quando le proporzioni sono molto diverse.','Scegli Contieni per cartelloni completi. Scegli Larghezza per titoli orizzontali e Altezza per una lettera alta. Dopo l’inserimento usa Adatta selezione dal menu destro se vuoi correggere solo alcuni elementi.','Una singola “A” su A4 può riempire l’altezza; una frase lunga come “BUONE VACANZE” riempie meglio la larghezza.','L’adattamento lascia un margine di sicurezza. Aumenta manualmente solo dopo aver controllato che contorni e maniglie restino dentro la pagina.'),
('simboli','’ Simboli e apostrofo intelligente','Quando crei oggetti separati, le liste dei simboli decidono quali segni restano con il carattere precedente o successivo. L’apostrofo intelligente osserva gli spazi per evitare una pagina dedicata al solo apostrofo.','Attiva Un oggetto per lettera/gruppo. Inserisci nella prima lista punteggiatura da legare a sinistra e nella seconda parentesi o segni da legare a destra. Lascia attivo Apostrofo intelligente per parole italiane.','“L’ AMICO” può tenere l’apostrofo con L; dopo uno spazio, un segno iniziale può unirsi al carattere successivo.','Le stesse regole vengono usate da Splitta testo e dalla funzione speciale una lettera/gruppo per pagina.'),
('split','✂ Splittare un testo esistente','Splitta converte un oggetto di testo già presente in lettere e gruppi secondo le regole correnti. I pezzi rimangono selezionati e possono essere raggruppati, distanziati o colorati separatamente.','Seleziona un singolo oggetto testuale, imposta simboli e apostrofo nel widget Testo e premi Splitta. Se il testo produce un solo gruppo, l’app lo segnala senza modificarlo.','Scrivi prima una frase per scegliere font e dimensione; quando sei soddisfatto, splittala per dare un colore diverso a ogni lettera.','Le emoji già trasformate in OpenMoji sono immagini separate. Dividi prima un eventuale gruppo misto se vuoi agire su testo ed emoji individualmente.'),
('speciale','✨ Una lettera o gruppo per pagina','La funzione speciale crea rapidamente festoni e cartelloni: suddivide un testo e prepara una pagina per ogni risultato. Può aprire un progetto nuovo, aggiungere pagine al progetto attivo o rimpiazzarle dopo conferma.','Apri Speciali, scrivi il testo, scegli orientamento e adattamento. Imposta destinazione Nuovo progetto per proteggere il lavoro corrente. Controlla simboli, apostrofo e Smart emoticon, poi avvia.','“BENVENUTI 👋” genera pagine stampabili con lettere grandi e una pagina OpenMoji, mantenendo i raggruppamenti previsti.','La generazione di molte pagine può richiedere qualche secondo perché ogni font ed emoji viene preparato come asset del progetto.'),
('gruppi-espliciti','^ Gruppi espliciti','Gruppi espliciti sostituisce la suddivisione automatica: il carattere ^ nel campo di testo indica esattamente dove iniziare una nuova pagina. Le opzioni incompatibili diventano grigie per rendere chiara la regola attiva.','Attiva Gruppi espliciti e inserisci il separatore fra i blocchi. Gli spazi interni restano parte del testo; gli spazi attorno al separatore vengono ripuliti. Controlla l’anteprima del numero di gruppi.','“questa^è una^prova” crea tre pagine: “questa”, “è una” e “prova”.','Il simbolo ^ viene usato come comando e non viene stampato. Disattiva Gruppi espliciti se desideri inserirlo come carattere normale.'),
('font-diretti','🔤 Ricerca e scelta diretta dei font','Il catalogo incorporato contiene circa 2.100 famiglie e resta esplorabile anche quando un servizio esterno è bloccato. La ricerca usa nome e parole di stile; le categorie possono sovrapporsi perché descrivono l’aspetto più che una classificazione rigida.','Digita un nome oppure termini come rotondo, bambino, serif o scrittura. Scegli una categoria e scorri i risultati. Clicca una tessera per scaricare e applicare il font; il campione mostra Outline.','Confronta Fredoka, Baloo e Comfortaa nella categoria rotondi per un titolo destinato alla scuola dell’infanzia.','Il catalogo è locale, ma il file del font scelto viene richiesto a Google Fonts o Fontsource. Se è bloccato, l’app usa un carattere di sistema e conserva comunque il progetto.'),
('wizard-font','🪄 Wizard dei caratteri','Il wizard valuta l’intero catalogo in base a peso visivo, rotondità, espressività e bordo desiderato. “Cicciottello” indica forme ampie, morbide e facili da colorare, non soltanto un peso tipografico bold.','Muovi gli slider, osserva il nome proposto e la sua anteprima separata, poi applica. Ripeti piccole variazioni per confrontare rapidamente alternative vicine.','Per bambini piccoli aumenta rotondità e corpo e mantieni media l’artisticità; per titoli robotici riduci rotondità e aumenta la componente squadrata.','I profili curati hanno precedenza; gli altri sono stimati da nome e categoria. Il risultato è un aiuto creativo, non un giudizio assoluto sul font.'),
('outline','◯ Outline, colore e spessore','In modalità Outline l’interno delle lettere è trasparente e il bordo usa il colore scelto. Lo spessore è regolabile e rende le scritte adatte alla colorazione. Disable Outline mode usa invece un testo pieno standard.','Scegli nero per schede da colorare, aumenta gradualmente il bordo e controlla gli spazi interni. Disattiva Outline per didascalie piccole o testi da leggere senza colorare. Applica stile aggiorna i testi selezionati.','Un titolo alto può usare bordo 4–6, mentre una parola piccola richiede un bordo più sottile per non chiudere A, O o R.','Alcuni font sono outline nativi: conservano il proprio disegno anche quando disabiliti la modalità. Per un riempimento pieno scegli una famiglia standard.'),
('emoji','😀 Esplorare OpenMoji','Il catalogo OpenMoji completo offre Più rilevanti, Tutte e categorie tematiche, oltre alla ricerca globale. Le descrizioni ufficiali sono in inglese: la traduzione automatica opzionale accetta parole italiane e resta disattivata all’avvio. Ogni emoji viene importata come immagine vettoriale.','Scegli Colore oppure Black/outline, filtra una categoria e usa Mostra altre per proseguire. Per cercare in italiano attiva Traduzione automatica, poi scrivi la parola: chicCanva prova il servizio online, quindi il dizionario didattico locale e infine il termine originale. Clicca una tessera per inserirla.','Cerca “school” direttamente oppure attiva la traduzione e cerca “scuola”, “matita” o “sole” per decorare un calendario delle presenze.','OpenMoji usa licenza CC BY-SA 4.0, indicata nel progetto. Il catalogo locale è completo; i singoli SVG nuovi richiedono rete la prima volta. La traduzione online è opzionale e il fallback locale resta sotto 1 MB.'),
('emoji-outline','🖍️ Colore e bordo delle emoji outline','La variante Black/outline può cambiare colore e spessore senza alterare l’originale OpenMoji. Le impostazioni valgono per i nuovi inserimenti; Applica selezione crea asset derivati per le emoji già selezionate.','Scegli il colore, regola lo spessore e inserisci l’emoji. Per aggiornare elementi esistenti, selezionali anche dentro un gruppo divisibile e premi Applica selezione.','Usa contorni neri spessi per una scheda da colorare oppure il colore della classe per icone decorative leggere.','Lo spessore eccessivo può chiudere dettagli piccoli. Controlla la resa alla dimensione di stampa, non soltanto con lo zoom molto alto.'),
('smart-emoji','🙂 Smart emoticon nel testo','Smart emoticon riconosce le emoji Unicode digitate o incollate nel testo e le sostituisce con OpenMoji. Testo ed emoji diventano componenti separati dentro un gruppo, così il font continua ad applicarsi solo alle lettere.','Lascia attiva Smart emoticon e aggiungi testo. Seleziona il gruppo per muoverlo intero; usa Dividi gruppo per cambiare colore, posizione o dimensione di una singola emoji.','“BRAVI ⭐” produce una scritta e una stella OpenMoji coordinata; puoi poi ingrandire soltanto la stella.','Le sequenze emoji vengono analizzate come grafemi completi, incluse molte varianti con tono della pelle e joiner.'),
('immagini','🖼️ Caricare immagini dal dispositivo','Carica immagine legge PNG, JPG, WebP, SVG e altri formati supportati dal browser, li incorpora negli asset e crea un oggetto nel canvas. Il progetto non dipende più dal file originale dopo il caricamento.','Premi Carica immagine, scegli il file e attendi la comparsa sul foglio. Sposta e ridimensiona, poi usa crop o trasformazioni senza distruggere il sorgente.','Inserisci una foto dell’attività, ridimensionala a metà pagina e aggiungi un titolo outline sopra.','Immagini molto grandi rendono autosalvataggi e JSON pesanti. Riduci la risoluzione prima del caricamento quando non serve qualità fotografica elevata.'),
('immagini-url','🌐 Immagini da URL','Da URL legge un collegamento diretto e incorpora il risultato nel progetto. Il download diretto è predefinito e non usa Puter, ma può essere bloccato dal CORS del sito remoto. La checkbox Usa Puter per scaricare l’immagine offre un secondo percorso esplicito attraverso puter.net.fetch.','Incolla un indirizzo HTTP/HTTPS diretto e prova prima Carica. Se vuoi usare Puter devi avere già effettuato l’accesso nella sezione Generazione immagini AI · Puter. Da sloggato la checkbox resta disabilitata e deselezionata; il link Vai al login chiude il dialogo, apre la sezione AI e porta il cursore sul pulsante di accesso. Dopo il login riapri Da URL e abilita Puter. Puoi anche copiare l’immagine e usare Incolla immagine dagli appunti.','Un CDN che abilita CORS funziona direttamente. Un server che lo vieta può funzionare tramite Puter o, quando usi il launcher locale, tramite il suo endpoint limitato alle immagini pubbliche.','Puter applica il modello user-pays anche alla rete: il trasferimento usa banda o quota dell’account dell’utente, distinta dai token della generazione AI. Il ripiego PowerShell non usa Puter, rifiuta indirizzi locali o privati e limita ogni file a 12 MB.'),
('pdf-import','📑 Importare un PDF come immagini','Importa PDF come immagini apre un documento locale con PDF.js e trasforma le pagine scelte in PNG. Ogni risultato viene inserito da solo in una pagina A4 e adattato senza deformazioni. Puoi importare una pagina specifica o l’intero PDF, creare un nuovo progetto oppure aggiungere le pagine al progetto corrente.','Premi Importa PDF come immagini e seleziona il file. Dopo la lettura, scegli Tutte le pagine oppure Una pagina specifica e indica il numero mostrato nell’intervallo disponibile. Scegli Nuovo progetto o Aggiungi al progetto corrente, poi orientamento Auto, Verticale o Orizzontale. Regola Qualità da 1× a 3× e avvia.','Importa una dispensa di sei pagine in un nuovo progetto: con Auto, una copertina verticale diventa A4 verticale e una scheda panoramica diventa A4 orizzontale. Se ti serve solo la pagina 4, usa l’opzione specifica.','1× crea file più leggeri, 2× è il valore consigliato per testi leggibili, 3× conserva più dettaglio ma aumenta memoria, autosalvataggio e dimensione del JSON. Il PDF non viene caricato online; le pagine diventano immagini e il loro testo non resta modificabile come testo chicCanva.'),
('crop','⌗ Crop non distruttivo','Crop modifica la finestra visibile di un’immagine e conserva l’asset completo. Durante la regolazione la parte scelta resta nitida, mentre il resto della sorgente appare in trasparenza per aiutarti a recuperare l’inquadratura.','Seleziona una sola immagine e premi Crop mode. Sposta o ridimensiona il rettangolo: Applica crop conferma, Annulla torna al ritaglio precedente. Il rettangolo parte esattamente dal crop già visibile e non può superare i bordi della sorgente originale. Applica crop conferma, Annulla torna al ritaglio precedente. Reset crop è disponibile sia nel widget sia nei comandi sotto al foglio e ripristina l’immagine intera mantenendo proporzioni e scala, senza deformarla.','Ritaglia una fotografia di classe per mostrare solo il cartellone. La sagoma traslucida permette di vedere cosa resta fuori; usa Reset crop se vuoi ripartire dall’intera fotografia.','Il crop segue le coordinate locali e rimane coerente anche con immagini ruotate. Per evitare ambiguità, termina il crop prima di cambiare pagina.'),
('bianco-nero','◐ Bianco e nero','Duplica e converti in B/N crea una nuova immagine in scala di grigi. Lo slider va dalla resa più netta “al tratto” alla versione soft con più sfumature; l’originale resta sempre nel canvas.','Seleziona l’immagine, regola lo slider e premi il pulsante. Confronta la copia spostata con l’originale e cancella quella che non serve.','Per una fotografia da fotocopia usa Soft; per un simbolo o un disegno semplice avvicinati ad Al tratto.','La trasformazione è locale e immediata. Non ricostruisce linee mancanti e non interpreta il soggetto come farebbe un modello generativo.'),
('outline-immagine','▱ Outline algoritmico','Duplica e rendi outline usa un rilevatore di bordi nel browser. La sensibilità decide quanti cambi di luminosità diventano linee nere su fondo bianco. Non invia file e non consuma crediti AI.','Seleziona una foto o un disegno, imposta una sensibilità media e genera la copia. Aumenta se mancano dettagli; riduci se il foglio diventa troppo rumoroso.','Un’illustrazione con colori piatti produce contorni puliti; una foto ricca di texture può richiedere sensibilità bassa.','Il risultato è un’estrazione matematica dei bordi, quindi non sempre è un buon disegno da colorare. In quel caso usa Prepara disegno da colorare con AI.'),
('sfondo-uniforme','⬜ Rimozione di uno sfondo uniforme','Sfondo uniforme elimina pixel simili al colore target. Il rilevamento automatico cerca il colore dominante lungo i bordi; la pipetta consente invece di campionare un punto preciso del foglio anche con zoom, Fit o vista spostata. La barra Tolleranza si trova sotto i controlli colore: un valore basso richiede una corrispondenza precisa, mentre una tolleranza alta include più variazioni.','Seleziona l’immagine e scegli Sfondo uniforme. Lascia attivo Rileva colore automaticamente oppure disattivalo e usa la pipetta accanto al colore. Regola Tolleranza e avvia Duplica senza background. Per impostazione iniziale vengono rimosse anche le aree interne dello stesso colore.','Genera una figura su uno sfondo verde uniforme, lascia attivo il rilevamento automatico e ottieni una copia trasparente senza selezionare manualmente il verde.','Se il soggetto contiene dettagli dello stesso colore dello sfondo, riduci la tolleranza oppure disattiva Rimuovi anche nelle aree interne. L’originale resta sempre invariato.'),
('sfondo-ai','🧠 Rimozione sfondo AI locale','La rimozione AI usa IMG.LY e ONNX nel browser. L’immagine non viene inviata a un servizio; al primo uso viene scaricato il modello scelto. Su desktop il modello rimane pronto in memoria per gli usi successivi. Su mobile chicCanva forza il modello Piccolo, riduce soltanto immagini eccessive e libera il processo AI al termine.','Scegli AI, modello e CPU/GPU. Avvia Duplica senza background e attendi spinner, progresso e scansione. Su mobile il selettore modello è bloccato su Piccolo per contenere la RAM; il file scaricato resta nella cache e non occupa RAM quando non è caricato.','Su computer puoi confrontare Piccolo, Medio e Grande. Su telefono usa un’immagine ben illuminata e con soggetto netto: al termine il messaggio conferma che la memoria AI è stata liberata.','Il browser può liberare la cache se lo spazio scarseggia. Memoria → Cancella dati salvati e modelli elimina anche i file del modello dalla cache.'),
('ai','🎨 Generazione immagini AI','Il widget Puter crea immagini e le inserisce come asset. Provider, modello, qualità, proporzioni e stile definiscono la richiesta; il prompt descrive soggetto e dettagli. Lo spinner resta visibile fino al risultato.','Scegli provider e modello, qualità e aspect ratio. Seleziona Da Prompt oppure uno stile didattico, scrivi il prompt e premi Genera e inserisci. Controlla sempre il risultato prima di stamparlo.','Chiedi “un albero con quattro stagioni, forme semplici, sfondo chiaro” e usa lo stile illustrazione educativa.','La generazione richiede webserver o dominio, connessione e un account Puter secondo le regole user-pays del modello. chicCanva non avvia una richiesta senza il clic esplicito su Genera.'),
('puter-credito','▰ Credito e consumo Puter','Quando l’utente è già collegato a Puter, il widget AI mostra il credito mensile assegnato a chicCanva, la parte consumata e quella ancora disponibile. I dati arrivano direttamente da Puter e riguardano soltanto le chiamate effettuate da questa applicazione.','Apri il widget AI dopo avere effettuato l’accesso a Puter. Premi Aggiorna per rileggere i valori. La barra si aggiorna anche dopo una generazione o un inserimento Clipart tramite Puter.','Prima di generare una serie di immagini puoi controllare la percentuale residua, creare un primo esempio e aggiornare il dato prima di continuare.','Puter esprime le risorse in microcent; chicCanva le converte in dollari e mostra anche la percentuale. La barra resta nascosta da file e quando l’utente non è collegato. I dati sono mensili e limitati all’app, quindi possono differire dal totale generale mostrato nell’account Puter.'),
('puter-account','👤 Accesso e account Puter','Le funzioni AI restano nascoste finché non colleghi un account Puter. Dopo l’accesso il widget mostra il nome dell’account, i comandi Cambia account e Logout, le impostazioni AI e il consumo disponibile. chicCanva non avvia automaticamente il login.','Premi Accedi con Puter per usare l’AI e completa la finestra Puter. Usa Cambia account quando vuoi scegliere un’identità diversa; usa Logout per scollegare il sito. Senza sessione, le opzioni di download Puter in Immagini e Clipart sono disabilitate e deselezionate. Il link Vai al login porta a questa sezione senza aprire dialoghi sovrapposti.','Su un computer condiviso accedi prima della generazione, controlla l’account indicato e usa Logout al termine. Dopo l’accesso riapri il dialogo URL o l’anteprima Clipart e abilita l’opzione Puter.','Il cambio account usa il selettore ufficiale Puter. Login e logout riguardano la sessione Puter concessa a questo sito; da file:// la sezione resta disabilitata perché l’SDK richiede un’origine web.'),
('clipart','🖼️ Explorer Clipart','Il widget Clipart cerca direttamente nelle pagine pubbliche di Openclipart senza API key e senza scaricare un catalogo completo. Le categorie sono scorciatoie di ricerca curate; le miniature vengono caricate solo quando servono.','Scrivi una parola inglese oppure scegli una categoria e premi Cerca. Se scrivi in italiano puoi attivare Traduzione automatica. Seleziona Anteprima per vedere l’immagine grande e le opzioni di utilizzo. Attiva il comando Puter soltanto se vuoi mostrare Inserisci direttamente sulle schede.','Cerca “child reading”, “school pencil” oppure scegli Animali. Apri la clipart preferita, salvala oppure inseriscila nel foglio attraverso Puter.','La traduzione prova prima il servizio gratuito MyMemory; se non risponde usa un piccolo dizionario incorporato per le parole didattiche più comuni, altrimenti conserva il termine originale. La ricerca prova Openclipart dal browser e, su localhost, passa automaticamente al webserver PowerShell quando CORS o un’estensione la bloccano. Salva su dispositivo crea un download reale quando i byte sono accessibili; copia manuale e Puter restano percorsi alternativi. Openclipart indica le proprie condizioni nella pagina collegata dal widget.'),
('stili-ai','🎭 Preset di stile AI','I preset aggiungono istruzioni interne al prompt senza cancellare le parole dell’utente. Da Prompt non aggiunge nulla; gli altri orientano il modello verso illustrazioni semplici, outline, colori piatti, bianco e nero o pagine da colorare.','Scrivi prima il contenuto concreto, poi scegli lo stile. Cambia preset se il risultato è troppo realistico o complesso. Usa Pagina da colorare per contorni chiusi, nero su bianco e aree ampie.','Lo stesso prompt “una volpe legge un libro” può diventare poster a colori, pittogramma o disegno da colorare cambiando solo il preset.','Il modello interpreta le istruzioni e può variare. Specifica nel prompt gli elementi indispensabili, il numero di soggetti e ciò che non deve apparire.'),
('riferimento-ai','📎 Immagine di riferimento AI','Un riferimento aiuta il modello a mantenere soggetto, posa o composizione. Può arrivare da file, dall’immagine selezionata nel canvas o da un URL leggibile dal browser. La miniatura conferma cosa verrà inviato.','Allega o scegli Dal canvas, seleziona un provider compatibile e descrivi nel prompt cosa conservare e cosa trasformare. Rimuovi riferimento con × quando vuoi tornare alla generazione da testo.','Seleziona una foto di un oggetto costruito in classe, applica e conferma il crop desiderato, poi scegli Dal canvas. Il riferimento usa la sola porzione ritagliata; rotazione, scala e posizione usate per impaginare il foglio non vengono applicate.','Il riferimento viene inviato solo quando premi Genera. OpenAI Image, Gemini e xAI supportano il flusso configurato; per altri modelli l’interfaccia segnala l’incompatibilità.'),
('ai-colorare','🖍️ Preparare un disegno da colorare con AI','Prepara disegno da colorare con AI non genera subito. Copia l’immagine selezionata come riferimento, apre il widget AI e imposta OpenAI Image 2, qualità Low, preset Pagina da colorare e un prompt pronto da rivedere.','Seleziona l’immagine nel canvas e premi Prepara. Leggi prompt e riferimento, modifica eventuali dettagli e solo alla fine premi Genera e inserisci.','Parti dalla fotografia di un animale e chiedi di conservare posa e caratteristiche, trasformandolo in contorni grandi adatti ai bambini.','Qualità Low riduce il consumo iniziale. Puoi cambiarla prima della richiesta se ti serve maggiore definizione.'),
('ai-post','✂ Chroma key e copia AI senza sfondo','Genera con sfondo uniforme per chroma key aggiunge al prompt la richiesta di un colore piatto che contrasti con il soggetto. Duplica il contenuto generato e rimuovi lo sfondo avvia una seconda elaborazione dopo una generazione riuscita. L’immagine originale generata resta disponibile e accanto viene inserita una copia trasparente usando il metodo e il modello di rimozione scelti nel widget Immagini.','Configura prima Rimozione sfondo, poi attiva la checkbox nel widget AI e genera. Attendi il secondo progresso: il lavoro termina quando il messaggio conferma entrambe le immagini.','Genera un personaggio illustrato su fondo semplice e ottieni automaticamente anche la versione pronta da sovrapporre a un cartellone.','La seconda elaborazione può scaricare un modello locale e richiedere più tempo. Se fallisce, l’immagine AI originale rimane comunque nel progetto.'),
('griglia','# Griglia e snap','Griglia mostra riferimenti sul foglio senza stamparli. Snap aggancia lo spostamento a passi regolari ed è indipendente: puoi vedere una griglia da 10 mm e agganciare ogni 5 mm, oppure usare snap senza griglia.','Attiva le icone dedicate e imposta le spaziature nel widget Canvas, griglia e snap. Trascina un oggetto per osservare l’aggancio. Disattiva snap per rifiniture libere.','Usa griglia 10 mm per una scheda e snap 5 mm per allineare tessere e immagini con mezzi passi.','Lo snap agisce durante lo spostamento. Dimensioni e rotazioni restano libere, così puoi mantenere proporzioni precise.'),
('livelli','⇧ Livelli e menu contestuale','Porta davanti e Porta dietro cambiano l’ordine visivo. Il menu destro raccoglie copia, incolla, raggruppa, splitta, crop, riferimento AI, rimozione sfondo ed eliminazione in base al tipo selezionato.','Seleziona un oggetto e usa le frecce di livello nella toolbar oppure clic destro. Le voci non pertinenti alle immagini risultano disabilitate.','Porta un titolo davanti a una forma colorata oppure manda una fotografia dietro una cornice.','L’ordine riguarda la pagina attiva. Un gruppo si muove come singolo livello finché non viene diviso.'),
('export-center','📤 Centro Esporta','Esporta progetto o selezioni riunisce gli output pronti: PDF, PNG e JPG. Prima scegli cosa esportare, poi il formato; l’interfaccia mostra soltanto DPI, qualità, sfondo, margine e area utili per quella combinazione. Per una pagina o una selezione in PNG/JPG compare anche Copia negli appunti.','Scegli Tutte le pagine, Pagina corrente o Selezione nella pagina. Seleziona PDF, PNG o JPG e controlla il testo del pulsante, che anticipa il risultato. Usa Copia negli appunti per riutilizzare subito la pagina o la selezione in un’altra app o come riferimento AI.','Per inviare il progetto alla tipografia usa PDF completo; per una presentazione usa PNG; per fotografie leggere usa JPG. Una selezione copiata può essere incollata nel widget del riferimento AI.','La scrittura di immagini negli appunti richiede HTTPS o localhost e il permesso del browser. Alcuni browser accettano solo PNG: in quel caso un JPG viene copiato automaticamente come PNG compatibile. Esporta JSON resta separato perché salva il progetto modificabile.'),
('pdf','📕 Esportare PDF','Il PDF conserva dimensioni e orientamento di ogni pagina, anche in progetti misti. I contenuti vengono rasterizzati ai DPI scelti per mantenere la resa di font, emoji, crop e immagini.','Seleziona progetto o pagina, formato PDF e DPI. Dalla barra superiore Esporta PDF apre una scelta rapida fra pagina corrente e progetto completo.','150 dpi è adatto a bozze e uso quotidiano; 300 dpi offre più dettaglio in stampa ma crea file più grandi.','Il PDF usa sfondo bianco. Controlla che la stampante non applichi Adatta alla pagina se vuoi rispettare le misure reali.'),
('raster','🗂️ PNG, JPG, appunti e ZIP','PNG supporta trasparenza ed è adatto a grafica, contorni e riuso digitale. JPG usa sfondo bianco e qualità regolabile, utile per fotografie. Se esporti più pagine, chicCanva crea uno ZIP client-side con un file per pagina e nomi ordinati.','Scegli PNG o JPG, DPI e qualità. Per PNG scegli sfondo trasparente o bianco. Con Tutte le pagine avvia lo ZIP; con Pagina corrente scarica l’immagine oppure usa Copia negli appunti.','Un progetto di dodici flashcard può diventare uno ZIP di dodici PNG; una singola flashcard può essere copiata e incollata subito come riferimento nel generatore AI.','PNG è senza perdita: lo slider qualità viene disattivato. JPG a 85–92% offre spesso un buon equilibrio fra peso e dettaglio. La copia negli appunti non crea un file sul dispositivo.'),
('area-export','▣ Esportare una selezione della pagina','La selezione di export è un rettangolo guida indipendente dalla selezione oggetti. Può includere margine aggiuntivo e sfondo trasparente o bianco. Il rettangolo non compare nel file finale.','Premi l’icona area nella toolbar: la sidebar apre Export, imposta Selezione nella pagina, PNG e trasparenza. Trascina l’area, regola margine e formato, poi esporta. Usa Ridisegna per sostituirla.','Ritaglia un’etichetta composta da testo e icona senza modificare o raggruppare gli oggetti originali.','Il margine è espresso in millimetri e viene limitato ai bordi della pagina. JPG forza lo sfondo bianco.'),
('json','🧰 Importare ed esportare JSON','JSON è il formato di lavoro autosufficiente: contiene pagine, oggetti, coordinate, font, asset, crop, impostazioni e, se richiesto, cronologia. Importa JSON apre una nuova scheda e conserva i progetti già presenti.','Premi Esporta JSON dalla barra o dal centro Export. Assegna un nome al file e archivialo. Per riprendere usa Importa JSON; verifica la nuova scheda prima di chiudere la precedente.','Consegna a un collega il JSON per permettergli di modificare testi e posizioni, oltre al PDF pronto da stampare.','Le immagini sono Data URL e possono rendere il file grande. Non modificare manualmente il JSON se non conosci la struttura.'),
('pwa','📲 Installare chicCanva come PWA','Su un vero dominio HTTPS compare Installa. Ogni build usa una cache identificata dal proprio contenuto e l’app mostra un avviso quando una versione nuova è pronta. Chrome, Edge e Android usano il prompt nativo; Safari su iPhone e iPad richiede Condividi → Aggiungi alla schermata Home. L’app installata ha icona Chicca e finestra dedicata.','Apri il dominio HTTPS, premi Installa e segui la finestra. Su iOS usa Safari e il menu Condividi. Dopo la prima apertura, verifica la presenza dell’icona tra le app.','Un insegnante può fissare chicCanva sul desktop dell’aula o sulla home del tablet e riaprirla senza cercare l’indirizzo.','La PWA è volutamente disattivata su file://, localhost, IP e reti private. La struttura dell’app è disponibile offline; Puter, font nuovi, emoji non ancora scaricate e modelli AI richiedono rete.'),
('mobile','📱 Uso su tablet e telefono','Il pulsante Installa diventa una sola icona per mantenere la barra su una riga. Sotto una certa larghezza la sidebar diventa un pannello sovrapposto, la toolbar scorre e i controlli grandi restano utilizzabili al tocco. Le frecce permettono di riordinare senza un drag preciso.','Ruota il dispositivo secondo il lavoro, usa Apri pannello per gli strumenti e chiudilo per vedere più canvas. Preferisci Fit dopo ogni cambio di orientamento.','Su tablet prepara rapidamente nomi e immagini; per regolazioni millimetriche o grandi progetti usa uno schermo più ampio.','Il browser mobile può sospendere schede pesanti. Lascia l’autosalvataggio attivo ed esporta il JSON al termine di una sessione importante.'),
('privacy','🔐 Dati, servizi, licenze e versione','Editor, trasformazioni B/N, outline algoritmico, sfondo uniforme ed export funzionano nel browser. Puter riceve prompt e riferimenti quando generi; IMG.LY scarica il modello ma elabora localmente. OpenMoji e font arrivano dai rispettivi CDN. Openclipart dichiara le opere pubblicate come pubblico dominio/CC0. In fondo alla sidebar trovi attribuzioni, versione dell’app e data della build.','Prima di usare una foto con persone, valuta le regole della scuola e il servizio selezionato. Per lavori locali preferisci strumenti non AI. Apri Librerie, contenuti e licenze per consultare attribuzioni e verificare quale build stai usando.','Una scheda con forme, testo e OpenMoji può essere creata ed esportata senza inviare il progetto completo a un backend chicCanva. La versione e la data aiutano a confrontare una copia locale con quella pubblicata online.','Il JSON contiene gli asset incorporati: trattalo come il materiale originale, soprattutto se include fotografie. Le risorse esterne conservano le proprie licenze; la licenza MIT del progetto copre soltanto il codice originale chicCanva.'),
('controllo','✅ Controllo finale prima della stampa','Una revisione breve evita pagine mancanti, testo fuori bordo e formati sbagliati. Preview mostra la sequenza; Fit controlla ogni pagina; l’export di prova verifica resa e dimensioni.','Rinomina le pagine, apri Preview, controlla orientamento e ordine. Visita le pagine critiche a Fit, verifica contorni, immagini e margini. Esporta prima una bozza a 96 o 150 dpi, poi il file finale.','Per un festone stampa una sola lettera di prova, misura il risultato e solo dopo esporta o stampa l’intero progetto.','Conserva JSON e output finale in due file distinti: uno serve a modificare, l’altro a stampare o condividere.')
]

WORKFLOWS = [
('Festone di benvenuto','Crea un progetto nuovo, apri Funzioni speciali e usa “BENVENUTI”. Scegli una lettera per pagina, A4 orizzontale e adattamento Altezza. Controlla apostrofi e Smart emoticon, genera, apri Preview e riordina se necessario. Esporta tutte le pagine in PDF a 150 o 300 dpi. Se preferisci stampare da immagini, scegli PNG: riceverai uno ZIP numerato.'),
('Titolo outline da colorare','Inserisci il testo come frase, scegli un font rotondo dal catalogo o dal wizard, mantieni Outline attivo, imposta nero e regola lo spessore. Usa Larghezza per un titolo orizzontale. Se vuoi colori diversi per lettera, usa Splitta, seleziona i caratteri a gruppi e applica i colori.'),
('Cartellone con foto e didascalie','Carica la foto dal dispositivo, usa Crop per definire l’inquadratura e blocca la rotazione quando hai finito. Inserisci un titolo outline e una didascalia piena con Disable Outline mode. Porta il titolo davanti, raggruppa gli elementi decorativi e salva una copia JSON prima dell’export PDF.'),
('Schede con una grafica comune','Prepara la prima pagina con cornice, titolo e posizione immagine. Duplicala più volte, rinomina ogni copia e sostituisci i contenuti. Usa Preview per confrontare la serie. Esporta tutte le pagine in PNG per ottenere uno ZIP oppure in PDF per un unico documento.'),
('Etichetta trasparente','Componi testo e OpenMoji, raggruppali per posizionarli. Premi lo strumento area export, disegna il rettangolo, usa margine ridotto e PNG trasparente. Esporta la selezione: il resto della pagina e il rettangolo guida non entrano nel file.'),
('Disegno da colorare senza AI','Carica un’illustrazione con colori piatti. Prova Duplica e rendi outline con sensibilità media; se il risultato è rumoroso, riduci la sensibilità o usa prima B/N verso Al tratto. Conserva sempre l’originale e confronta le copie a Fit.'),
('Disegno da colorare con AI','Seleziona l’immagine e premi Prepara disegno da colorare con AI. Controlla riferimento, modello GPT Image 2, qualità Low e prompt. Specifica età dei bambini e dettagli da conservare, poi premi Genera. Se vuoi anche la figura trasparente, configura rimozione sfondo e attiva la checkbox post elaborazione.'),
('Emoji coordinate con il testo','Scrivi una frase con emoji e lascia Smart emoticon attivo. Il risultato è un gruppo misto. Applica il font alle lettere, poi dividi il gruppo per ingrandire o recolorare l’OpenMoji outlined. Raggruppa nuovamente quando la composizione è pronta.'),
('Progetto misto verticale e orizzontale','Crea pagine con formati differenti e assegna nomi espliciti. Ruota soltanto quelle necessarie. Preview le mostrerà con proporzioni leggibili alla stessa scala del lato lungo; il PDF manterrà orientamento e dimensioni pagina per pagina.'),
('Lavoro condiviso con una collega','Esporta il JSON con storico se vuoi permettere annulla/ripristina anche dopo l’importazione. Invia anche un PDF di riferimento. La collega importa il JSON in una nuova scheda, verifica font e asset, apporta modifiche e riesporta senza sovrascrivere i progetti già aperti.'),
('Preparazione su tablet','Installa la PWA dal dominio HTTPS, lascia l’autosalvataggio attivo e usa la sidebar sovrapposta. Aggiungi testo e immagini, chiudi il pannello per lavorare sul foglio e usa le frecce per riordinare. Al termine esporta JSON e PDF, perché il sistema mobile può liberare memoria dopo periodi lunghi.'),
('Stampa economica in bianco e nero','Duplica le fotografie in B/N Soft, usa contorni neri per testi ed emoji outline e scegli sfondo bianco. Esporta una bozza PDF a 150 dpi e stampa una pagina campione. Se i dettagli sono sufficienti, mantieni questa risoluzione per contenere il peso del file.'),
('Flashcard quadrate','Crea una pagina Quadrata, aggiungi una parola e un’immagine, quindi duplica. Rinomina ogni pagina con il contenuto della carta. Usa griglia e snap per mantenere posizioni costanti. Esporta tutte le pagine PNG: lo ZIP usa ordine e nomi delle pagine.'),
('Recuperare un errore','Interrompi l’azione corrente con Esc quando possibile. Usa Annulla fino allo stato corretto e controlla il contatore. Se hai ricaricato la pagina, scegli Riprendi progetto. Se hai chiuso esplicitamente una scheda, importa il JSON esportato: l’autosalvataggio della scheda chiusa è stato rimosso.'),
('Confrontare due idee','Duplica il progetto esportando e reimportando il JSON oppure crea una nuova scheda e copia gli oggetti. Rinomina le varianti “A” e “B”, cambia font o colori in modo indipendente e usa Preview. Mantieni entrambe aperte finché non hai scelto, poi esporta la versione preferita.'),
('Trasformare una dispensa PDF in un progetto','Apri Immagini e scegli Importa PDF come immagini. Seleziona Tutte le pagine, Nuovo progetto, orientamento Auto e qualità 2×. Dopo la conversione usa Preview per controllare pagine verticali e orizzontali, aggiungi annotazioni o Clipart e conserva il JSON prima dell’export finale.')
]

FAQ = [
('Perché il pulsante Installa non compare?','Compare soltanto su un dominio reale in HTTPS e quando l’app non è già installata. È nascosto intenzionalmente su file, localhost, indirizzi IP e domini di rete privata.'),
('Perché un font appare diverso?','Il catalogo è incorporato, mentre il file tipografico si scarica al primo uso. Se rete o filtro lo bloccano, il browser usa un font sostitutivo. Prova un’altra rete o consenti Google Fonts/Fontsource.'),
('Perché un URL immagine non funziona?','Il link deve restituire direttamente un file immagine. Se il sito blocca CORS, riprova spuntando Usa Puter per scaricare l’immagine; questa rete è conteggiata secondo la quota user-pays dell’account. Puoi anche copiare l’immagine e usare Incolla immagine dagli appunti.'),
('Perché PNG e JPG producono uno ZIP?','Quando scegli tutte le pagine ci sono più file. Lo ZIP li raccoglie senza inviarli a un server e conserva ordine e nomi.'),
('Perché la qualità PNG è disattivata?','PNG è senza perdita e il browser ignora una qualità percentuale. Usa DPI per controllare la risoluzione; lo slider qualità è utile per JPG.'),
('Perché JPG non consente trasparenza?','Il formato JPG non possiede un canale alpha. chicCanva applica automaticamente uno sfondo bianco.'),
('La griglia verrà stampata?','No. Griglia, selezioni, maniglie e rettangolo di export sono guide dell’editor e vengono escluse.'),
('Lo zoom cambia la stampa?','No. Zoom e manina modificano soltanto la visualizzazione. Dimensioni pagina, oggetti e DPI decidono l’output.'),
('Perché Rotate è bloccato?','È una protezione contro rotazioni involontarie. Premi R quando serve e disattivalo dopo la regolazione.'),
('Dove sono finite le altre sezioni?','Con Espandi singolarmente attivo resta aperto solo il widget in uso. Premi Espandi sezioni per mostrarle tutte o disattiva la checkbox.'),
('Posso cambiare font a un testo con emoji?','Sì. Il comando attraversa il gruppo e cambia i componenti testuali. Dividi gruppo se vuoi selezionare un solo pezzo.'),
('La rimozione sfondo invia la foto?','IMG.LY/ONNX elabora nel browser; scarica il modello ma non la foto. Puter riceve immagini solo per le funzioni generative quando premi Genera.'),
('Perché il modello AI viene scaricato di nuovo?','La cache può essere stata cancellata dall’app, dal browser o dal sistema per recuperare spazio. Modelli diversi hanno file separati.'),
('Posso lavorare senza internet?','Editor, testi, asset già incorporati, trasformazioni locali ed export funzionano. Font o OpenMoji mai scaricati, Puter e download iniziale dei modelli richiedono rete.'),
('Cosa salva il JSON?','Salva lo stato modificabile e gli asset incorporati. Se abiliti la relativa opzione include anche la cronologia, aumentando il peso.'),
('Autosave sostituisce il JSON?','No. Protegge dai refresh nello stesso browser e indirizzo. Il JSON è la copia trasferibile e archiviabile.'),
('Come ottengo una sola immagine?','Scegli Pagina corrente oppure Selezione nella pagina. Tutte le pagine crea ZIP quando sono più di una.'),
('Come mantengo uguali più pagine?','Prepara una pagina modello e duplicala. Usa griglia, snap e nomi ordinati, poi sostituisci soltanto il contenuto variabile.'),
('Perché l’AI post elaborazione dura più della generazione?','Dopo Puter parte un secondo processo locale di segmentazione; può dover scaricare e caricare il modello scelto.'),
('Quale file devo conservare?','Conserva sempre il JSON per modifiche future e il PDF/PNG/JPG per stampa o condivisione. Sono scopi diversi.'),
('Il testo del PDF resta modificabile?','No. Ogni pagina PDF viene convertita in un’immagine PNG adattata a una pagina A4. Puoi aggiungere sopra nuovi testi e oggetti chicCanva, ma il contenuto originale resta rasterizzato.')
]

def section_html(item):
    sid,title,summary,steps,example,tips=item
    return f'''<section id="{sid}"><h3>{title}</h3><p>{summary}</p><h4>Come usarla</h4><p>{steps}</p><div class="guide-example"><strong>Esempio pratico</strong><p>{example}</p></div><h4>Da ricordare</h4><p>{tips}</p><ul><li>Controlla il risultato sul foglio o in Preview prima dell’esportazione.</li><li>Le operazioni che creano copie conservano l’originale per permettere confronti e ripensamenti.</li><li>Usa Annulla quando il risultato non corrisponde all’intenzione; usa il JSON per una copia esterna duratura.</li></ul></section>'''

toc=''.join(f'<a href="#{sid}">{title}</a>' for sid,title,*_ in SECTIONS)
body=''.join(section_html(item) for item in SECTIONS)
workflows=''.join(f'<article class="guide-example"><h4>{escape(title)}</h4><p>{text}</p><p><strong>Controllo finale:</strong> verifica ordine delle pagine, margini, qualità delle immagini e formato di export. Salva il JSON se vuoi riaprire e modificare il lavoro.</p></article>' for title,text in WORKFLOWS)
faq=''.join(f'<details><summary><strong>{escape(q)}</strong></summary><p>{a}</p></details>' for q,a in FAQ)
shortcuts='''<table><thead><tr><th>Scorciatoia</th><th>Azione</th><th>Quando usarla</th></tr></thead><tbody><tr><td><kbd>Ctrl C</kbd> / <kbd>Ctrl V</kbd></td><td>Copia / incolla</td><td>Anche fra pagine e progetti aperti</td></tr><tr><td><kbd>Ctrl D</kbd></td><td>Duplica</td><td>Crea una copia nella pagina attiva</td></tr><tr><td><kbd>Ctrl G</kbd> / <kbd>Ctrl Maiusc G</kbd></td><td>Raggruppa / dividi</td><td>Gestisce composizioni di più elementi</td></tr><tr><td><kbd>Ctrl Z</kbd> / <kbd>Ctrl Y</kbd></td><td>Annulla / ripristina</td><td>Naviga nello storico</td></tr><tr><td><kbd>Ctrl S</kbd></td><td>Esporta JSON</td><td>Salva il progetto modificabile</td></tr><tr><td><kbd>CANC</kbd></td><td>Elimina selezione</td><td>Equivale all’icona × cerchiata</td></tr><tr><td><kbd>F</kbd></td><td>Fit</td><td>Centra e adatta il foglio</td></tr><tr><td><kbd>H</kbd></td><td>Manina</td><td>Sposta la vista ingrandita</td></tr><tr><td><kbd>V</kbd></td><td>Selezione</td><td>Torna alla modifica oggetti</td></tr><tr><td><kbd>G</kbd></td><td>Griglia</td><td>Mostra o nasconde la guida</td></tr><tr><td><kbd>R</kbd></td><td>Rotazione</td><td>Sblocca o blocca la maniglia</td></tr><tr><td><kbd>F1</kbd></td><td>Guida</td><td>Apre questo manuale</td></tr><tr><td><kbd>Ctrl</kbd> + rotella</td><td>Zoom</td><td>Ingrandisce attorno al puntatore</td></tr><tr><td>Frecce / <kbd>Maiusc</kbd> + frecce</td><td>Sposta 1 / 10 pixel</td><td>Regolazioni precise</td></tr></tbody></table>'''

html=f'''<div class="guide-intro"><p><strong>chicCanva</strong> è il laboratorio di Chicca per cartelloni, scritte, schede, immagini e materiali da stampare. Questo manuale segue le attività dell’insegnante: prima organizza il progetto, poi compone, rifinisce, salva ed esporta.</p><p class="guide-callout">Puoi leggere tutto in ordine oppure usare l’indice. I nomi in grassetto corrispondono ai pulsanti e ai widget dell’app. Nessuna procedura richiede conoscenze tecniche.</p></div><div class="guide-shell"><details class="guide-toc" open><summary>Indice della guida</summary><nav>{toc}<a href="#percorsi">Percorsi guidati</a><a href="#scorciatoie">Scorciatoie</a><a href="#faq">Domande frequenti</a></nav></details><div class="guide-body">{body}<section id="percorsi"><h3>🗺️ Percorsi guidati</h3><p>Questi esempi combinano più widget in un ordine già collaudato. Adattali alla classe, alla stampante e al materiale di partenza.</p>{workflows}</section><section id="scorciatoie"><h3>⌨️ Scorciatoie complete</h3><p>Le scorciatoie funzionano quando non stai scrivendo in un campo. Su macOS puoi usare Cmd al posto di Ctrl per copia, incolla, salvataggio e cronologia.</p>{shortcuts}</section><section id="faq"><h3>❓ Domande frequenti</h3><p>Apri una domanda per leggere la risposta. Le indicazioni riguardano il comportamento normale dell’app e aiutano a scegliere il percorso più semplice.</p>{faq}</section></div></div>'''

target=Path(__file__).with_name('help-v7.html')
target.write_text(html,encoding='utf-8')
print(f'Guida generata: {len(html):,} caratteri, {len(SECTIONS)} sezioni, {len(WORKFLOWS)} percorsi, {len(FAQ)} FAQ')
