from pathlib import Path
import re,json,shutil
root=Path(__file__).resolve().parent.parent
s=(root/'OutlineLab_v5.html').read_text(encoding='utf-8')
def rep(a,b):
 global s
 assert a in s,a[:120]
 s=s.replace(a,b)
def fn(name,code):
 global s
 pattern=r'(?:async )?function '+name+r'\([^\n]*?(?=(?:async )?function |\n)'
 s,n=re.subn(pattern,lambda m:code+'\n',s,count=1)
 assert n,name
rep('OutlineLab v5','chicCanva')
rep('Apri OutlineLab tramite','Apri chicCanva tramite')
rep('Outline · multi-page · OpenMoji · immagini · crop · AI','Piccole idee, grandi scoperte · con Chicca')
rep('<script async src="https://js.puter.com/v2/"></script>','')
logo='''<svg viewBox="0 0 64 64" role="img" aria-label="Chicca, la piccola insegnante"><rect width="64" height="64" rx="19" fill="#e8f3ee"/><path d="M16 35V23C16 4 49 4 49 25v15" fill="#694739"/><circle cx="32" cy="27" r="16" fill="#ffd9b7"/><path d="M16 23c0-19 32-18 32 1-11-1-17-6-20-10-2 5-7 8-12 9" fill="#694739"/><g fill="none" stroke="#304f48" stroke-width="2"><rect x="20" y="25" width="10" height="8" rx="3"/><rect x="34" y="25" width="10" height="8" rx="3"/><path d="M30 28h4M28 37q4 4 8 0"/></g><path d="M13 59v-6c0-15 38-15 38 0v6" fill="#298879"/><path d="M20 46l12 3 12-3v13l-12 3-12-3z" fill="#fff5d4" stroke="#d6b765" stroke-width="1.5"/><path d="M32 49v12" stroke="#d6b765"/><path d="M49 44l5-14 3 1-5 14-3 3z" fill="#f2b84b"/></svg>'''
rep('<div class="mark">O</div>','<div class="mark chicca">'+logo+'</div>')
rep('<div class="actions">','<div class="actions"><button class="btn" id="helpBtn" title="Guida a chicCanva e scorciatoie (F1)">? Guida</button>')
rep('<textarea id="textInput" spellcheck="false">CIAO 👋</textarea>','<textarea id="textInput" spellcheck="false">CIAO 👋</textarea><label class="check"><input id="uppercaseText" type="checkbox"><span>Tutto MAIUSCOLO <small>· per i nuovi testi</small></span></label>')
rep('Font OUTLINED','Caratteri e stile')
rep('Catalogo Fontsource completo: tutti i font caricati ricevono un profilo wizard automatico.','2.100 famiglie nel catalogo incorporato. Filtra, cerca o lasciati guidare dal wizard.')
rep('<div class="seg" id="fontMode">','<label class="check"><input id="disableOutline" type="checkbox"><span><strong>Disable Outline mode</strong> · caratteri pieni</span></label><div class="help" id="outlineHelp">Contorni da colorare. Il colore si applica al bordo.</div><div class="seg" id="fontMode">')
rep('<div id="directFontPanel">','<div id="directFontPanel"><div id="fontCategories" class="font-categories" role="tablist" aria-label="Tipi di carattere"></div>')
rep('<div class="status" id="fontStatus">Catalogo locale iniziale · caricamento Fontsource…</div>','<div class="status" id="fontStatus">Catalogo incorporato…</div><div class="status" id="fontLoadStatus" role="status"></div>')
rep('Colore e spessore del contorno','<span id="colorModeLabel">Colore e spessore del contorno</span>')
rep('<label class="small">Stile illustrazione</label>', '''<label class="small">Immagine di riferimento · opzionale</label><div class="row"><button class="btn grow" id="attachAiReference">＋ Allega immagine</button><button class="btn" id="useCanvasReference" title="Usa l’immagine selezionata come riferimento AI">Dal canvas</button></div><input id="aiReferenceFile" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" hidden><div id="aiReferencePreview" class="reference-preview hidden"><img id="aiReferenceImg" alt="Immagine di riferimento"><div class="grow"><strong id="aiReferenceName"></strong><div class="help">Verrà inviata a Puter quando premi Genera.</div></div><button id="clearAiReference" class="iconbtn" title="Rimuovi riferimento">×</button></div><div id="aiReferenceStatus" class="status"></div><label class="small">Stile illustrazione</label>''')
rep('state.text=$(\'textInput\').value;', "state.text=$('textInput').value;state.uppercase=$('uppercaseText').checked;state.outline=!$('disableOutline').checked;")
rep("text:'CIAO 👋',assets:", "text:'CIAO 👋',outline:true,uppercase:false,fontCategory:'all',aiReference:null,assets:")
# Explicit per-object mode survives project imports and style changes.
rep("charSpacing:o.charSpacing,lineHeight", "outlineMode:o.outlineMode??(o.strokeWidth>0),charSpacing:o.charSpacing,lineHeight")
rep("o.objectType='text';o.projectId=d.id;", "o.objectType='text';o.outlineMode=d.outlineMode??(d.strokeWidth!==0);o.projectId=d.id;")
rep("stroke:d.stroke||state.strokeColor", "stroke:d.stroke??state.strokeColor")
fn('makeTextObj', "function makeTextObj(text,left,top,size=80){const o=new fabric.Text(text,{left,top,originX:'center',originY:'center',fontFamily:state.font,fontSize:size,fontWeight:400,...textPaint(),charSpacing:0,objectCaching:false});o.objectType='text';o.outlineMode=state.outline;o.projectId=uid('obj');o.setControlVisible('mtr',state.rotateEnabled);return o}")
fn('applyTextStyle', "function applyTextStyle(){syncStateFromUI();const objs=selectionObjects().filter(o=>o.objectType==='text');objs.forEach(o=>{o.set(textPaint());o.outlineMode=state.outline;o.setCoords()});canvas.requestRenderAll();saveActivePage();toast(objs.length?'Stile applicato alla selezione':'Stile impostato per i prossimi testi')}")
rep("$('strokeColor').value=objs[0].stroke||state.strokeColor;$('strokeWidth').value=objs[0].strokeWidth||state.strokeWidth", "state.outline=objs[0].outlineMode??(objs[0].strokeWidth>0);$('disableOutline').checked=!state.outline;$('strokeColor').value=state.outline?(objs[0].stroke||state.strokeColor):(objs[0].fill||state.strokeColor);$('strokeWidth').value=objs[0].strokeWidth||state.strokeWidth;syncOutlineUI()")
rep("state.text,state.mode==='whole'", "(state.uppercase?state.text.toLocaleUpperCase('it-IT'):state.text),state.mode==='whole'")
rep("groupGraphemes(graphemes(state.text))", "groupGraphemes(graphemes(state.uppercase?state.text.toLocaleUpperCase('it-IT'):state.text))")
rep("app:'OutlineLab',version:4", "app:'chicCanva',version:5")
rep("customCounter:state.customCounter},pages:", "customCounter:state.customCounter,outline:state.outline,uppercase:state.uppercase,fontCategory:state.fontCategory,aiReference:state.aiReference},pages:")
rep("customCounter:s.customCounter||1}", "customCounter:s.customCounter||1,outline:s.outline??true,uppercase:s.uppercase??false,fontCategory:s.fontCategory||'all',aiReference:s.aiReference||null}")
rep("function syncUiFromState(){$('textInput')", "function syncUiFromState(){$('disableOutline').checked=!state.outline;$('uppercaseText').checked=state.uppercase;syncOutlineUI();syncReferenceUI();$('textInput')")
rep("'OutlineLab_v5.pdf'", "'chicCanva.pdf'")
rep("'OutlineLab_project_v5.json'", "'chicCanva_progetto.json'")
rep("'OutlineLab_crop.png'", "'chicCanva_ritaglio.png'")
rep("if(location.protocol==='file:'||!window.puter?.ai?.listModels){toast('Lista dinamica non disponibile');return}", "if(location.protocol==='file:'){toast('Avvia il launcher per Puter');return}try{await ensurePuter()}catch(e){toast(e.message);return}if(!window.puter?.ai?.listModels){toast('Lista dinamica non disponibile');return}")
rep("populateAiModels();syncAiQualityOptions()};$('refreshAiModels')", "populateAiModels();syncAiQualityOptions();syncReferenceUI()};$('aiModel').onchange=syncReferenceUI;$('refreshAiModels')")
fn('generateAi', (root/'development/chic-ai.js').read_text(encoding='utf-8'))
fn('initFontCatalog', "function initFontCatalog(){state.fontCatalog=EMBEDDED_FONTS.map(autoProfile).sort((a,b)=>a.name.localeCompare(b.name,'it'));renderFontResults();updateWizard();$('fontStatus').textContent=state.fontCatalog.length.toLocaleString('it-IT')+' famiglie incorporate · nessuna richiesta all’API Fontsource.'}")
fn('renderFontResults', (root/'development/chic-fonts.js').read_text(encoding='utf-8'))
fn('loadFont', "async function loadFont(name){if(!name)return;if(!fontLinks.has(name)){fontLinks.set(name,(async()=>{const m=fontMeta(name),google='https://fonts.googleapis.com/css2?family='+encodeURIComponent(name).replace(/%20/g,'+')+'&display=swap',cdn=m.id?'https://cdn.jsdelivr.net/npm/@fontsource/'+encodeURIComponent(m.id)+'/400.css':null;for(const url of [google,cdn].filter(Boolean)){const link=document.createElement('link');link.rel='stylesheet';link.href=url;const ready=new Promise(resolve=>{link.onload=()=>resolve(true);link.onerror=()=>resolve(false);setTimeout(()=>resolve(false),5000)});document.head.append(link);if(await ready){try{const faces=await Promise.race([document.fonts.load('100px '+JSON.stringify(name)),new Promise(resolve=>setTimeout(()=>resolve([]),5000))]);if(faces.length){loadedFonts.add(name);return true}}catch(e){}}link.remove()}if(name===state.font)$('fontLoadStatus').textContent='Il font '+name+' non è scaricabile: verifica il filtro di rete. Il catalogo resta completo; viene usato il carattere di sistema.';fontLinks.delete(name);return false})())}return fontLinks.get(name)}")
rep('bindUpgrades();ensurePages();', 'bindUpgrades();bindChic();ensurePages();')
fn('autoProfile',(root/'development/chic-profiles.js').read_text(encoding='utf-8'))
rep('<span>Cicciottello</span>','<span>Cicciottello / colorabile</span>')
rep("best.profileSource==='manual'?'profilato':'automatico'", "best.profileSource==='curato'?'curato':'stimato da metadati'")
rep(' · peso ${Math.round(best.weight)}',' · colorabile ${Math.round(best.weight)}')
rep("emojiStyle:'black',text:","emojiStyle:'black',emojiInk:'#000000',text:")
rep('id="emojiSearch" placeholder=', 'id="emojiSearch" placeholder=')
rep('<input class="field" id="emojiSearch"', '<div class="row" id="emojiInkRow" style="margin-top:10px"><label class="grow" for="emojiInk" style="font-size:12px">Colore outlined</label><input type="color" id="emojiInk" value="#000000"><button class="btn" id="applyEmojiInk">Applica selezione</button></div><input class="field" id="emojiSearch"')
rep("key=`openmoji:${style}:${hex}`", "key=`openmoji:${style}:${hex}:${style==='black'?state.emojiInk:'original'}`")
rep("`openmoji:${state.emojiStyle}:${e.hexcode}`", "`openmoji:${state.emojiStyle}:${e.hexcode}:${state.emojiStyle==='black'?state.emojiInk:'original'}`")
rep('const dataUrl=await dataUrlFromBlob(blob);const id=uid(\'asset\');', "let dataUrl=await dataUrlFromBlob(blob);if(meta.kind==='emoji'&&meta.meta?.style==='black'){dataUrl=await recolorEmojiSvg(dataUrl,'#000000',state.emojiInk);meta.meta.ink=state.emojiInk}const id=uid('asset');")
rep("emojiStyle:state.emojiStyle,text:","emojiStyle:state.emojiStyle,emojiInk:state.emojiInk,text:")
rep("emojiStyle:s.emojiStyle||'black',text:","emojiStyle:s.emojiStyle||'black',emojiInk:s.emojiInk||'#000000',text:")
rep("function syncUiFromState(){$('disableOutline')", "function syncUiFromState(){$('emojiInk').value=state.emojiInk;$('emojiInkRow').classList.toggle('hidden',state.emojiStyle!=='black');$('disableOutline')")
rep("state.emojiStyle=b.dataset.emojistyle;", "state.emojiStyle=b.dataset.emojistyle;$('emojiInkRow').classList.toggle('hidden',state.emojiStyle!=='black');")
# Default font previews are loaded on intersection; prevent two concurrent loads and avoid request bursts.
catalog=json.loads((root/'development/font-catalog.json').read_text())
catalog=[{k:f[k] for k in ('id','family','weights','category','type') if k in f} for f in catalog]
rep('init().catch(e=>', 'const EMBEDDED_FONTS='+json.dumps(catalog,ensure_ascii=False,separators=(',',':'))+';\n'+(root/'development/chic-emoji.js').read_text(encoding='utf-8')+'\n'+(root/'development/chic-ui.js').read_text(encoding='utf-8')+'\ninit().catch(e=>')
rep('\n</style>', '\n'+(root/'development/chic-style.css').read_text(encoding='utf-8')+'\n</style>')
rep('<div class="toast" id="toast"', (root/'development/chic-help.html').read_text(encoding='utf-8')+'\n<div class="toast" id="toast"')
out=root/'chicCanva.html';out.write_text(s,encoding='utf-8')
bat=(root/'OutlineLab_v5_server.bat').read_text().replace('OutlineLab_v5.html','chicCanva.html').replace('OutlineLab v5','chicCanva').replace('OutlineLab:','chicCanva:')
(root/'chicCanva_server.bat').write_text(bat,encoding='utf-8',newline='\r\n')
build=root/'build/chicCanva';build.mkdir(parents=True,exist_ok=True)
for f in ['chicCanva.html','chicCanva_server.bat']:shutil.copy2(root/f,build/f)
(root/'development/chic-check.js').write_text(re.findall(r'<script>([\s\S]*?)</script>',s)[-1],encoding='utf-8')
print('chicCanva built:',len(catalog),'fonts;',out.stat().st_size,'bytes')
