let fontPageLimit=60,puterReady=null,tooltipTimer=null,lastHelpFocus=null;
const FONT_CATEGORIES=[['all','Tutti'],['child','Cicciottelli'],['round','Rotondi'],['square','Squadrati'],['art','Artistici'],['serif','Serif'],['sans','Sans serif'],['hand','Scrittura'],['mono','Monospazio'],['outline','Outline nativi']];
function matchesFontCategory(f,category){switch(category){case 'child':return f.weight>=72&&f.shape>=55;case 'round':return f.shape>=72;case 'square':return f.shape<=28;case 'art':return f.art>=70;case 'serif':return f.category==='serif';case 'sans':return f.category==='sans-serif';case 'hand':return f.category==='handwriting';case 'mono':return f.category==='monospace';case 'outline':return !!f.native;default:return true}}
function fontKeywords(f){const tags=[f.name,f.category];for(const [id,label] of FONT_CATEGORIES)if(id!=='all'&&matchesFontCategory(f,id))tags.push(label);if(matchesFontCategory(f,'child'))tags.push('cicciottello cicciottelli bambini bambino colorabile colorabili gonfio bubble kids');if(matchesFontCategory(f,'round'))tags.push('rotondo tondo rotondeggiante rotondeggianti morbido rounded');if(matchesFontCategory(f,'square'))tags.push('squadrato geometrico pixel square');if(matchesFontCategory(f,'art'))tags.push('artistico decorativo creativo artistic');if(matchesFontCategory(f,'hand'))tags.push('manoscritto mano calligrafico');return tags.join(' ').toLocaleLowerCase('it-IT')}
function renderFontCategories(){const panel=$('fontCategories');panel.replaceChildren();FONT_CATEGORIES.forEach(([id,label])=>{const b=document.createElement('button');b.className='font-category'+(state.fontCategory===id?' active':'');b.role='tab';b.setAttribute('aria-selected',String(state.fontCategory===id));b.textContent=label;b.title=state.fontCatalog.filter(f=>matchesFontCategory(f,id)).length+' famiglie';b.onclick=()=>{state.fontCategory=id;fontPageLimit=60;renderFontResults()};panel.append(b)})}
function textPaint(){return{fill:state.outline?'rgba(255,255,255,0)':state.strokeColor,stroke:state.outline?state.strokeColor:null,strokeWidth:state.outline?state.strokeWidth:0,paintFirst:'stroke'}}
function syncOutlineUI(){$('colorModeLabel').textContent=state.outline?'Colore e spessore del contorno':'Colore del testo';$('strokeWidth').disabled=!state.outline;$('outlineHelp').textContent=state.outline?'Contorni da colorare. Il colore si applica al bordo.':'Testo pieno. I font nativamente outline restano vuoti per disegno: scegli un font standard per riempirlo.';}
async function ensurePuter(){if(window.puter?.ai?.txt2img)return;if(!puterReady)puterReady=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://js.puter.com/v2/';script.async=true;let done=false;const finish=e=>{if(done)return;done=true;clearTimeout(timer);if(e){puterReady=null;script.remove();reject(e)}else resolve()};const timer=setTimeout(()=>finish(new Error('Puter non raggiungibile. Controlla la connessione o il filtro del browser.')),15000);script.onload=()=>window.puter?.ai?finish():finish(new Error('SDK Puter non disponibile'));script.onerror=()=>finish(new Error('Caricamento Puter bloccato dal browser o dalla rete'));document.head.append(script)});return puterReady}
function referenceSupported(){return ['openai-image-generation','gemini','xai'].includes($('aiProvider').value)}
function syncReferenceUI(){const ref=state.aiReference;$('aiReferencePreview').classList.toggle('hidden',!ref);if(ref){$('aiReferenceImg').src=ref.dataUrl;$('aiReferenceName').textContent=ref.name}else $('aiReferenceImg').removeAttribute('src');$('aiReferenceStatus').textContent=ref&&!referenceSupported()?'Per usare il riferimento seleziona OpenAI Image, Gemini o xAI. Puoi anche rimuoverlo per usare questo modello.':ref?'Riferimento pronto · descrivi nel prompt cosa mantenere o cambiare.':'Allega una foto o un disegno; senza allegato la generazione funziona come prima.';if(!$('generateAiBtn').querySelector('.spinner'))$('generateAiBtn').disabled=!!ref&&!referenceSupported()}
async function setAiReference(file){if(!file)return;if(file.size>12*1024*1024){toast('Il riferimento deve essere inferiore a 12 MB');return}try{const raw=await fileToDataUrl(file),im=new Image();im.src=raw;await im.decode();const scale=Math.min(1,2048/Math.max(im.naturalWidth,im.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(im.naturalWidth*scale);c.height=Math.round(im.naturalHeight*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);state.aiReference={dataUrl:c.toDataURL('image/png'),mime:'image/png',name:file.name||'Riferimento dal canvas',width:c.width,height:c.height};syncReferenceUI()}catch(e){toast('Immagine di riferimento non leggibile')}}
async function duplicateSelection(){if(loadingPage||cropSession)return;const selected=selectionObjects().filter(o=>!o.excludeProject);if(!selected.length)return;canvas.discardActiveObject();const page=currentPage,descriptors=selected.map(o=>({...serializeObject(o),id:uid('obj'),left:o.left+20,top:o.top+20})),copies=[];for(const d of descriptors){if(currentPage!==page){page.objects.push(d);continue}copies.push(await instantiateObject(d))}if(currentPage===page){canvas.setActiveObject(copies.length===1?copies[0]:new fabric.ActiveSelection(copies,{canvas}));canvas.requestRenderAll();saveActivePage()}toast('Selezione duplicata')}
function fitSelection(){const selected=selectionObjects().filter(o=>!o.excludeProject);if(!selected.length)return;canvas.discardActiveObject();fitObjectList(selected,canvas.width,canvas.height);canvas.requestRenderAll();saveActivePage()}
function openHelp(){lastHelpFocus=document.activeElement;$('helpLayer').classList.remove('hidden');document.querySelector('.app').inert=true;$('closeHelp').focus()}
function closeHelp(){$('helpLayer').classList.add('hidden');document.querySelector('.app').inert=false;lastHelpFocus?.focus()}
function hideContext(){$('objectMenu').classList.add('hidden')}
function bindChic(){
 $('emojiInk').oninput=()=>{state.emojiInk=$('emojiInk').value};$('applyEmojiInk').onclick=applyEmojiInk;

 if(location.protocol!=='file:'){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();ensurePuter().catch(e=>{$('aiStatus').textContent=e.message})}},{root:$('sidebar'),rootMargin:'120px'});observer.observe($('aiCard'))}
 $('fontSearch').placeholder='Cerca font o stile: rotondo, bambino, serif…';$('fontSearch').oninput=e=>{state.fontSearch=e.target.value;fontPageLimit=60;renderFontResults()};
 $('disableOutline').onchange=()=>{state.outline=!$('disableOutline').checked;syncOutlineUI();applyTextStyle();renderFontResults()};$('uppercaseText').onchange=()=>state.uppercase=$('uppercaseText').checked;
 $('attachAiReference').onclick=()=>$('aiReferenceFile').click();$('aiReferenceFile').onchange=async e=>{await setAiReference(e.target.files?.[0]);e.target.value=''};$('clearAiReference').onclick=()=>{state.aiReference=null;syncReferenceUI()};$('useCanvasReference').onclick=async()=>{const image=selectedImage();if(!image){toast('Seleziona un’immagine nel canvas');return}const blob=await(await fetch(image.toDataURL({format:'png'}))).blob();await setAiReference(new File([blob],'Riferimento dal canvas.png',{type:'image/png'}))};
 $('helpBtn').onclick=openHelp;$('closeHelp').onclick=closeHelp;$('helpLayer').onclick=e=>{if(e.target===$('helpLayer'))closeHelp()};
 const jumps=document.createElement('nav');jumps.className='quick-jump';jumps.setAttribute('aria-label','Sezioni strumenti');[['Testo','textInput'],['Font','fontMode'],['Emoji','emojiSearch'],['Immagini','uploadImageBtn'],['AI','aiCard'],['Export','pdfMode']].forEach(([label,id])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>$(id).closest('.card').scrollIntoView({behavior:'smooth',block:'start'});jumps.append(b)});$('sidebar').prepend(jumps);
 const menuActions={duplicate:duplicateSelection,delete:()=>$('deleteTool').click(),front:()=>$('bringFrontTool').click(),back:()=>$('sendBackTool').click(),fit:fitSelection,crop:startCrop,background:removeBackgroundSelected,reference:()=>$('useCanvasReference').click()};document.querySelectorAll('#objectMenu button').forEach(b=>b.onclick=()=>{hideContext();menuActions[b.dataset.action]?.()});canvas.upperCanvasEl.addEventListener('contextmenu',e=>{e.preventDefault();if(loadingPage||cropSession)return;const target=canvas.findTarget(e,true);if(target&&!target.excludeProject&&!selectionObjects().includes(target))canvas.setActiveObject(target);if(!target&&!selectionObjects().length)return;canvas.requestRenderAll();const image=!!selectedImage();document.querySelectorAll('#objectMenu [data-image]').forEach(b=>b.disabled=!image);const menu=$('objectMenu');menu.classList.remove('hidden');menu.style.left=Math.max(8,Math.min(e.clientX,innerWidth-220))+'px';menu.style.top=Math.max(8,Math.min(e.clientY,innerHeight-menu.offsetHeight-8))+'px'});document.addEventListener('pointerdown',e=>{if(!e.target.closest('#objectMenu'))hideContext()});$('stageWrap').addEventListener('scroll',hideContext);
 window.addEventListener('keydown',e=>{const editable=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable;if(e.key==='F1'){e.preventDefault();openHelp();return}if(!$('helpLayer').classList.contains('hidden')){if(e.key==='Escape'){e.preventDefault();closeHelp()}if(e.key==='Tab'){const nodes=[...$('helpLayer').querySelectorAll('button,a[href],input')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}return}if(editable)return;const key=e.key.toLowerCase(),ctrl=e.ctrlKey||e.metaKey;let handled=true;if(ctrl&&key==='d')duplicateSelection();else if(ctrl&&key==='s')exportJson();else if(ctrl&&key==='a'&&!cropSession){const objects=canvas.getObjects().filter(o=>!o.excludeProject);if(objects.length)canvas.setActiveObject(new fabric.ActiveSelection(objects,{canvas}));canvas.requestRenderAll()}else if(key==='f'&&!ctrl)setZoom('fit');else if(key==='v'&&!ctrl){setPan(false);state.selectionMode=true;canvas.selection=true;$('selectTool').classList.add('active')}else if(key==='h'&&!ctrl)setPan(!panMode);else if(key==='g'&&!ctrl)$('gridTool').click();else if(key==='r'&&!ctrl)$('rotateTool').click();else if(e.key==='Escape'){if(!$('objectMenu').classList.contains('hidden'))hideContext();else handled=false}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&canvas.getActiveObject()&&!cropSession){const a=canvas.getActiveObject(),step=e.shiftKey?10:1;a.set({left:a.left+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),top:a.top+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)});a.setCoords();canvas.requestRenderAll();saveActivePage()}else handled=false;if(handled){e.preventDefault();e.stopImmediatePropagation()}},true);
 const tips={selectTool:'Seleziona oggetti. Ctrl + clic aggiunge alla selezione; trascina sul vuoto per selezionare un’area. Tasto V.',panTool:'Manina: trascina la vista quando sei ingrandito. Tasto H.',rotateTool:'Sblocca la maniglia di rotazione. Tasto R.',gridTool:'Mostra la griglia senza stamparla. Tasto G.',snapTool:'Aggancia lo spostamento alla spaziatura Snap, indipendente dalla griglia.',cropTool:'Crop non distruttivo: ritaglia l’immagine selezionata conservando l’originale.',exportRegionTool:'Disegna un’area da esportare in PNG, con margine e trasparenza.',fitTextBtn:'Adatta tutti gli oggetti secondo la modalità scelta sotto. Dal menu destro puoi adattare solo la selezione.',buildTextBtn:'Aggiunge il testo senza cancellare gli oggetti esistenti. In modalità singola aggiunge nuove pagine.',previewBtn:'Mostra tutte le pagine della modalità corrente. Clicca una miniatura per modificarla.',applySingleScale:'Conferma la scala attuale di tutte le pagine singole come nuova base 100%.',deleteTool:'Elimina gli oggetti selezionati. Anche CANC.',bringFrontTool:'Porta la selezione sopra gli altri oggetti.',sendBackTool:'Porta la selezione sotto gli altri oggetti.',zoomSelect:'Zoom della vista: Fit ricentra l’intera pagina. Non modifica le dimensioni di stampa.',addCustomPage:'Aggiunge una pagina custom vuota, con formato indipendente.'};Object.entries(tips).forEach(([id,tip])=>{if($(id))$(id).title=tip});document.querySelectorAll('button[title],select[title]').forEach(el=>{el.dataset.tip=el.title;if(!el.getAttribute('aria-label'))el.setAttribute('aria-label',el.title);el.removeAttribute('title')});const hideTip=()=>{clearTimeout(tooltipTimer);$('desktopTooltip').classList.add('hidden')};document.addEventListener('pointerover',e=>{if(!matchMedia('(hover:hover) and (pointer:fine)').matches)return;const el=e.target.closest('[data-tip]');if(!el)return;clearTimeout(tooltipTimer);tooltipTimer=setTimeout(()=>{const box=el.getBoundingClientRect(),tip=$('desktopTooltip');tip.textContent=el.dataset.tip;tip.classList.remove('hidden');tip.style.left=clamp(box.left,8,innerWidth-tip.offsetWidth-8)+'px';tip.style.top=(box.bottom+tip.offsetHeight+12>innerHeight?box.top-tip.offsetHeight-8:box.bottom+8)+'px'},450)});document.addEventListener('pointerout',hideTip);document.addEventListener('pointerdown',hideTip);
}
