const CLIPART_SEARCH='https://openclipart.org/search/';
const CLIPART_IT_EN={'albero':'tree','alfabeto':'alphabet','alunno':'student','alunna':'student','alunni':'students','amicizia':'friendship','amico':'friend','amici':'friends','amore':'love','animale':'animal','animali':'animals','ape':'bee','arcobaleno':'rainbow','astuccio':'pencil case','autobus':'bus','automobile':'car','bambina':'girl','bambine':'girls','bambini':'children','bambino':'child','biblioteca':'library','bicicletta':'bicycle','bruco':'caterpillar','cane':'dog','casa':'house','castello':'castle','cavallo':'horse','cerchio':'circle','cibo':'food','classe':'classroom','colorare':'coloring','colori':'colors','coniglio':'rabbit','cuore':'heart','dinosauro':'dinosaur','emozione':'emotion','emozioni':'emotions','famiglia':'family','farfalla':'butterfly','felice':'happy','fiore':'flower','fiori':'flowers','foglia':'leaf','foglie':'leaves','frutta':'fruit','gatto':'cat','gioco':'toy','giochi':'toys','globo':'globe','gomma':'eraser','insegnante':'teacher','libro':'book','libri':'books','luna':'moon','maestra':'teacher','maestro':'teacher','mano':'hand','mare':'sea','matita':'pencil','matite':'pencils','meteo':'weather','montagna':'mountain','musica':'music','natale':'christmas','natura':'nature','neve':'snow','nuvola':'cloud','numeri':'numbers','numero':'number','occhio':'eye','palloncino':'balloon','pasqua':'easter','penna':'pen','pianta':'plant','pioggia':'rain','quaderno':'notebook','quadrato':'square','rana':'frog','regalo':'gift','righello':'ruler','robot':'robot','scienze':'science','scuola':'school','sole':'sun','sport':'sports','stella':'star','stelle':'stars','treno':'train','triangolo':'triangle','uccello':'bird','verdura':'vegetables','viso':'face'};
let clipartPage=1,clipartLastQuery='',clipartItems=[],clipartCurrent=null,puterUsageTimer=null,clipartTranslationNote='',clipartSearchTransport='',clipartSearchSerial=0;
function clipartUrls(id,slug='clipart'){return{thumbnail:'https://openclipart.org/image/400px/'+id,large:'https://openclipart.org/image/800px/'+id,download:'https://openclipart.org/download/'+id,detail:'https://openclipart.org/detail/'+id+'/'+slug}}
function normalizeClipartTitle(value,slug){const text=String(value||'').replace(/\s+/g,' ').trim();return text||String(slug||'clipart').replace(/-/g,' ')}
function parseOpenclipartResults(html){const doc=new DOMParser().parseFromString(html,'text/html'),seen=new Set(),items=[];for(const link of doc.querySelectorAll('a[href*="/detail/"]')){const href=link.getAttribute('href')||'',match=href.match(/\/detail\/(\d+)(?:\/([^?#"']+))?/);if(!match||seen.has(match[1]))continue;seen.add(match[1]);const id=match[1],slug=(match[2]||'clipart').replace(/\/$/,'');let title=normalizeClipartTitle(link.getAttribute('title')||link.querySelector('img')?.alt||link.textContent,slug);if(/^download$/i.test(title))title=normalizeClipartTitle('',slug);items.push({id,slug,title,...clipartUrls(id,slug)})}return items}
function clipartTimed(promise,ms){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Tempo di attesa superato')),ms)})]).finally(()=>clearTimeout(timer))}
function translateClipartLocally(keyword){let changed=false;const translated=String(keyword).split(/(\s+|[-,;]+)/).map(part=>{const key=part.toLocaleLowerCase('it-IT').normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(CLIPART_IT_EN[key]){changed=true;return CLIPART_IT_EN[key]}return part}).join('').replace(/\s+/g,' ').trim();return{translated,changed}}
async function translateClipartKeyword(keyword){clipartTranslationNote='';if(!$('clipartTranslate').checked||!keyword)return keyword;try{const url='https://api.mymemory.translated.net/get?q='+encodeURIComponent(keyword.slice(0,100))+'&langpair=it%7Cen',response=await clipartTimed(fetch(url),7000);if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json(),translated=String(data?.responseData?.translatedText||'').trim();if(translated&&translated.toUpperCase()!=='QUERY LENGTH LIMIT EXCEEDED'){clipartTranslationNote=translated.toLocaleLowerCase()!==keyword.toLocaleLowerCase()?'Tradotto online in “'+translated+'”':'Il servizio online ha mantenuto la parola originale';return translated}throw new Error('Traduzione vuota')}catch(error){const local=translateClipartLocally(keyword);clipartTranslationNote=local.changed?'Servizio online non disponibile · traduzione locale: “'+local.translated+'”':'Traduzione non disponibile · usato il termine originale';return local.translated}}
async function translateEmojiKeyword(keyword){try{const url='https://api.mymemory.translated.net/get?q='+encodeURIComponent(keyword.slice(0,100))+'&langpair=it%7Cen',response=await clipartTimed(fetch(url),7000);if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json(),translated=String(data?.responseData?.translatedText||'').trim();if(translated&&translated.toUpperCase()!=='QUERY LENGTH LIMIT EXCEEDED')return{translated,note:translated.toLocaleLowerCase()!==keyword.toLocaleLowerCase()?'tradotto in “'+translated+'”':'termine originale'};throw new Error('Traduzione vuota')}catch(error){const local=translateClipartLocally(keyword);return{translated:local.translated,note:local.changed?'traduzione locale: “'+local.translated+'”':'termine originale'}}}
function isLocalChicServer(){return location.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(location.hostname)}
async function fetchOpenclipartSearch(query,page){clipartSearchTransport='browser';const remote=CLIPART_SEARCH+'?p='+page+'&query='+encodeURIComponent(query);try{const response=await clipartTimed(fetch(remote,{headers:{Accept:'text/html'}}),15000);if(!response.ok)throw new Error('Openclipart risponde HTTP '+response.status);return await response.text()}catch(directError){if(!isLocalChicServer())throw directError;clipartSearchTransport='webserver locale';const local='/__chiccanva_openclipart_search?p='+page+'&query='+encodeURIComponent(query),response=await clipartTimed(fetch(local,{credentials:'same-origin'}),20000);if(!response.ok)throw new Error((await response.text()).trim()||'Openclipart risponde HTTP '+response.status);return await response.text()}}
function renderClipartResults(){const grid=$('clipartResults');grid.replaceChildren();for(const item of clipartItems){const card=document.createElement('article');card.className='clipart-item';card.dataset.id=item.id;const preview=document.createElement('button');preview.className='clipart-thumb';preview.type='button';preview.title='Apri anteprima di '+item.title;const image=document.createElement('img');preview.classList.add('loading');image.alt=item.title;image.loading='lazy';image.onload=()=>preview.classList.remove('loading');image.onerror=()=>{preview.classList.remove('loading');preview.classList.add('load-error')};image.src=item.thumbnail;if(image.complete)queueMicrotask(()=>image.naturalWidth?image.onload():image.onerror());preview.append(image);const title=document.createElement('strong');title.textContent=item.title;title.title=item.title;const actions=document.createElement('div');actions.className='clipart-item-actions';const open=document.createElement('button');open.className='btn';open.type='button';open.textContent='Anteprima';open.dataset.clipartAction='preview';open.dataset.id=item.id;actions.append(open);if($('clipartUsePuter').checked){const insert=document.createElement('button');insert.className='btn accent';insert.type='button';insert.textContent='Inserisci';insert.dataset.clipartAction='insert';insert.dataset.id=item.id;actions.append(insert)}preview.dataset.clipartAction='preview';preview.dataset.id=item.id;card.append(preview,title,actions);grid.append(card)}$('clipartPages').classList.toggle('hidden',!clipartItems.length);$('clipartPageLabel').textContent='Pagina '+clipartPage;$('clipartPrev').disabled=clipartPage<=1;$('clipartNext').disabled=!clipartItems.length}
async function searchClipart(page=1){
 const serial=++clipartSearchSerial,button=$('clipartSearchBtn');let keyword=$('clipartQuery').value.trim(),category=$('clipartCategory').value;
 if(!keyword&&!category){$('clipartStatus').textContent='Scrivi una parola o scegli una categoria.';return}
 button.disabled=true;button.setAttribute('aria-busy','true');button.innerHTML='<span class="spinner"></span> Ricerca…';$('clipartResults').setAttribute('aria-busy','true');$('clipartResults').innerHTML='<div class="clipart-loading"><span class="spinner"></span> Traduco e cerco le clipart…</div>';$('clipartPages').classList.add('hidden');$('clipartStatus').textContent='Preparazione della ricerca…';
 try{keyword=await translateClipartKeyword(keyword);if(serial!==clipartSearchSerial)return;const query=[keyword,category].filter(Boolean).join(' ').trim();clipartPage=Math.max(1,page);clipartLastQuery=query;$('clipartStatus').textContent=(clipartTranslationNote?clipartTranslationNote+' · ':'')+'Ricerca di “'+query+'”…';clipartItems=parseOpenclipartResults(await fetchOpenclipartSearch(query,clipartPage));if(serial!==clipartSearchSerial)return;renderClipartResults();const via=clipartSearchTransport==='webserver locale'?' · tramite webserver locale':'';const result=clipartItems.length?clipartItems.length+' risultati mostrati · '+query+via:'Nessun risultato in questa pagina.';$('clipartStatus').textContent=(clipartTranslationNote?clipartTranslationNote+' · ':'')+result}
 catch(error){if(serial!==clipartSearchSerial)return;clipartItems=[];renderClipartResults();$('clipartStatus').textContent='Ricerca non riuscita: '+(error.message||error)+'. Se un’estensione blocca Openclipart, usa il launcher aggiornato.'}
 finally{if(serial===clipartSearchSerial){button.disabled=false;button.removeAttribute('aria-busy');button.textContent='Cerca';$('clipartResults').removeAttribute('aria-busy')}}
}
function clipartById(id){return clipartItems.find(item=>item.id===String(id))}
function openClipartPreview(item){if(!item)return;clipartCurrent=item;$('clipartPreviewTitle').textContent=item.title;$('clipartPreviewMeta').textContent='Openclipart #'+item.id;$('clipartPreviewImage').src=item.large;$('clipartPreviewImage').alt=item.title;$('clipartPreviewStatus').textContent='';const unavailable=location.protocol==='file:';$('clipartInsertPuterBtn').disabled=unavailable;$('clipartInsertPuterBtn').title=unavailable?'Per usare la funzione apri l’app tramite webserver':'';$('clipartPreviewDialog').showModal()}
async function saveClipart(item){if(!item)return;const status=$('clipartPreviewStatus');status.textContent='Preparazione del download…';try{let response;try{response=await clipartTimed(fetch(item.download),15000);if(!response.ok)throw new Error('HTTP '+response.status)}catch(error){if(isLocalChicServer()){response=await clipartTimed(fetch('/__chiccanva_image_proxy?url='+encodeURIComponent(item.download),{credentials:'same-origin'}),20000);if(!response.ok)throw new Error((await response.text()).trim()||'Download non disponibile')}else if($('clipartUsePuter').checked){const file=await fetchClipartFile(item);download(cleanExportName(item.title,'clipart')+'.png',file);status.textContent='Download avviato.';return}else throw error}const blob=await response.blob(),type=blob.type||response.headers.get('content-type')||'',extension=type.includes('svg')?'svg':type.includes('jpeg')?'jpg':'png';download(cleanExportName(item.title,'clipart')+'.'+extension,blob);status.textContent='Download avviato.'}catch(error){status.textContent='Download automatico bloccato dal sito o dal browser. Attiva Puter oppure usa “Apri immagine grande”.'}}
async function fetchClipartFile(item){const checkbox=$('imageUrlUsePuter'),previous=checkbox.checked;checkbox.checked=true;try{return await fetchImageFile(item.large)}finally{checkbox.checked=previous}}
async function insertClipart(item){if(!item)return;if(location.protocol==='file:'){toast('Per usare la funzione apri l’app tramite webserver');return}const status=$('clipartPreviewDialog').open?$('clipartPreviewStatus'):$('clipartStatus');status.textContent='Download tramite Puter…';try{const file=await fetchClipartFile(item);const named=new File([file],cleanExportName(item.title,'clipart')+'.'+((file.type||'image/png').split('/')[1]||'png'),{type:file.type||'image/png'});await handleImageUpload(named);status.textContent='Clipart inserita nel canvas.';$('clipartPreviewDialog').close();toast('Clipart inserita');schedulePuterUsageRefresh()}catch(error){status.textContent='Inserimento non riuscito: '+(error.message||error)}}
function formatPuterMoney(microcents){if(!Number.isFinite(Number(microcents)))return'—';const dollars=Number(microcents)/100000000;return new Intl.NumberFormat('it-IT',{style:'currency',currency:'USD',minimumFractionDigits:dollars<0.01?4:2,maximumFractionDigits:dollars<0.01?4:2}).format(dollars)}
async function refreshPuterUsage(silent=false){const box=$('puterUsage');if(!box||location.protocol==='file:'){box?.classList.add('hidden');return}try{await ensurePuter();if(!window.puter?.auth?.isSignedIn||!await Promise.resolve(puter.auth.isSignedIn())){box.classList.add('hidden');return}if(!puter.auth.getMonthlyUsage)throw new Error('Consumo non disponibile in questa versione di Puter');const usage=await puter.auth.getMonthlyUsage(),info=usage?.allowanceInfo||{},total=Number(info.monthUsageAllowance),remaining=Number(info.remaining),used=Math.max(0,total-remaining),percent=total>0?clamp(used/total*100,0,100):0,callCount=Object.values(usage?.appTotals||{}).reduce((sum,item)=>sum+Number(item?.count||0),0);box.classList.remove('hidden');$('puterUsageBar').style.width=percent+'%';const progress=box.querySelector('[role="progressbar"]');progress.setAttribute('aria-valuenow',String(Math.round(percent)));$('puterUsageUsed').textContent='Usato '+Math.round(percent)+'% · '+formatPuterMoney(used);$('puterUsageRemaining').textContent='Disponibile '+Math.round(100-percent)+'% · '+formatPuterMoney(remaining);$('puterUsageDetail').textContent='Credito mensile '+formatPuterMoney(total)+(callCount?' · '+callCount+' chiamate dell’app':'')+'. Valori forniti da Puter.'}catch(error){if(!silent){box.classList.remove('hidden');$('puterUsageDetail').textContent='Aggiornamento non riuscito: '+(error.message||error)}}}
function schedulePuterUsageRefresh(){clearTimeout(puterUsageTimer);puterUsageTimer=setTimeout(()=>refreshPuterUsage(true),1200)}
const clipartBaseGenerateAi=generateAi;generateAi=async function(){try{return await clipartBaseGenerateAi()}finally{schedulePuterUsageRefresh()}};
function bindClipart(){const card=$('clipartCard'),ai=$('aiCard');ai.parentNode.insertBefore(card,ai);$('clipartSearchBtn').onclick=()=>searchClipart(1);$('clipartQuery').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();searchClipart(1)}};$('clipartCategory').onchange=()=>{if($('clipartCategory').value)searchClipart(1)};$('clipartUsePuter').onchange=renderClipartResults;$('clipartResults').onclick=event=>{const action=event.target.closest('[data-clipart-action]');if(!action)return;const item=clipartById(action.dataset.id);if(action.dataset.clipartAction==='insert')insertClipart(item);else openClipartPreview(item)};$('clipartPrev').onclick=()=>searchClipart(clipartPage-1);$('clipartNext').onclick=()=>searchClipart(clipartPage+1);$('clipartPreviewClose').onclick=()=>$('clipartPreviewDialog').close();$('clipartDownloadBtn').onclick=()=>saveClipart(clipartCurrent);$('clipartOpenBtn').onclick=()=>{if(clipartCurrent)window.open(clipartCurrent.large,'_blank','noopener')};$('clipartInsertPuterBtn').onclick=()=>insertClipart(clipartCurrent);$('puterUsageRefresh').onclick=()=>refreshPuterUsage(false);if(location.protocol==='file:'){$('clipartUsePuter').disabled=true;$('clipartUsePuter').closest('label').title='Per usare la funzione apri l’app tramite webserver'}else{const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){observer.disconnect();refreshPuterUsage(true)}},{root:$('sidebar'),rootMargin:'100px'});observer.observe($('aiCard'))}}
const clipartBaseInit=init;init=async function(){await clipartBaseInit();bindClipart()};
