// MEGA Cloud Storage connector, in-app explorer, backups and best-effort single-writer sync.
const CLOUD_ROOT_NAME='chicCanva Cloud',CLOUD_BACKUP_NAME='.backups',CLOUD_SYNC_NAME='.synch',CLOUD_SECRET_DB='chicCanva-cloud-secrets',CLOUD_SECRET_STORE='secrets',CLOUD_META_KEY='chicCanva.cloud.meta.v1',CLOUD_UPLOAD_INTERVAL=10*60*1000,CLOUD_LEASE_MS=3*60*1000;
let cloudStorage=null,cloudRoot=null,cloudCurrent=null,cloudPath=[],cloudSelection=new Set(),cloudEditMode=false,cloudExplorerMode='browse',cloudPendingArtifact=null,cloudPreviewUrl='',cloudDestinationResolver=null,cloudTextResolver=null,cloudConfirmResolver=null,cloudMoveTarget=null,cloudBackupTimer=0,cloudSyncPoll=0,cloudSyncBusy=false,cloudLocalDirty=false,cloudLastPayloadHash='',cloudStartupSnapshot=null;
let cloudMeta=readCloudMeta();

function readCloudMeta(){try{return{backupInstanceId:uid('backup'),syncSessionId:uid('sync'),writerId:uid('writer'),lastRevision:0,lastBackupAt:0,...JSON.parse(localStorage.getItem(CLOUD_META_KEY)||'{}')}}catch(error){return{backupInstanceId:uid('backup'),syncSessionId:uid('sync'),writerId:uid('writer'),lastRevision:0,lastBackupAt:0}}}
function writeCloudMeta(){try{localStorage.setItem(CLOUD_META_KEY,JSON.stringify(cloudMeta))}catch(error){}}
function cloudAvailable({protocol=location.protocol,hostname=location.hostname,secure=globalThis.isSecureContext,subtle=globalThis.crypto?.subtle,Storage=mega?.Storage}={}){const loopback=['localhost','127.0.0.1','::1','[::1]'].includes(String(hostname||'').toLowerCase());return!!((protocol==='https:'||loopback)&&secure&&subtle&&Storage)}
function cloudConnected(){return cloudStorage?.status==='ready'&&!!cloudRoot}
function cloudStatus(message,error=false){const element=$('cloudStatus');if(element){setLocalizedText(element,message||'');element.classList.toggle('error',!!error)}}
function cloudExplorerStatus(message,error=false){const element=$('cloudExplorerStatus');if(element){setLocalizedText(element,message||'');element.classList.toggle('error',!!error)}}
function cloudFilePromise(method,...args){return new Promise((resolve,reject)=>{try{method(...args,(error,result)=>error?reject(error):resolve(result))}catch(error){reject(error)}})}
function cloudSecretDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(CLOUD_SECRET_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(CLOUD_SECRET_STORE))request.result.createObjectStore(CLOUD_SECRET_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function cloudSecret(mode,key,value){const db=await cloudSecretDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(CLOUD_SECRET_STORE,mode),store=tx.objectStore(CLOUD_SECRET_STORE),request=value===undefined?store.get(key):value===null?store.delete(key):store.put(value,key);tx.oncomplete=()=>resolve(request.result);tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function saveCloudSession(){if(!cloudStorage)return;let key=await cloudSecret('readonly','key');if(!key){key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);await cloudSecret('readwrite','key',key)}const iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(cloudStorage.toJSON())),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);await cloudSecret('readwrite','session',{version:1,iv:[...iv],cipher:[...new Uint8Array(cipher)]})}
async function clearCloudSession(){await cloudSecret('readwrite','session',null).catch(()=>{});await cloudSecret('readwrite','key',null).catch(()=>{})}
async function restoreCloudSession(){if(!cloudAvailable())return false;const record=await cloudSecret('readonly','session').catch(()=>null),key=await cloudSecret('readonly','key').catch(()=>null);if(!record||!key)return false;try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(record.iv)},key,new Uint8Array(record.cipher));cloudStorage=mega.Storage.fromJSON(JSON.parse(new TextDecoder().decode(plain)));cloudStorage.options.forceHttps=true;await cloudStorage.reload();cloudStorage.status='ready';await finishCloudConnection(false);return true}catch(error){console.warn('Sessione MEGA non ripristinata',error);await clearCloudSession();cloudStorage=null;return false}}
async function ensureCloudRoot(){cloudRoot=(cloudStorage.root.children||[]).find(node=>node.directory&&node.name===CLOUD_ROOT_NAME)||await cloudStorage.root.mkdir(CLOUD_ROOT_NAME);return cloudRoot}
async function ensureCloudFolder(parent,name){return(parent.children||[]).find(node=>node.directory&&node.name===name)||await parent.mkdir(name)}
async function finishCloudConnection(saveSession){await ensureCloudRoot();if(saveSession)await saveCloudSession();await refreshCloudQuota();syncCloudUi();startCloudSyncWatcher()}
async function cloudLogin(){if(!cloudAvailable())return;const button=$('cloudLoginBtn'),email=$('cloudEmail').value.trim(),password=$('cloudPassword').value,secondFactorCode=$('cloudUse2fa').checked?$('cloud2faCode').value.trim():'';if(!email||!password){cloudStatus('Inserisci email e password MEGA.',true);return}button.disabled=true;cloudStatus('Accesso a MEGA…');try{cloudStorage=new mega.Storage({email,password,secondFactorCode:secondFactorCode||undefined,forceHttps:true,keepalive:true});await cloudStorage.ready;$('cloudPassword').value='';$('cloud2faCode').value='';await finishCloudConnection($('cloudRememberSession').checked);cloudStatus('Cloud Storage collegato.')}catch(error){console.error(error);cloudStorage=null;cloudStatus('Accesso non riuscito: '+(error.message||error),true)}finally{button.disabled=false}}
async function cloudLogout(){stopCloudSyncWatcher();try{cloudStorage?.close?.()}catch(error){}cloudStorage=null;cloudRoot=null;cloudCurrent=null;await clearCloudSession();syncCloudUi();cloudStatus('Sessione MEGA rimossa da questo browser.')}
async function refreshCloudQuota(){if(!cloudStorage)return;try{const info=await cloudStorage.getAccountInfo(),used=Number(info.spaceUsed)||0,total=Number(info.spaceTotal)||0,pct=total?Math.min(100,used/total*100):0;$('cloudQuotaValue').textContent=humanBytes(used)+' / '+humanBytes(total)+' · '+pct.toLocaleString(appLocale(),{maximumFractionDigits:1})+'%';$('cloudQuotaBar').style.width=pct+'%';$('cloudAccountName').textContent=cloudStorage.name||'MEGA';$('cloudAccountEmail').textContent=cloudStorage.email||''}catch(error){cloudStatus('Spazio MEGA non disponibile: '+error.message,true)}}
function syncCloudUi(){const available=cloudAvailable(),connected=cloudConnected();$('cloudUnavailable')?.classList.toggle('hidden',available);$('cloudSignedOut')?.classList.toggle('hidden',!available||connected);$('cloudSignedIn')?.classList.toggle('hidden',!connected);for(const id of ['cloudAutomaticBackup','cloudAutomaticSync','cloudHideSyncBadge'])if($(id))$(id).disabled=!connected;$('cloudCleanupBtn')&&($('cloudCleanupBtn').disabled=!connected);if($('cloudAutomaticBackup'))$('cloudAutomaticBackup').checked=!!preferences.cloudBackup;if($('cloudAutomaticSync'))$('cloudAutomaticSync').checked=!!preferences.cloudSync;if($('cloudHideSyncBadge'))$('cloudHideSyncBadge').checked=!!preferences.cloudHideSyncBadge;syncCloudBadge()}
function nodeInsideCloud(node){for(let value=node;value;value=value.parent)if(value===cloudRoot)return true;return false}
function cloudCanWrite(){return cloudConnected()&&nodeInsideCloud(cloudCurrent)}
function cleanCloudName(value){const name=String(value||'').trim().replace(/[\\/:*?"<>|]/g,'_').slice(0,180);if(!name||name==='.'||name==='..')throw new Error(t('Nome non valido'));return name}
function uniqueCloudName(parent,base,suffix='Clone'){const names=new Set((parent.children||[]).map(node=>node.name.toLocaleLowerCase())),dot=base.lastIndexOf('.'),stem=dot>0?base.slice(0,dot):base,ext=dot>0?base.slice(dot):'';let name=stem+' ('+suffix+')'+ext,index=2;while(names.has(name.toLocaleLowerCase()))name=stem+' ('+suffix+' '+index+++')'+ext;return name}
function cloudMime(name){const extension=String(name).split('.').pop().toLowerCase();return{png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',svg:'image/svg+xml',pdf:'application/pdf',json:'application/json',zip:'application/zip'}[extension]||'application/octet-stream'}
function cloudNodeIcon(node){if(node.directory)return'📁';const type=cloudMime(node.name);return type.startsWith('image/')?'🖼️':type==='application/pdf'?'📄':type==='application/json'?'{}':'📎'}
function revokeCloudPreview(){if(cloudPreviewUrl)URL.revokeObjectURL(cloudPreviewUrl);cloudPreviewUrl=''}
function renderCloudBreadcrumb(){const box=$('cloudBreadcrumb');box.replaceChildren();cloudPath.forEach((node,index)=>{const button=document.createElement('button');button.type='button';button.textContent=index===0?(node===cloudRoot?CLOUD_ROOT_NAME:t('Cloud Drive')):node.name;button.disabled=cloudExplorerMode==='save'&&index===0&&node===cloudRoot;button.onclick=()=>{cloudPath=cloudPath.slice(0,index+1);cloudCurrent=node;cloudSelection.clear();renderCloudExplorer()};box.append(button)});$('cloudBackBtn').disabled=cloudPath.length<=1}
function selectedCloudNodes(){return(cloudCurrent?.children||[]).filter(node=>cloudSelection.has(node.nodeId))}
function syncCloudToolbar(){const selected=selectedCloudNodes(),writable=cloudCanWrite();document.querySelectorAll('.cloud-write-action').forEach(button=>button.disabled=!writable);document.querySelectorAll('.cloud-selection-action').forEach(button=>button.disabled=!writable||!selected.length);$('cloudRenameBtn').disabled=!writable||selected.length!==1;$('cloudCloneBtn').disabled=!writable||selected.length!==1||selected[0]?.directory;$('cloudImportSelected').disabled=!selected.some(node=>!node.directory);$('cloudEditBtn').classList.toggle('active',cloudEditMode)}
async function previewCloudNode(node){revokeCloudPreview();const box=$('cloudPreview');box.replaceChildren();const title=document.createElement('h3');title.textContent=node.name;const meta=document.createElement('p');meta.className='help';meta.textContent=(node.directory?t('Cartella'):humanBytes(node.size))+(node.createdAt?' · '+new Date(node.createdAt).toLocaleString(appLocale()):'');box.append(title,meta);if(node.directory)return;const type=cloudMime(node.name);if((type.startsWith('image/')&&node.size<=30*1024*1024)||type==='application/pdf'&&node.size<=50*1024*1024){const loading=document.createElement('p');setLocalizedText(loading,'Caricamento anteprima…');box.append(loading);try{const data=await node.downloadBuffer({forceHttps:true}),blob=new Blob([data],{type});cloudPreviewUrl=URL.createObjectURL(blob);loading.remove();if(type.startsWith('image/')){const image=document.createElement('img');image.src=cloudPreviewUrl;image.alt=node.name;box.append(image)}else{const frame=document.createElement('iframe');frame.className='cloud-pdf-preview';frame.src=cloudPreviewUrl;frame.title=node.name;box.append(frame)}}catch(error){loading.textContent=t('Anteprima non disponibile')+': '+(error.message||error)}}const actions=document.createElement('div');actions.className='cloud-preview-actions';const open=document.createElement('button');open.className='btn accent';open.type='button';setLocalizedText(open,'Apri in chicCanva');open.onclick=()=>importCloudNodes([node]);actions.append(open);box.append(actions)}
function renderCloudExplorer(){renderCloudBreadcrumb();const box=$('cloudFileList');box.replaceChildren();const children=[...(cloudCurrent?.children||[])].sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name,appLocale(),{sensitivity:'base'}));if(!children.length){const empty=document.createElement('div');empty.className='cloud-preview-empty';setLocalizedText(empty,'Questa cartella è vuota.');box.append(empty)}for(const node of children){const row=document.createElement('button');row.type='button';row.className='cloud-file-row'+(cloudSelection.has(node.nodeId)?' selected':'');row.dataset.nodeId=node.nodeId;row.setAttribute('role','option');row.setAttribute('aria-selected',String(cloudSelection.has(node.nodeId)));const icon=document.createElement('span');icon.className='cloud-file-icon';icon.textContent=cloudNodeIcon(node);const name=document.createElement('span');name.className='cloud-file-name';name.textContent=node.name;const meta=document.createElement('span');meta.className='cloud-file-meta';meta.textContent=node.directory?t('Cartella'):humanBytes(node.size);row.append(icon,name,meta);row.onclick=event=>{if(!cloudEditMode&&!event.ctrlKey&&!event.metaKey)cloudSelection.clear();cloudSelection.has(node.nodeId)?cloudSelection.delete(node.nodeId):cloudSelection.add(node.nodeId);renderCloudExplorer();if(!node.directory)previewCloudNode(node)};row.ondblclick=()=>{if(node.directory){cloudCurrent=node;cloudPath.push(node);cloudSelection.clear();renderCloudExplorer()}else importCloudNodes([node])};box.append(row)}$('cloudConfirmSave').classList.toggle('hidden',cloudExplorerMode!=='save');$('cloudImportSelected').classList.toggle('hidden',cloudExplorerMode!=='browse');syncCloudToolbar()}
async function refreshCloudExplorer(){await cloudStorage.reload();cloudRoot=cloudStorage.root.find(CLOUD_ROOT_NAME)||await ensureCloudRoot();const ids=cloudPath.map(node=>node.nodeId);cloudPath=[cloudExplorerMode==='save'?cloudRoot:cloudStorage.root];for(const id of ids.slice(1)){const next=cloudPath.at(-1).children?.find(node=>node.nodeId===id);if(next)cloudPath.push(next)}cloudCurrent=cloudPath.at(-1);cloudSelection.clear();renderCloudExplorer()}
function openCloudExplorer({mode='browse',artifact=null}={}){if(!cloudConnected()){toast(t('Accedi prima a MEGA'));return}cloudExplorerMode=mode;cloudPendingArtifact=artifact;cloudCurrent=mode==='save'?cloudRoot:cloudStorage.root;cloudPath=[cloudCurrent];cloudSelection.clear();cloudEditMode=false;setLocalizedText($('cloudExplorerTitle'),mode==='save'?'Salva su Cloud':'Cloud Storage');setLocalizedText($('cloudExplorerModeHelp'),mode==='save'?'Scegli una cartella dentro chicCanva Cloud.':'Fuori da chicCanva Cloud i file sono in sola lettura.');cloudExplorerStatus('');revokeCloudPreview();$('cloudPreview').innerHTML='<div class="cloud-preview-empty">'+t('Seleziona un file per visualizzarne i dettagli.')+'</div>';renderCloudExplorer();$('cloudExplorerDialog').showModal()}
function closeCloudExplorer(){revokeCloudPreview();cloudPendingArtifact?.resolve?.(false);cloudPendingArtifact=null;if($('cloudExplorerDialog').open)$('cloudExplorerDialog').close()}
function askCloudText(title,label,value=''){return new Promise(resolve=>{cloudTextResolver=resolve;setLocalizedText($('cloudTextTitle'),title);setLocalizedText($('cloudTextLabel').firstChild,label);$('cloudTextInput').value=value;$('cloudTextDialog').showModal();setTimeout(()=>$('cloudTextInput').focus(),0)})}
function finishCloudText(value=null){if($('cloudTextDialog').open)$('cloudTextDialog').close();const resolve=cloudTextResolver;cloudTextResolver=null;resolve?.(value)}
function askCloudConfirm(title,message){return new Promise(resolve=>{cloudConfirmResolver=resolve;setLocalizedText($('cloudConfirmTitle'),title);setLocalizedText($('cloudConfirmMessage'),message);$('cloudConfirmDialog').showModal()})}
function finishCloudConfirm(value=false){if($('cloudConfirmDialog').open)$('cloudConfirmDialog').close();const resolve=cloudConfirmResolver;cloudConfirmResolver=null;resolve?.(value)}
async function uploadCloudBlob(folder,name,blob,progress=true){name=cleanCloudName(name);const existing=(folder.children||[]).find(node=>!node.directory&&node.name===name);const upload=folder.upload({name,size:blob.size,forceHttps:true},new Uint8Array(await blob.arrayBuffer()));if(progress){$('cloudProgress').classList.remove('hidden');setLocalizedText($('cloudProgressLabel'),'Caricamento '+name+'…');upload.on('progress',event=>{const pct=event.bytesTotal?event.bytesUploaded/event.bytesTotal*100:0;$('cloudProgressBar').value=pct;$('cloudProgressValue').textContent=Math.round(pct)+'%'})}const node=await upload.complete;if(existing)await existing.delete();if(progress)$('cloudProgress').classList.add('hidden');return node}
async function importCloudNodes(nodes=selectedCloudNodes()){const queue=[];for(const node of nodes.filter(item=>!item.directory)){cloudExplorerStatus('Download '+node.name+'…');const data=await node.downloadBuffer({forceHttps:true}),file=new File([data],node.name,{type:cloudMime(node.name),lastModified:node.createdAt||Date.now()}),item={file,kind:classifyIncomingFile(file)};await inspectIncomingItem(item);queue.push(item)}closeCloudExplorer();if(queue.length){incomingShareQueue.push(...queue);await showNextIncomingShare()}}
function chooseCloudDestination(description){if(!cloudConnected())return Promise.resolve('device');return new Promise(resolve=>{cloudDestinationResolver=resolve;$('cloudDestinationInfo').textContent=t(description||'Scegli dove salvare il file.');$('cloudDestinationDialog').showModal()})}
function finishCloudDestination(value){if($('cloudDestinationDialog').open)$('cloudDestinationDialog').close();const resolve=cloudDestinationResolver;cloudDestinationResolver=null;resolve?.(value)}
async function deliverCloudArtifact(artifact,onSuccess){const destination=await chooseCloudDestination(artifact.description);if(destination==='cancel')return false;if(destination==='device')download(artifact.fileName,artifact.blob);else await new Promise(resolve=>{openCloudExplorer({mode:'save',artifact:{...artifact,onSuccess,resolve}})});if(destination==='device')onSuccess?.();return true}
async function runCloudUnifiedExport(){const button=$('exportPdfPanel'),status=$('projectStatus'),label=button.textContent;button.disabled=true;try{const destination=await chooseCloudDestination('Il file verrà generato dopo la scelta della destinazione.');if(destination==='cancel')return;const artifact=await buildUnifiedExportArtifact(message=>status.textContent=message);if(destination==='device')download(artifact.fileName,artifact.blob);else await new Promise(resolve=>openCloudExplorer({mode:'save',artifact:{...artifact,resolve}}));status.textContent=artifact.description}catch(error){console.error(error);status.textContent=t('Esportazione non riuscita: ')+(error.message||error)}finally{button.disabled=false;button.textContent=label}}
async function exportCloudProject(){const record=activeProject();if(!record)return;commitHistory();storeActiveDocument();const artifact=projectExportArtifact(record);await deliverCloudArtifact({...artifact,description:'Progetto chicCanva modificabile.'},()=>markProjectExported(record));$('projectStatus').textContent=t('Progetto «'+record.name+'» esportato.')}
async function exportCloudPromptLibrary(){await loadPromptLibrary();await deliverCloudArtifact({...promptLibraryExportArtifact(),description:'Backup della Prompt Library.'})}
async function cloudSaveHere(){if(!cloudPendingArtifact)return;const pending=cloudPendingArtifact,button=$('cloudConfirmSave');button.disabled=true;try{await uploadCloudBlob(cloudCurrent,pending.fileName,pending.blob);pending.onSuccess?.();cloudExplorerStatus('File salvato su MEGA.');toast(t('File salvato su Cloud'));pending.resolve?.(true);closeCloudExplorer();await refreshCloudQuota()}catch(error){cloudExplorerStatus('Salvataggio non riuscito: '+error.message,true)}finally{button.disabled=false}}

async function sha256Text(text){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));return[...bytes].map(value=>value.toString(16).padStart(2,'0')).join('')}
async function cloudJson(node){if(!node)return null;return JSON.parse(new TextDecoder().decode(await node.downloadBuffer({forceHttps:true})))}
async function cloudUploadJson(folder,name,value){return uploadCloudBlob(folder,name,new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),false)}
async function cloudBackupWorkspace(payload,saved){if(!cloudConnected()||!preferences.cloudBackup)return;const hash=await sha256Text(payload);if(hash===cloudLastPayloadHash)return;const base=await ensureCloudFolder(cloudRoot,CLOUD_BACKUP_NAME),instance=await ensureCloudFolder(base,cloudMeta.backupInstanceId),projectsFolder=await ensureCloudFolder(instance,'projects'),decoded=decodeMemory(payload),stamp=saved.replace(/[:.]/g,'-'),entries=[],written=[];for(const record of decoded.workspace?.projects||[{id:'project',name:decoded.name||'Progetto',payload:decoded}]){const folder=await ensureCloudFolder(projectsFolder,record.id);const blob=new Blob([JSON.stringify(record.payload,null,2)],{type:'application/json'}),name=stamp+' - '+cleanCloudName(record.name||'Progetto')+'.json',node=await uploadCloudBlob(folder,name,blob,false);entries.push({id:record.id,name:record.name,file:node.name,nodeId:node.nodeId});written.push({folder,node})}await cloudUploadJson(instance,'index.json',{version:1,saved,entries});for(const {folder,node} of written)for(const old of [...folder.children||[]])if(old!==node&&old.name!==node.name)await old.delete();cloudLastPayloadHash=hash;cloudMeta.lastBackupAt=Date.now();writeCloudMeta();if($('cloudBackupLog'))$('cloudBackupLog').textContent=t('Ultimo backup')+': '+new Date().toLocaleString(appLocale())}
async function cloudLeaseFolder(syncFolder){return ensureCloudFolder(syncFolder,'leases')}
async function cloudClaimLease(syncFolder){const leases=await cloudLeaseFolder(syncFolder),now=Date.now();for(const node of [...leases.children||[]]){try{const lease=await cloudJson(node);if(lease.expiresAt<now)await node.delete()}catch(error){}}await cloudUploadJson(leases,cloudMeta.writerId+'.json',{writerId:cloudMeta.writerId,expiresAt:now+CLOUD_LEASE_MS});await cloudStorage.reload();const refreshed=cloudStorage.root.find(CLOUD_ROOT_NAME)?.find(CLOUD_SYNC_NAME,true)?.find(cloudMeta.syncSessionId,true)?.find('leases',true),active=[];for(const node of refreshed?.children||[])try{const lease=await cloudJson(node);if(lease.expiresAt>=now)active.push(lease)}catch(error){}active.sort((a,b)=>String(a.writerId).localeCompare(String(b.writerId)));return active[0]?.writerId===cloudMeta.writerId}
async function cloudSyncWorkspace(payload,saved){if(!cloudConnected()||!preferences.cloudSync||cloudSyncBusy)return;cloudSyncBusy=true;try{const base=await ensureCloudFolder(cloudRoot,CLOUD_SYNC_NAME),session=await ensureCloudFolder(base,cloudMeta.syncSessionId);if(!await cloudClaimLease(session)){showCloudConflict();return}const decoded=decodeMemory(payload),revision=Math.max(Number(cloudMeta.lastRevision)||0,Date.now()),revisionFolder=await ensureCloudFolder(session,'revision-'+revision),manifestProjects=[];for(const record of decoded.workspace?.projects||[]){const file=record.id+'.json';await cloudUploadJson(revisionFolder,file,record.payload);manifestProjects.push({id:record.id,name:record.name,file})}await cloudUploadJson(revisionFolder,'workspace.json',decoded);const manifest={version:1,revision,writerId:cloudMeta.writerId,updatedAt:saved,folder:revisionFolder.name,projects:manifestProjects};await cloudUploadJson(session,'current.json',manifest);for(const old of [...session.children||[]])if(old.directory&&old!==revisionFolder&&old.name.startsWith('revision-'))await old.delete();cloudMeta.lastRevision=revision;writeCloudMeta();cloudLocalDirty=false;syncCloudBadge()}finally{cloudSyncBusy=false}}
function chicCloudLocalDirty(){cloudLocalDirty=true}
function chicCloudAutosaveCommitted({payload,saved}){if(!cloudConnected())return;clearTimeout(cloudBackupTimer);const elapsed=Date.now()-(cloudMeta.lastBackupAt||0),delay=Math.max(1500,CLOUD_UPLOAD_INTERVAL-elapsed);cloudBackupTimer=setTimeout(async()=>{try{await cloudBackupWorkspace(payload,saved);await cloudSyncWorkspace(payload,saved)}catch(error){console.error(error);if($('cloudBackupLog'))$('cloudBackupLog').textContent=t('Operazione Cloud non riuscita')+': '+(error.message||error)}},delay)}
async function cloudCurrentSnapshot(){if(!cloudConnected()||!preferences.cloudSync)return null;const base=cloudRoot.find(CLOUD_SYNC_NAME,true),session=base?.find(cloudMeta.syncSessionId,true),manifestNode=session?.children?.find(node=>node.name==='current.json');if(!manifestNode)return null;const manifest=await cloudJson(manifestNode),folder=session.children?.find(node=>node.name===manifest.folder),workspace=folder?.children?.find(node=>node.name==='workspace.json');if(!workspace)return null;const project=await cloudJson(workspace);cloudMeta.lastRevision=manifest.revision;writeCloudMeta();return{saved:manifest.updatedAt,project,manifest}}
async function chicCloudPrepareStartup(){if(!cloudAvailable())return null;await restoreCloudSession();if(cloudConnected())cloudStartupSnapshot=await cloudCurrentSnapshot().catch(error=>{console.warn(error);return null});return cloudStartupSnapshot}
function showCloudConflict(){if(!preferences.cloudSync)return;preferences.cloudSync=false;writePreferences();syncCloudUi();syncCloudBadge(true);if(!$('cloudConflictDialog').open)$('cloudConflictDialog').showModal()}
function syncCloudBadge(force=false){const show=(force||(!preferences.cloudSync&&cloudConnected()&&cloudLocalDirty))&&!preferences.cloudHideSyncBadge;$('cloudOutOfSyncBadge')?.classList.toggle('hidden',!show)}
async function pollCloudSync(){if(!cloudConnected()||!preferences.cloudSync||cloudSyncBusy)return;try{const previous=Number(cloudMeta.lastRevision||0);await cloudStorage.reload();await ensureCloudRoot();const snapshot=await cloudCurrentSnapshot();if(snapshot?.manifest?.writerId!==cloudMeta.writerId&&Number(snapshot.manifest.revision)>previous)showCloudConflict()}catch(error){console.warn('Controllo Cloud',error)}}

function cloudFolderOptions(root,blocked=[]){const blockedIds=new Set(blocked.map(node=>node.nodeId)),result=[];const visit=(folder,depth)=>{if(blockedIds.has(folder.nodeId))return;result.push({folder,depth});for(const child of folder.children||[])if(child.directory)visit(child,depth+1)};visit(root,0);return result}
function openCloudMoveDialog(){const selected=selectedCloudNodes();if(!selected.length)return;cloudMoveTarget=cloudRoot;const box=$('cloudMoveTree');box.replaceChildren();for(const {folder,depth} of cloudFolderOptions(cloudRoot,selected)){const button=document.createElement('button');button.type='button';button.style.paddingLeft=(8+depth*18)+'px';button.textContent=(depth?'↳ ':'')+folder.name;button.classList.toggle('active',folder===cloudMoveTarget);button.onclick=()=>{cloudMoveTarget=folder;box.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button))};box.append(button)}$('cloudMoveDialog').showModal()}
async function confirmCloudMove(){const selected=selectedCloudNodes();if(!cloudMoveTarget||!selected.length)return;for(const node of selected)await node.moveTo(cloudMoveTarget);$('cloudMoveDialog').close();await refreshCloudExplorer()}
function startCloudSyncWatcher(){stopCloudSyncWatcher();cloudSyncPoll=setInterval(pollCloudSync,30000)}
function stopCloudSyncWatcher(){clearInterval(cloudSyncPoll);cloudSyncPoll=0;clearTimeout(cloudBackupTimer)}
async function applyCloudSnapshot(snapshot){if(!snapshot?.project)return;const memory={saved:snapshot.saved,project:snapshot.project};localStorage.setItem(MEMORY_KEY,JSON.stringify({version:2,saved:memory.saved,project:encodeMemory(memory.project),pendingDatabase:true}));location.reload()}
async function clearCloudArea(name,instanceOnly=false){const base=cloudRoot.find(name,true);if(!base)return;if(instanceOnly){const node=base.children?.find(item=>item.name===cloudMeta.backupInstanceId);if(node)await node.delete()}else await base.delete();await cloudStorage.reload();await ensureCloudRoot();toast(t('Dati Cloud spostati nel Cestino MEGA'))}

function bindCloudStorage(){syncCloudUi();$('cloudUse2fa').onchange=()=>$('cloud2faRow').classList.toggle('hidden',!$('cloudUse2fa').checked);$('cloudLoginBtn').onclick=cloudLogin;$('cloudLogoutBtn').onclick=cloudLogout;$('openCloudExplorerBtn').onclick=()=>openCloudExplorer();$('closeCloudExplorer').onclick=closeCloudExplorer;$('cloudCancelExplorer').onclick=closeCloudExplorer;$('cloudBackBtn').onclick=()=>{if(cloudPath.length>1){cloudPath.pop();cloudCurrent=cloudPath.at(-1);cloudSelection.clear();renderCloudExplorer()}};$('cloudRefreshBtn').onclick=()=>refreshCloudExplorer().catch(error=>cloudExplorerStatus(error.message,true));$('cloudEditBtn').onclick=()=>{cloudEditMode=!cloudEditMode;if(!cloudEditMode)cloudSelection.clear();renderCloudExplorer()};$('cloudNewFolderBtn').onclick=async()=>{const name=await askCloudText('Nuova cartella','Nome della cartella');if(name)try{await cloudCurrent.mkdir(cleanCloudName(name));await refreshCloudExplorer()}catch(error){cloudExplorerStatus(error.message,true)}};$('cloudRenameBtn').onclick=async()=>{const node=selectedCloudNodes()[0],name=node&&await askCloudText('Rinomina','Nuovo nome',node.name);if(name)try{await node.rename(cleanCloudName(name));await refreshCloudExplorer()}catch(error){cloudExplorerStatus(error.message,true)}};$('cloudCloneBtn').onclick=async()=>{const node=selectedCloudNodes()[0];if(!node)return;if(!await askCloudConfirm('Duplica file','Creare una copia di «'+node.name+'»?'))return;try{await node.copyTo(cloudCurrent);await cloudStorage.reload();const copy=[...(cloudCurrent.children||[])].filter(item=>item.name===node.name).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))[0];if(copy&&copy!==node)await copy.rename(uniqueCloudName(cloudCurrent,node.name));await refreshCloudExplorer()}catch(error){cloudExplorerStatus(error.message,true)}};$('cloudDeleteBtn').onclick=async()=>{const nodes=selectedCloudNodes();if(!nodes.length||!await askCloudConfirm('Sposta nel Cestino','Spostare '+nodes.length+' '+(nodes.length===1?'elemento':'elementi')+' nel Cestino MEGA?'))return;for(const node of nodes)await node.delete();await refreshCloudExplorer()};$('cloudImportSelected').onclick=()=>importCloudNodes().catch(error=>cloudExplorerStatus(error.message,true));$('cloudConfirmSave').onclick=cloudSaveHere;
 $('cloudMoveBtn').onclick=openCloudMoveDialog;$('cloudMoveConfirm').onclick=()=>confirmCloudMove().catch(error=>cloudExplorerStatus(error.message,true));$('cloudMoveCancel').onclick=()=>$('cloudMoveDialog').close();$('cloudTextConfirm').onclick=()=>finishCloudText($('cloudTextInput').value);$('cloudTextCancel').onclick=()=>finishCloudText();$('cloudTextDialog').oncancel=event=>{event.preventDefault();finishCloudText()};$('cloudConfirmYes').onclick=()=>finishCloudConfirm(true);$('cloudConfirmNo').onclick=()=>finishCloudConfirm(false);$('cloudConfirmDialog').oncancel=event=>{event.preventDefault();finishCloudConfirm(false)};$('cloudSaveDevice').onclick=()=>finishCloudDestination('device');$('cloudSaveRemote').onclick=()=>finishCloudDestination('cloud');$('cloudDestinationCancel').onclick=()=>finishCloudDestination('cancel');
 $('exportPdfPanel').onclick=runCloudUnifiedExport;$('exportJsonPanel').onclick=exportCloudProject;$('exportJsonBtn').onclick=exportCloudProject;$('exportPromptLibraryBtn').onclick=exportCloudPromptLibrary;
 $('cloudAutomaticBackup').onchange=()=>{preferences.cloudBackup=$('cloudAutomaticBackup').checked;writePreferences();scheduleAutosave()};$('cloudAutomaticSync').onchange=()=>{preferences.cloudSync=$('cloudAutomaticSync').checked;if(preferences.cloudSync&&!cloudMeta.syncSessionId)cloudMeta.syncSessionId=uid('sync');writeCloudMeta();writePreferences();syncCloudBadge();scheduleAutosave()};$('cloudHideSyncBadge').onchange=()=>{preferences.cloudHideSyncBadge=$('cloudHideSyncBadge').checked;writePreferences();syncCloudBadge()};$('cloudCleanupBtn').onclick=()=>$('cloudCleanupDialog').showModal();$('cloudCleanupCancel').onclick=()=>$('cloudCleanupDialog').close();$('cloudClearInstanceBackups').onclick=()=>clearCloudArea(CLOUD_BACKUP_NAME,true).finally(()=>$('cloudCleanupDialog').close());$('cloudClearAllBackups').onclick=()=>clearCloudArea(CLOUD_BACKUP_NAME).finally(()=>$('cloudCleanupDialog').close());$('cloudClearSync').onclick=()=>clearCloudArea(CLOUD_SYNC_NAME).finally(()=>$('cloudCleanupDialog').close());$('cloudConflictReload').onclick=()=>cloudCurrentSnapshot().then(applyCloudSnapshot);$('cloudConflictLocal').onclick=()=>{$('cloudConflictDialog').close();syncCloudBadge(true)};$('cloudOutOfSyncBadge').onclick=()=>$('cloudConflictDialog').showModal();window.addEventListener('pagehide',stopCloudSyncWatcher)
}
globalThis.chicCloudPrepareStartup=chicCloudPrepareStartup;globalThis.chicCloudLocalDirty=chicCloudLocalDirty;globalThis.chicCloudAutosaveCommitted=chicCloudAutosaveCommitted;
const cloudStorageBaseInit=init;init=async function(){await cloudStorageBaseInit();bindCloudStorage();if(!cloudConnected())await restoreCloudSession().catch(()=>{});syncCloudUi()};
const cloudStorageClearAllMemory=clearAllMemory;clearAllMemory=async function(){await cloudStorageClearAllMemory();stopCloudSyncWatcher();try{cloudStorage?.close?.()}catch(error){}cloudStorage=null;cloudRoot=null;preferences.cloudBackup=false;preferences.cloudSync=false;preferences.cloudHideSyncBadge=false;try{localStorage.removeItem(CLOUD_META_KEY)}catch(error){}await clearCloudSession();cloudMeta=readCloudMeta();syncCloudUi()};
