// v7 interaction refinements: groups, page ordering, collapsible tools and file mode.
let previewReorder=false,previewSelected=-1,pageDragIndex=-1;
const copyIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></svg>';
const pasteIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5h6M9 3h6v4H9z"/><rect x="5" y="5" width="14" height="16" rx="2"/></svg>';
const trashIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m9 9 6 6m0-6-6 6"/></svg>';
const exportRegionIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4" stroke-dasharray="2 1"/><path d="M12 7v9M9 13l3 3 3-3"/></svg>';
function objectTree(objects){const out=[];const walk=o=>{out.push(o);if(o.type==='group'||o.objectType==='group')o.getObjects?.().forEach(walk)};objects.forEach(walk);return out}
function selectedTree(){return objectTree(selectionObjects().filter(o=>o!==exportRegion&&o!==cropSession?.rect))}
function refreshGroupBounds(top){for(const o of top){if(o.type==='group'){o._calcBounds?.();o._updateObjectsCoords?.();o.dirty=true}o.setCoords?.()}}
applyFontToSelectionOrFuture=function(name){const top=selectionObjects().filter(o=>!o.excludeProject),scope=top.length?objectTree(top):objectTree(canvas.getObjects()),texts=scope.filter(o=>o.objectType==='text');texts.forEach(o=>{o.set({fontFamily:name});o.dirty=true});if(texts.length){refreshGroupBounds(top.length?top:canvas.getObjects());canvas.requestRenderAll();saveActivePage();toast('Font applicato a '+texts.length+' testi')}refreshFontPreviews()};
applyTextStyle=function(){syncStateFromUI();const top=selectionObjects().filter(o=>!o.excludeProject),texts=objectTree(top).filter(o=>o.objectType==='text');texts.forEach(o=>{o.set(textPaint());o.outlineMode=state.outline;o.dirty=true});refreshGroupBounds(top);canvas.requestRenderAll();saveActivePage();toast(texts.length?'Stile applicato a '+texts.length+' testi':'Stile impostato per i prossimi testi')};
const earlierSelectionChanged=selectionChanged;selectionChanged=function(){earlierSelectionChanged();const active=canvas?.getActiveObject(),isGroup=active?.type==='group'||active?.objectType==='group';if(active){active.set({borderColor:isGroup?'#7549b8':'#5b50e6',cornerColor:isGroup?'#7549b8':'#5b50e6',borderScaleFactor:isGroup?2.4:1});active.setCoords?.()}$('selectionInfo')?.classList.toggle('selection-group-hint',!!isGroup);if(isGroup)$('selectionInfo').textContent='Gruppo selezionato · '+active.getObjects().length+' elementi';canvas?.requestRenderAll()};
function groupSelection(){if(cropSession||loadingPage)return;const active=canvas.getActiveObject();if(active?.type!=='activeSelection'||active.getObjects().length<2){toast('Seleziona almeno due oggetti');return}const group=active.toGroup();group.objectType='group';group.projectId=uid('obj');group.set({borderColor:'#7549b8',cornerColor:'#7549b8',borderScaleFactor:2.4});group.setControlVisible('mtr',state.rotateEnabled);canvas.setActiveObject(group);canvas.requestRenderAll();saveActivePage();selectionChanged();toast('Oggetti raggruppati')}
function ungroupSelection(){if(cropSession||loadingPage)return;const group=canvas.getActiveObject();if(group?.type!=='group'){toast('Seleziona un gruppo da dividere');return}const selection=group.toActiveSelection();selection.getObjects().forEach(o=>{o.projectId=o.projectId||uid('obj');o.setControlVisible?.('mtr',state.rotateEnabled)});canvas.setActiveObject(selection);canvas.requestRenderAll();saveActivePage();selectionChanged();toast('Gruppo diviso: gli elementi restano selezionati')}
async function richToken(token,target,source=null){const chars=graphemes(token),hasEmoji=state.smartEmoji&&chars.some(isEmoji);if(!hasEmoji){const o=source?new fabric.Text(token,{fontFamily:source.fontFamily,fontSize:source.fontSize,fontWeight:source.fontWeight,fill:source.fill,stroke:source.stroke,strokeWidth:source.strokeWidth,paintFirst:'stroke',objectCaching:false,charSpacing:source.charSpacing,lineHeight:source.lineHeight,textAlign:source.textAlign,originX:'center',originY:'center'}):makeTextObj(token,0,0,100);o.objectType='text';o.outlineMode=source?.outlineMode??state.outline;o.projectId=uid('obj');target.add(o);return o}const runs=[];let text='';for(const c of chars){if(isEmoji(c)){if(text){runs.push({text});text=''}runs.push({emoji:c})}else text+=c}if(text)runs.push({text});const pieces=[];let x=0;for(const run of runs){let o;if(run.emoji)o=await instantiateObject(await makeGlyphDescriptor(run.emoji,0,0,source?.fontSize||100),target);else{o=source?new fabric.Text(run.text,{fontFamily:source.fontFamily,fontSize:source.fontSize,fontWeight:source.fontWeight,fill:source.fill,stroke:source.stroke,strokeWidth:source.strokeWidth,paintFirst:'stroke',objectCaching:false,charSpacing:source.charSpacing,lineHeight:source.lineHeight,textAlign:source.textAlign,originX:'center',originY:'center'}):makeTextObj(run.text,0,0,100);o.objectType='text';o.outlineMode=source?.outlineMode??state.outline;o.projectId=uid('obj');target.add(o)}o.set({left:x+o.getScaledWidth()/2,top:0});o.setCoords();x+=o.getScaledWidth()+4;pieces.push(o)}if(pieces.length===1)return pieces[0];pieces.forEach(o=>target.remove(o));const group=new fabric.Group(pieces,{originX:'center',originY:'center'});group.objectType='group';group.projectId=uid('obj');group.setControlVisible('mtr',state.rotateEnabled);target.add(group);return group}
tokenObject=richToken;
async function splitSelectedText(){if(cropSession||loadingPage)return;const source=canvas.getActiveObject();if(source?.objectType!=='text'){toast('Seleziona un singolo oggetto di testo');return}syncStateFromUI();const groups=groupGraphemes(graphemes(source.text)).map(x=>x.join(''));if(groups.length<2){toast('Il testo produce un solo gruppo');return}canvas.discardActiveObject();const pieces=[];let x=0;for(const token of groups){const o=await richToken(token,canvas,source);o.set({left:x+o.getScaledWidth()/2,top:0});o.setCoords();x+=o.getScaledWidth()+6;pieces.push(o)}pieces.forEach(o=>canvas.remove(o));const holder=new fabric.Group(pieces,{left:source.left,top:source.top,originX:source.originX||'center',originY:source.originY||'center',angle:source.angle||0,scaleX:source.scaleX||1,scaleY:source.scaleY||1});holder.objectType='group';holder.projectId=uid('obj');canvas.remove(source);canvas.add(holder);const selection=holder.toActiveSelection();canvas.setActiveObject(selection);canvas.requestRenderAll();saveActivePage();selectionChanged();toast('Testo diviso in '+groups.length+' oggetti')}
splitSelectedText=withHistory(splitSelectedText);

function insertPageAfterCurrent(){if(workspaceBusy())return;saveActivePage();const current=state.pages.custom[state.pageIndex.custom],page=makePage('Pagina '+(state.pages.custom.length+1),current.widthMm,current.heightMm);state.pages.custom.splice(state.pageIndex.custom+1,0,page);state.pageIndex.custom++;loadPage(page);commitHistory();scheduleAutosave()}
function movePage(from,to,open=true){const pages=state.pages.custom;if(from<0||from>=pages.length||to<0||to>=pages.length||from===to)return false;saveActivePage();const [page]=pages.splice(from,1);pages.splice(to,0,page);const currentId=currentPage?.id;state.pageIndex.custom=Math.max(0,pages.findIndex(p=>p.id===currentId));commitHistory();renderCustomChips();updatePageNavigation();if(open&&pages[to]){state.pageIndex.custom=to;loadPage(pages[to])}scheduleAutosave();return true}
function decoratePageChips(){const chips=[...$('customPageChips').querySelectorAll('.page-chip')];chips.forEach((chip,i)=>{chip.draggable=true;chip.dataset.index=i;chip.addEventListener('dragstart',e=>{pageDragIndex=i;chip.classList.add('dragging');e.dataTransfer.effectAllowed='move'});chip.addEventListener('dragend',()=>{pageDragIndex=-1;chip.classList.remove('dragging');chips.forEach(c=>c.classList.remove('drop-before','drop-after'))});chip.addEventListener('dragover',e=>{e.preventDefault();chips.forEach(c=>c.classList.remove('drop-before','drop-after'));chip.classList.add(e.offsetX<chip.offsetWidth/2?'drop-before':'drop-after')});chip.addEventListener('drop',e=>{e.preventDefault();const after=e.offsetX>=chip.offsetWidth/2,target=i+(after?1:0)-(pageDragIndex<i?1:0);movePage(pageDragIndex,clamp(target,0,state.pages.custom.length-1),false)})})}
const priorRenderChips=renderCustomChips;renderCustomChips=function(){priorRenderChips();decoratePageChips();$('pageMoveLeft').disabled=state.pageIndex.custom<=0;$('pageMoveRight').disabled=state.pageIndex.custom>=state.pages.custom.length-1};
function renderPreviewV7(){const grid=$('previewGrid'),pages=state.pages.custom;grid.replaceChildren();grid.classList.toggle('reordering',previewReorder);previewObserver?.disconnect();previewObserver=new IntersectionObserver(entries=>entries.forEach(async entry=>{if(!entry.isIntersecting)return;previewObserver.unobserve(entry.target);const page=pages.find(p=>p.id===entry.target.dataset.page);if(!page)return;try{const url=await renderPageDataUrl(page,Math.min(60,420/(Math.max(page.widthMm,page.heightMm)*PX_PER_MM)*96));if(entry.target.isConnected){const image=document.createElement('img');image.src=url;image.alt=page.name;entry.target.querySelector('.preview-sheet').append(image)}}catch(e){entry.target.querySelector('.preview-sheet').textContent='Anteprima non disponibile'}}),{root:$('previewPanel'),rootMargin:'400px'});pages.forEach((page,i)=>{const tile=document.createElement('button');tile.className='preview-page '+(page.widthMm>page.heightMm?'landscape':'portrait')+(i===previewSelected?' selected':'');tile.dataset.page=page.id;tile.dataset.index=i;tile.draggable=previewReorder;const sheet=document.createElement('div');sheet.className='preview-sheet';sheet.style.aspectRatio=page.widthMm+'/'+page.heightMm;const label=document.createElement('span');label.textContent=(i+1)+'. '+page.name;tile.append(sheet,label);tile.onclick=async()=>{if(previewReorder){previewSelected=i;renderPreviewV7();syncPreviewArrows();return}closePreview();saveActivePage();state.pageIndex.custom=i;await loadPage(page)};tile.addEventListener('dragstart',e=>{pageDragIndex=i;tile.classList.add('dragging');e.dataTransfer.effectAllowed='move'});tile.addEventListener('dragend',()=>{pageDragIndex=-1;tile.classList.remove('dragging')});tile.addEventListener('dragover',e=>{if(!previewReorder)return;e.preventDefault();tile.classList.toggle('drop-before',e.offsetX<tile.offsetWidth/2);tile.classList.toggle('drop-after',e.offsetX>=tile.offsetWidth/2)});tile.addEventListener('dragleave',()=>tile.classList.remove('drop-before','drop-after'));tile.addEventListener('drop',e=>{if(!previewReorder)return;e.preventDefault();const after=e.offsetX>=tile.offsetWidth/2,target=i+(after?1:0)-(pageDragIndex<i?1:0);if(movePage(pageDragIndex,clamp(target,0,pages.length-1),false)){previewSelected=clamp(target,0,pages.length-1);renderPreviewV7();syncPreviewArrows()}});grid.append(tile);previewObserver.observe(tile)});syncPreviewArrows()}
openPreview=function(){saveActivePage();$('previewPanel').classList.remove('hidden');previewSelected=state.pageIndex.custom;renderPreviewV7()};
function syncPreviewArrows(){$('previewMoveLeft').disabled=!previewReorder||previewSelected<=0;$('previewMoveRight').disabled=!previewReorder||previewSelected<0||previewSelected>=state.pages.custom.length-1;$('previewReorder').classList.toggle('active',previewReorder)}

function updateExplicitUI(){const active=$('specialExplicit').checked;$('specialRuleOptions').classList.toggle('explicit-disabled',active);for(const input of $('specialRuleOptions').querySelectorAll('input'))input.disabled=active;const raw=$('specialText').value,parts=raw.split('^').map(s=>s.trim()).filter(Boolean);$('specialGroupPreview').textContent=active?(parts.length?parts.length+' gruppi: '+parts.map(x=>'“'+x+'”').join(' · '):'Separa i gruppi con ^'): 'Un carattere o gruppo per pagina.'}
function setupCollapsible(){const sidebar=$('sidebar'),cards=[...sidebar.querySelectorAll(':scope > .card')].filter(c=>c.querySelector(':scope > .card-h'));cards.forEach((card,i)=>{card.dataset.section=card.id||'section-'+i;const head=card.querySelector(':scope > .card-h');head.setAttribute('role','button');head.tabIndex=0;head.setAttribute('aria-expanded',String(!card.classList.contains('collapsed')));const activate=()=>{if(preferences.accordion){cards.forEach(c=>c.classList.toggle('collapsed',c!==card));card.classList.remove('collapsed')}else card.classList.toggle('collapsed');cards.forEach(c=>c.querySelector(':scope > .card-h')?.setAttribute('aria-expanded',String(!c.classList.contains('collapsed'))));preferences.collapsed=cards.filter(c=>c.classList.contains('collapsed')).map(c=>c.dataset.section);writePreferences()};head.onclick=e=>{if(e.target.closest('button,input,select,a'))return;activate()};head.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}}});const applyStored=()=>cards.forEach(c=>c.classList.toggle('collapsed',preferences.collapsed?.includes(c.dataset.section)));applyStored();$('singleSection').checked=!!preferences.accordion;$('collapseSections').onclick=()=>{preferences.accordion=false;preferences.collapsed=cards.map(c=>c.dataset.section);$('singleSection').checked=false;applyStored();writePreferences()};$('expandSections').onclick=()=>{preferences.accordion=false;preferences.collapsed=[];$('singleSection').checked=false;applyStored();writePreferences()};$('singleSection').onchange=()=>{preferences.accordion=$('singleSection').checked;if(preferences.accordion){const visible=cards.find(c=>!c.classList.contains('collapsed'))||cards[0];cards.forEach(c=>c.classList.toggle('collapsed',c!==visible));preferences.collapsed=cards.filter(c=>c.classList.contains('collapsed')).map(c=>c.dataset.section)}writePreferences()};for(const button of sidebar.querySelectorAll('.quick-jump button')){const old=button.onclick;button.onclick=()=>{const labels={Pagina:'customCardTitle',Speciali:'specialCard',Testo:'textInput',Font:'fontMode',Emoji:'emojiSearch',Immagini:'uploadImageBtn',AI:'aiCard',Export:'pdfMode'},target=$(labels[button.textContent]),card=target?.closest('.card');if(card){if(preferences.accordion)cards.forEach(c=>c.classList.toggle('collapsed',c!==card));card.classList.remove('collapsed');card.querySelector(':scope > .card-h')?.setAttribute('aria-expanded','true');preferences.collapsed=cards.filter(c=>c.classList.contains('collapsed')).map(c=>c.dataset.section);writePreferences();card.dataset.flash='true';setTimeout(()=>delete card.dataset.flash,700);card.scrollIntoView({behavior:'smooth',block:'start'})}else old?.()}}}
const oldReadPreferences=readPreferences;readPreferences=function(){oldReadPreferences();try{const p=JSON.parse(localStorage.getItem(PREF_KEY)||'{}');preferences.accordion=p.accordion!==false;preferences.collapsed=Array.isArray(p.collapsed)?p.collapsed:[]}catch(e){preferences.accordion=true;preferences.collapsed=[]}};
const baseSetupCollapsible=setupCollapsible;setupCollapsible=function(){baseSetupCollapsible();if(!preferences.accordion)return;const cards=[...$('sidebar').querySelectorAll(':scope > .card')].filter(c=>c.querySelector(':scope > .card-h')),visible=cards.find(c=>!c.classList.contains('collapsed'))||cards[0];cards.forEach(c=>{c.classList.toggle('collapsed',c!==visible);c.querySelector(':scope > .card-h')?.setAttribute('aria-expanded',String(c===visible))});preferences.collapsed=cards.filter(c=>c.classList.contains('collapsed')).map(c=>c.dataset.section);$('singleSection').checked=true};
function applyFileMode(){if(location.protocol!=='file:')return;const ai=$('aiCard'),body=ai.querySelector('.card-b');ai.classList.add('server-disabled');for(const e of body.querySelectorAll('input,select,textarea,button'))e.disabled=true;const message=document.createElement('div');message.className='server-message';message.textContent='Per usare la funzione apri l’app tramite webserver.';body.prepend(message);const option=$('bgMethod').querySelector('option[value="ai"]');if(option)option.disabled=true;$('bgMethod').value='solid';$('bgMethod').dispatchEvent(new Event('change'));$('bgAiOptions').classList.add('hidden');$('removeBgStatus').textContent='La rimozione dello sfondo uniforme è disponibile. Per la rimozione AI apri l’app tramite webserver.'}
let renameTarget=null,projectMenuId=null,pageMenuId=null;
function hideNamingMenus(){for(const id of ['projectTabMenu','pageTabMenu'])$(id)?.classList.add('hidden')}
function showNamingMenu(id,event){hideNamingMenus();const menu=$(id);menu.classList.remove('hidden');menu.style.left=clamp(event.clientX,8,innerWidth-menu.offsetWidth-8)+'px';menu.style.top=clamp(event.clientY,8,innerHeight-menu.offsetHeight-8)+'px'}
function beginRename(kind,id){hideNamingMenus();const item=kind==='project'?projects.find(p=>p.id===id):state.pages.custom.find(p=>p.id===id);if(!item)return;renameTarget={kind,id};$('renameDialogTitle').textContent=kind==='project'?'Rinomina progetto':'Rinomina pagina';$('renameInput').value=item.name;$('renameDialog').showModal();setTimeout(()=>{$('renameInput').focus();$('renameInput').select()},0)}
function confirmRename(){const name=$('renameInput').value.trim();if(!renameTarget||!name)return;const {kind,id}=renameTarget;if(kind==='project'){const project=projects.find(p=>p.id===id);if(project){project.name=name.slice(0,100);project.payload.name=project.name;project.lastExport=null;if(id===activeProjectId)storeActiveDocument();renderProjectTabs();scheduleAutosave();toast('Progetto rinominato')}}else{saveActivePage();commitHistory();const page=state.pages.custom.find(p=>p.id===id);if(page){page.name=name.slice(0,100);if(page.id===currentPage?.id){$('customPageName').value=page.name;$('pageCaption').textContent=page.name}updatePageNavigation();renderCustomChips();if(!$('previewPanel').classList.contains('hidden'))renderPreviewV7();scheduleCommit();scheduleAutosave();toast('Pagina rinominata')}}renameTarget=null;$('renameDialog').close()}
async function openPageFromMenu(id){const index=state.pages.custom.findIndex(p=>p.id===id);if(index<0)return;closePreview();saveActivePage();state.pageIndex.custom=index;await loadPage(state.pages.custom[index])}
async function duplicatePageFromMenu(id){saveActivePage();commitHistory();const index=state.pages.custom.findIndex(p=>p.id===id),page=state.pages.custom[index];if(!page)return;const copy=cloneData(page);copy.id=uid('page');copy.name=page.name+' copia';visitDescriptors(copy.objects||[],o=>o.id=uid('obj'));state.pages.custom.splice(index+1,0,copy);state.pageIndex.custom=index+1;closePreview();await loadPage(copy);scheduleCommit();scheduleAutosave();toast('Pagina duplicata')}
function decorateProjectRename(){[...$('projectTabs').querySelectorAll('.project-tab')].forEach((tab,index)=>{const project=projects[index],name=tab.querySelector('.project-name');if(!project||!name)return;name.title=project.name+' · doppio clic o clic destro per rinominare';name.ondblclick=e=>{e.preventDefault();beginRename('project',project.id)};name.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();projectMenuId=project.id;showNamingMenu('projectTabMenu',e)};name.onkeydown=e=>{if(e.key==='F2'||(e.shiftKey&&e.key==='F10')){e.preventDefault();beginRename('project',project.id)}}})}
function decoratePageRename(){[...$('customPageChips').querySelectorAll('.page-chip')].forEach((chip,index)=>{const page=state.pages.custom[index];if(!page)return;chip.title=page.name+' · doppio clic o clic destro per rinominare';chip.ondblclick=e=>{e.preventDefault();beginRename('page',page.id)};chip.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();pageMenuId=page.id;showNamingMenu('pageTabMenu',e)};chip.onkeydown=e=>{if(e.key==='F2'||(e.shiftKey&&e.key==='F10')){e.preventDefault();beginRename('page',page.id)}}})}
function decoratePreviewRename(){[...$('previewGrid').querySelectorAll('.preview-page')].forEach(tile=>{const id=tile.dataset.page,open=tile.onclick;let clickTimer;tile.title='Doppio clic o clic destro per rinominare';tile.onclick=e=>{if(e.detail>1){clearTimeout(clickTimer);return}clickTimer=setTimeout(()=>open?.(e),220)};tile.ondblclick=e=>{clearTimeout(clickTimer);e.preventDefault();e.stopPropagation();beginRename('page',id)};tile.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();pageMenuId=id;showNamingMenu('pageTabMenu',e)}})}
const baseRenderProjects=renderProjectTabs;renderProjectTabs=function(){baseRenderProjects();decorateProjectRename()};
const baseDecoratePageChips=decoratePageChips;decoratePageChips=function(){baseDecoratePageChips();decoratePageRename()};
const baseRenderPreview=renderPreviewV7;renderPreviewV7=function(){baseRenderPreview();decoratePreviewRename()};
function setupRenameUi(){$('renameConfirm').onclick=confirmRename;$('renameCancel').onclick=()=>{$('renameDialog').close();renameTarget=null};$('renameInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();confirmRename()}};$('projectTabMenu').onclick=e=>{const action=e.target.closest('[data-project-action]')?.dataset.projectAction,id=projectMenuId;hideNamingMenus();if(!id)return;if(action==='rename')beginRename('project',id);if(action==='export'){const project=projects.find(p=>p.id===id);if(project)exportProjectRecord(project)}if(action==='close')requestCloseProject(id)};$('pageTabMenu').onclick=e=>{const action=e.target.closest('[data-page-action]')?.dataset.pageAction,id=pageMenuId;hideNamingMenus();if(!id)return;if(action==='rename')beginRename('page',id);if(action==='open')openPageFromMenu(id);if(action==='duplicate')duplicatePageFromMenu(id)};document.addEventListener('pointerdown',e=>{if(!e.target.closest('#projectTabMenu,#pageTabMenu'))hideNamingMenus()});window.addEventListener('keydown',e=>{if(e.key==='Escape')hideNamingMenus()})}
function setupEnhancedUi(){
 $('copyTool').innerHTML=copyIcon;$('pasteTool').innerHTML=pasteIcon;$('deleteTool').innerHTML=trashIcon;$('exportRegionTool').innerHTML=exportRegionIcon;$('copyTool').setAttribute('aria-label','Copia oggetti');$('pasteTool').setAttribute('aria-label','Incolla oggetti');$('deleteTool').setAttribute('aria-label','Elimina selezione');$('exportRegionTool').setAttribute('aria-label','Disegna area da esportare');const contextActions={group:groupSelection,ungroup:ungroupSelection,split:splitSelectedText};for(const b of document.querySelectorAll('#objectMenu [data-action="group"],#objectMenu [data-action="ungroup"],#objectMenu [data-action="split"]'))b.onclick=()=>{hideContext();contextActions[b.dataset.action]()};
 $('quickAddPage').onclick=insertPageAfterCurrent;$('quickAddNav').onclick=insertPageAfterCurrent;$('groupTool').onclick=groupSelection;$('ungroupTool').onclick=ungroupSelection;$('splitTool').onclick=splitSelectedText;$('applyStyleSelection').onclick=applyTextStyle;
 $('pageMoveLeft').onclick=()=>movePage(state.pageIndex.custom,state.pageIndex.custom-1);$('pageMoveRight').onclick=()=>movePage(state.pageIndex.custom,state.pageIndex.custom+1);$('customPageName').oninput=()=>{const p=state.pages.custom[state.pageIndex.custom];if(p){p.name=$('customPageName').value||'Pagina senza nome';$('pageCaption').textContent=p.name;updatePageNavigation();scheduleCommit();scheduleAutosave()}};$('pageCaption').classList.add('page-caption-editable');$('pageCaption').title='Clicca per modificare il nome della pagina';$('pageCaption').onclick=()=>{$('customPageName').closest('.card').classList.remove('collapsed');$('customPageName').focus();$('customPageName').select()};
 $('previewReorder').onclick=()=>{previewReorder=!previewReorder;renderPreviewV7()};$('previewMoveLeft').onclick=()=>{if(movePage(previewSelected,previewSelected-1,false)){previewSelected--;renderPreviewV7()}};$('previewMoveRight').onclick=()=>{if(movePage(previewSelected,previewSelected+1,false)){previewSelected++;renderPreviewV7()}};
 $('specialExplicit').onchange=updateExplicitUI;$('specialText').oninput=updateExplicitUI;updateExplicitUI();setupCollapsible();setupRenameUi();applyFileMode();renderCustomChips();renderProjectTabs();updateTextModeUI();refreshFontPreviews();
 window.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.querySelector('dialog[open]'))return;if(e.key.toLowerCase()==='g'){e.preventDefault();e.stopImmediatePropagation();e.shiftKey?ungroupSelection():groupSelection()}},true);
}
const v7BindWorkspace=bindWorkspace;bindWorkspace=function(){v7BindWorkspace();setupEnhancedUi()};
