// Native file sharing, PWA share-target intake, and explicit Trystero/WebRTC transfers.
const SHARE_INBOX_DB='chicCanva-share-inbox',SHARE_INBOX_STORE='shares',P2P_APP_ID='chiccanva-project-transfer-v1',P2P_PROTOCOL=1,P2P_MAX_ITEM_BYTES=160*1024*1024,P2P_MAX_TOTAL_BYTES=256*1024*1024,P2P_CUSTOM_RELAY_KEY='chicCanva.p2p.customRelay';
const P2P_RELAY_POOL=['wss://basspistol.org','wss://bucket.coracle.social','wss://chorus.pjv.me','wss://koru.bitcointxoko.org','wss://nos.lol','wss://nostr-01.uid.ovh','wss://nostr-01.yakihonne.com','wss://nostr-relay.corb.net','wss://nostr.data.haus','wss://nostr.islandarea.net','wss://nostr.sathoarder.com','wss://nostr.tegila.com.br','wss://nostr.vulpem.com','wss://purplerelay.com','wss://relay-can.zombi.cloudrodion.com','wss://relay-rpi.edufeed.org','wss://relay.agorist.space','wss://relay.artio.inf.unibe.ch','wss://relay.mostr.pub','wss://relay.mostro.network','wss://relay.sigit.io','wss://relay02.lnfi.network','wss://schnorr.me','wss://social.amanah.eblessing.co','wss://staging.yabu.me','wss://strfry.shock.network','wss://top.testrelay.top','wss://yabu.me/v2'];
let shareFallbackArtifact=null,incomingShareQueue=[],incomingShareRecordId=null,incomingShareBusy=false,p2pRoom=null,p2pRoomActions=null,p2pPeerId=null,p2pSessionItems=new Map(),p2pManifest=null,p2pReceived=new Map(),p2pTimeout=null,p2pRelayWatchTimer=null,p2pActiveRelayUrls=[],p2pRelaySettingsReturnView='p2pStartView',p2pCameraStream=null,p2pScannerFrame=0,p2pViewBeforeScanner='p2pReceiveCodeView';

function humanBytes(bytes){const value=Number(bytes)||0;if(value<1024)return value+' B';if(value<1024*1024)return(value/1024).toLocaleString(appLocale(),{maximumFractionDigits:1})+' KB';return(value/(1024*1024)).toLocaleString(appLocale(),{maximumFractionDigits:1})+' MB'}
function artifactFile(artifact){return new File([artifact.blob],artifact.fileName,{type:artifact.blob.type||'application/octet-stream',lastModified:Date.now()})}
function canNativeShareFile(fileName,type,navigation=navigator,secure=globalThis.isSecureContext){if(!secure||typeof File==='undefined'||typeof navigation?.share!=='function'||typeof navigation?.canShare!=='function')return false;try{return navigation.canShare({files:[new File([''],fileName,{type})]})===true}catch(error){return false}}
function generatedShareProbe(){const format=$('exportFormat')?.value||'pdf',scope=$('exportScope')?.value||'project';if(format==='pdf')return['chiccanva.pdf','application/pdf'];if(scope==='project'&&(state.pages?.custom?.length||0)>1)return['chiccanva-pages.zip','application/zip'];return format==='jpg'?['chiccanva.jpg','image/jpeg']:['chiccanva.png','image/png']}
function syncFileShareAvailability(){const generated=generatedShareProbe(),jsonSupported=canNativeShareFile('chiccanva.json','application/json');$('shareGeneratedFileBtn')?.classList.toggle('hidden',!canNativeShareFile(generated[0],generated[1]));$('shareProjectJsonBtn')?.classList.toggle('hidden',!jsonSupported);$('sharePromptLibraryBtn')?.classList.toggle('hidden',!jsonSupported)}
function openShareFallback(artifact){shareFallbackArtifact=artifact;$('shareFallbackInfo').textContent=t('«'+artifact.fileName+'» è pronto, ma questo browser non può inviarlo tramite il menu di sistema.');$('shareFallbackDialog').showModal()}
async function shareArtifact(artifact,title){const file=artifactFile(artifact);if(!navigator.share||!navigator.canShare?.({files:[file]})){openShareFallback(artifact);return false}try{await navigator.share({files:[file],title:title||artifact.fileName});return true}catch(error){if(error?.name==='AbortError')return false;console.error(error);openShareFallback(artifact);return false}}
async function shareGeneratedArtifact(){const button=$('shareGeneratedFileBtn'),status=$('projectStatus');button.disabled=true;try{const artifact=await buildUnifiedExportArtifact(message=>status.textContent=message);await shareArtifact(artifact,t('File esportato da chicCanva'));status.textContent=artifact.description}catch(error){console.error(error);status.textContent=t('Condivisione non riuscita: '+(error.message||error))}finally{button.disabled=false}}
async function shareProjectArtifact(){const button=$('shareProjectJsonBtn'),record=activeProject();if(!record)return;button.disabled=true;try{commitHistory();storeActiveDocument();const artifact=projectExportArtifact(record);if(await shareArtifact(artifact,t('Progetto chicCanva')))markProjectExported(record)}finally{button.disabled=false}}
async function sharePromptLibraryArtifact(){const button=$('sharePromptLibraryBtn');button.disabled=true;try{await loadPromptLibrary();await shareArtifact(promptLibraryExportArtifact(),t('Prompt Library chicCanva'))}finally{button.disabled=false}}

function shareInboxDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(SHARE_INBOX_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(SHARE_INBOX_STORE))request.result.createObjectStore(SHARE_INBOX_STORE,{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function shareInboxRecord(id,remove=false){const db=await shareInboxDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(SHARE_INBOX_STORE,remove?'readwrite':'readonly'),store=tx.objectStore(SHARE_INBOX_STORE),request=remove?store.delete(id):store.get(id);tx.oncomplete=()=>resolve(request.result);tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
function classifyIncomingFile(file){const name=String(file.name||''),type=String(file.type||'').toLowerCase();if(type==='application/pdf'||/\.pdf$/i.test(name))return'pdf';if(type.startsWith('image/')||/\.(png|jpe?g|webp|gif|bmp|svg)$/i.test(name))return'image';if(type==='application/json'||/\.json$/i.test(name))return'json';return'unsupported'}
async function inspectIncomingItem(item){if(item.kind!=='json')return item.kind;try{const payload=JSON.parse(await item.file.text());item.payload=payload;if(payload?.type==='chicCanva-prompt-library'||Array.isArray(payload?.prompts)||Array.isArray(payload)){normalizePromptLibraryPayload(payload);return item.kind='prompt'}if(payload?.workspace||payload?.version===7){if(payload.workspace){if(!Array.isArray(payload.workspace.projects)||!payload.workspace.projects.length)throw new Error(t('Workspace vuoto'));payload.workspace.projects.forEach(record=>normalizeCustomProject(record.payload))}else normalizeCustomProject(payload);return item.kind='project'}}catch(error){item.inspectError=error.message}return item.kind='unsupported'}
function incomingQuestion(kind){return{pdf:'Vuoi importare questo PDF come immagini?',project:'Vuoi importare e aprire questo progetto?',prompt:'Vuoi importare questa Prompt Library?',image:'Dove vuoi inserire questa immagine?',unsupported:'Questo formato non è supportato.'}[kind]||'Questo formato non è supportato.'}
async function showNextIncomingShare(){if(incomingShareBusy)return;if(!incomingShareQueue.length){await finishIncomingShare();return}incomingShareBusy=true;const item=incomingShareQueue[0];await inspectIncomingItem(item);$('incomingShareName').textContent=item.file.name||t('File senza nome');$('incomingShareMeta').textContent=(item.file.type||t('Tipo non dichiarato'))+' · '+humanBytes(item.file.size);$('incomingShareCounter').textContent=incomingShareQueue.length>1?t('1 di '+incomingShareQueue.length):'';$('incomingShareQuestion').textContent=t(incomingQuestion(item.kind))+(item.inspectError?' '+t(item.inspectError):'');$('incomingImageDestination').classList.toggle('hidden',item.kind!=='image');$('incomingShareConfirm').classList.toggle('hidden',item.kind==='unsupported');$('incomingShareConfirm').textContent=t(item.kind==='pdf'?'Apri opzioni PDF':item.kind==='prompt'?'Scegli modalità':item.kind==='image'?'Importa immagine':'Importa progetto');$('incomingShareCancelAll').classList.toggle('hidden',incomingShareQueue.length<2);$('incomingShareStatus').textContent='';$('incomingShareDialog').showModal();incomingShareBusy=false}
async function finishIncomingShare(){if(incomingShareRecordId)await shareInboxRecord(incomingShareRecordId,true).catch(()=>{});incomingShareRecordId=null;const url=new URL(location.href);if(url.searchParams.has('shareTarget')){url.searchParams.delete('shareTarget');history.replaceState(null,'',url.pathname+(url.search?url.search:'')+url.hash)}if($('incomingShareDialog').open)$('incomingShareDialog').close()}
async function importSharedProjectPayload(payload,fileName){const records=payload.workspace?.projects;if(records){for(const source of records){const copy=cloneData(source.payload);if(!preferences.history)delete copy.history;await addProject(copy,source.name)}}else{const copy=cloneData(payload);if(!preferences.history)delete copy.history;await addProject(copy,payload.name||String(fileName||'Progetto').replace(/\.json$/i,''))}}
async function importIncomingImage(file,destination){if(destination==='current'){await handleImageUpload(file);return}if(destination==='project'){const name=String(file.name||localizedProjectName(projectSerial)).replace(/\.[^.]+$/,'').slice(0,100),payload=blankProjectPayload(name);await addProject(payload,name);await handleImageUpload(file);return}saveActivePage();const index=state.pageIndex.custom,current=state.pages.custom[index],page=makePage(localizedPageName(state.pages.custom.length+1),current?.widthMm||210,current?.heightMm||297);state.pages.custom.splice(index+1,0,page);state.pageIndex.custom=index+1;await loadPage(page);await handleImageUpload(file);storeActiveDocument();scheduleAutosave()}
async function confirmIncomingShare(){const item=incomingShareQueue[0];if(!item)return;const button=$('incomingShareConfirm');button.disabled=true;$('incomingShareStatus').textContent=t('Preparazione…');try{if(item.kind==='pdf'){$('incomingShareDialog').close();await preparePdfImport(item.file);if($('pdfImportDialog').open)await new Promise(resolve=>$('pdfImportDialog').addEventListener('close',resolve,{once:true}))}else if(item.kind==='project'){await importSharedProjectPayload(item.payload,item.file.name);$('incomingShareDialog').close()}else if(item.kind==='prompt'){$('incomingShareDialog').close();await requestPromptLibraryImport(item.payload,item.file.name)}else if(item.kind==='image'){const destination=document.querySelector('input[name="incomingImageDestination"]:checked').value;await importIncomingImage(item.file,destination);$('incomingShareDialog').close()}incomingShareQueue.shift();await showNextIncomingShare()}catch(error){console.error(error);$('incomingShareStatus').textContent=t('Importazione non riuscita: '+(error.message||error));if(!$('incomingShareDialog').open)$('incomingShareDialog').showModal()}finally{button.disabled=false}}
async function skipIncomingShare(all=false){if($('incomingShareDialog').open)$('incomingShareDialog').close();if(all)incomingShareQueue=[];else incomingShareQueue.shift();await showNextIncomingShare()}
async function processShareTarget(){const url=new URL(location.href),id=url.searchParams.get('shareTarget');if(!id)return;try{const record=await shareInboxRecord(id);if(!record?.files?.length){incomingShareQueue=[{file:new File([],'',{type:''}),kind:'unsupported',inspectError:t('Il file condiviso non è più disponibile.')}]}else incomingShareQueue=record.files.map(source=>{const file=source.blob instanceof File?source.blob:new File([source.blob],source.name||'file',{type:source.type||source.blob?.type||'',lastModified:source.lastModified||Date.now()});return{file,kind:classifyIncomingFile(file)}});incomingShareRecordId=id;await showNextIncomingShare()}catch(error){console.error(error);incomingShareQueue=[{file:new File([],t('File condiviso'),{type:''}),kind:'unsupported',inspectError:error.message}];incomingShareRecordId=id;await showNextIncomingShare()}}

const P2P_ALPHABET='23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
function p2pCodeChecksum(body){let value=0;for(const char of body)value=(value*33+P2P_ALPHABET.indexOf(char)+1)%1024;return P2P_ALPHABET[(value>>5)&31]+P2P_ALPHABET[value&31]}
function createP2pCode(){const bytes=crypto.getRandomValues(new Uint8Array(10)),body=[...bytes].map(value=>P2P_ALPHABET[value%P2P_ALPHABET.length]).join('');return(body+p2pCodeChecksum(body)).replace(/(.{4})(?=.)/g,'$1-')}
function normalizeP2pCode(value){return String(value||'').toUpperCase().replace(/[^2-9A-HJ-NP-Z]/g,'').slice(0,12)}
function displayP2pCode(value){return normalizeP2pCode(value).replace(/(.{4})(?=.)/g,'$1-')}
function validateP2pCode(value){const compact=normalizeP2pCode(value);return compact.length===12&&p2pCodeChecksum(compact.slice(0,10))===compact.slice(10)}
function normalizeP2pRelayUrl(value){const raw=String(value||'').trim();if(!raw)return'';let url;try{url=new URL(raw)}catch(error){throw new Error(t('Inserisci un indirizzo relay valido che inizi con wss://'))}if(url.protocol!=='wss:'||url.username||url.password)throw new Error(t('Inserisci un indirizzo relay valido che inizi con wss://'));url.hash='';return url.href.replace(/\/$/,'')}
function storedP2pRelay(){try{return normalizeP2pRelayUrl(localStorage.getItem(P2P_CUSTOM_RELAY_KEY)||'')}catch(error){return''}}
function selectP2pRelays(hash,count=5){const selected=[],used=new Set();for(let cursor=0;selected.length<Math.min(count,P2P_RELAY_POOL.length)&&cursor<hash.length*4;cursor++){const index=((hash[cursor%hash.length]<<8)|hash[(cursor+11)%hash.length])%P2P_RELAY_POOL.length,url=P2P_RELAY_POOL[index];if(!used.has(url)){used.add(url);selected.push(url)}}for(const url of P2P_RELAY_POOL){if(selected.length>=count)break;if(!used.has(url)){used.add(url);selected.push(url)}}return selected}
async function p2pRoomCredentials(code){const compact=normalizeP2pCode(code),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('chicCanva:'+compact))),hex=[...hash].map(value=>value.toString(16).padStart(2,'0')).join('');return{roomId:'cc-'+hex.slice(0,24),password:hex.slice(24),relayUrls:selectP2pRelays(hash)}}
function p2pJoinConfig(credentials){const custom=storedP2pRelay(),urls=[custom,...credentials.relayUrls].filter((url,index,list)=>url&&list.indexOf(url)===index);return{appId:P2P_APP_ID,password:credentials.password,relayConfig:{urls,warnOnRelayFailure:true}}}
function p2pSetSignalingError(message=''){$('p2pSignalingError').classList.toggle('hidden',!message);$('p2pSignalingErrorText').textContent=message?t(message):''}
function p2pRelaySockets(){try{return Object.entries(ChicTransferVendor.getRelaySockets?.()||{}).filter(([url])=>!p2pActiveRelayUrls.length||p2pActiveRelayUrls.includes(url)).map(([,value])=>value?.socket||value).filter(Boolean)}catch(error){return[]}}
function p2pStartRelayWatch(mode){clearInterval(p2pRelayWatchTimer);p2pSetSignalingError();const status=$(mode==='send'?'p2pSendStatus':'p2pReceiveStatus'),deadline=Date.now()+12000;status.textContent=t('Connessione ai relay di signaling…');const inspect=()=>{if(!p2pRoom){clearInterval(p2pRelayWatchTimer);p2pRelayWatchTimer=null;return}const sockets=p2pRelaySockets(),open=sockets.filter(socket=>socket.readyState===WebSocket.OPEN).length;if(open){if(!p2pPeerId)status.textContent=t(mode==='send'?'Relay collegati · in attesa del destinatario…':'Relay collegati · ricerca del dispositivo che invia…');p2pSetSignalingError();return}if(Date.now()>=deadline){clearInterval(p2pRelayWatchTimer);p2pRelayWatchTimer=null;const message='Nessun relay di signaling è raggiungibile. Controlla la rete oppure configura un relay personalizzato.';status.textContent=t(message);p2pSetSignalingError(message)}};inspect();p2pRelayWatchTimer=setInterval(inspect,500)}
function p2pStopRelayWatch(){clearInterval(p2pRelayWatchTimer);p2pRelayWatchTimer=null}
function p2pJoinError(mode,details){const reason=details?.error||details?.message||String(details||t('errore')),message=t('Connessione WebRTC non riuscita: '+reason),status=$(mode==='send'?'p2pSendStatus':'p2pReceiveStatus');status.textContent=message;p2pSetSignalingError(message)}
function openP2pRelaySettings(){const visible=[...$('p2pTransferDialog').querySelectorAll('.p2p-view')].find(view=>!view.classList.contains('hidden'));p2pRelaySettingsReturnView=visible?.id==='p2pSendSessionView'?'p2pSendSetupView':visible?.id||'p2pStartView';$('p2pCustomRelayUrl').value=storedP2pRelay();$('p2pRelaySettingsStatus').textContent='';p2pSetView('p2pRelaySettingsView')}
async function saveP2pRelay(){const input=$('p2pCustomRelayUrl'),status=$('p2pRelaySettingsStatus');try{const relay=normalizeP2pRelayUrl(input.value);if(!relay)throw new Error(t('Inserisci un indirizzo relay valido che inizi con wss://'));localStorage.setItem(P2P_CUSTOM_RELAY_KEY,relay);input.value=relay;if(p2pRoom)await stopP2pSession(false);p2pSetSignalingError();const message=t('Relay personalizzato salvato. Ripeti la connessione per applicarlo.');status.textContent=message;p2pSetView(p2pRelaySettingsReturnView);toast(message)}catch(error){status.textContent=error.message}}
async function removeP2pRelay(){try{localStorage.removeItem(P2P_CUSTOM_RELAY_KEY)}catch(error){}$('p2pCustomRelayUrl').value='';if(p2pRoom)await stopP2pSession(false);p2pSetSignalingError();const message=t('Relay personalizzato rimosso. Verranno usati i relay interni.');$('p2pRelaySettingsStatus').textContent=message;p2pSetView(p2pRelaySettingsReturnView);toast(message)}
async function sha256Hex(bytes){const source=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',source));return[...hash].map(value=>value.toString(16).padStart(2,'0')).join('')}
function p2pSetView(id){for(const view of $('p2pTransferDialog').querySelectorAll('.p2p-view'))view.classList.toggle('hidden',view.id!==id)}
function p2pTouchTimeout(){clearTimeout(p2pTimeout);p2pTimeout=setTimeout(()=>{if(p2pRoom){$('p2pSendStatus').textContent=t('Sessione scaduta per inattività.');$('p2pReceiveStatus').textContent=t('Sessione scaduta per inattività.');stopP2pSession(false)}},5*60*1000)}
async function stopP2pSession(showStart=true){clearTimeout(p2pTimeout);p2pTimeout=null;p2pStopRelayWatch();stopP2pScanner();const room=p2pRoom;p2pRoom=null;p2pRoomActions=null;p2pPeerId=null;p2pActiveRelayUrls=[];p2pSessionItems.clear();p2pManifest=null;p2pReceived.clear();if(room)try{await room.leave()}catch(error){}if(showStart&&$('p2pTransferDialog').open){p2pSetSignalingError();p2pSetView('p2pStartView')}}
function p2pAvailable(){return!!(globalThis.ChicTransferVendor?.joinRoom&&globalThis.ChicTransferVendor?.getRelaySockets&&globalThis.RTCPeerConnection&&crypto?.subtle)}
function qrSvg(text){const qr=ChicTransferVendor.qrcodegen.QrCode.encodeText(text,ChicTransferVendor.qrcodegen.QrCode.Ecc.MEDIUM),border=3,size=qr.size+border*2,path=[];for(let y=0;y<qr.size;y++)for(let x=0;x<qr.size;x++)if(qr.getModule(x,y))path.push('M'+(x+border)+','+(y+border)+'h1v1h-1z');return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+size+' '+size+'" role="img" aria-label="QR"><rect width="100%" height="100%" fill="#fff"/><path d="'+path.join('')+'" fill="#102f2a"/></svg>'}
function p2pQrPayload(code){const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('p2p',displayP2pCode(code));return url.href}
function renderP2pSendProjects(){saveActivePage();const list=$('p2pSendProjectList');list.replaceChildren(...projects.map(record=>{const label=document.createElement('label');label.className='p2p-item';const input=document.createElement('input');input.type='checkbox';input.dataset.p2pProject=record.id;const main=document.createElement('span');main.className='p2p-item-main';main.innerHTML='<span class="p2p-item-name"></span><span class="p2p-item-meta"></span>';main.firstElementChild.textContent=record.name;main.lastElementChild.textContent=record.payload.pages?.custom?.length+' '+t('pagine');label.append(input,main);return label}))}
async function p2pBuildSendItems(){storeActiveDocument();const selected=[...document.querySelectorAll('[data-p2p-project]:checked')].map(input=>input.dataset.p2pProject),items=[];for(const id of selected){const record=projects.find(project=>project.id===id),artifact=projectExportArtifact(record),bytes=new Uint8Array(await artifact.blob.arrayBuffer());if(bytes.length>P2P_MAX_ITEM_BYTES)throw new Error(t('Il progetto «'+record.name+'» supera il limite di '+humanBytes(P2P_MAX_ITEM_BYTES)));items.push({id:uid('transfer'),type:'project',name:record.name,fileName:artifact.fileName,bytes,sha256:await sha256Hex(bytes)})}if($('p2pSendPromptLibrary').checked){await loadPromptLibrary();const artifact=promptLibraryExportArtifact(),bytes=new Uint8Array(await artifact.blob.arrayBuffer());if(bytes.length>P2P_MAX_ITEM_BYTES)throw new Error(t('La Prompt Library supera il limite consentito'));items.push({id:uid('transfer'),type:'prompt-library',name:'Prompt Library',fileName:artifact.fileName,bytes,sha256:await sha256Hex(bytes)})}if(!items.length)throw new Error(t('Seleziona almeno un progetto o la Prompt Library'));const total=items.reduce((sum,item)=>sum+item.bytes.length,0);if(total>P2P_MAX_TOTAL_BYTES)throw new Error(t('Il trasferimento supera il limite complessivo di '+humanBytes(P2P_MAX_TOTAL_BYTES)));return items}
function p2pManifestFor(items){return{protocol:P2P_PROTOCOL,transferId:uid('transfer'),createdAt:new Date().toISOString(),items:items.map(({id,type,name,fileName,bytes,sha256})=>({id,type,name,fileName,size:bytes.length,sha256}))}}
function validateP2pManifest(manifest){if(manifest?.protocol!==P2P_PROTOCOL||!Array.isArray(manifest.items)||!manifest.items.length||manifest.items.length>100)throw new Error(t('Manifesto di trasferimento non valido'));let total=0;for(const item of manifest.items){if(!item?.id||!['project','prompt-library'].includes(item.type)||!Number.isFinite(item.size)||item.size<0||item.size>P2P_MAX_ITEM_BYTES||!/^[a-f0-9]{64}$/i.test(item.sha256))throw new Error(t('Elemento di trasferimento non valido'));total+=item.size}if(total>P2P_MAX_TOTAL_BYTES)throw new Error(t('Trasferimento troppo grande'));return manifest}
function p2pActions(room){
 const manifest=room.makeAction('manifest'),request=room.makeAction('request'),payload=room.makeAction('payload'),done=room.makeAction('done'),errorAction=room.makeAction('error');
 const send=(action)=>(data,peerId,metadata,onProgress)=>action.send(data,{target:peerId,metadata,onProgress:onProgress?(percent)=>onProgress(percent):undefined});
 const receive=(action)=>(handler)=>{action.onMessage=(data,{peerId,metadata})=>handler(data,peerId,metadata)};
 return{sendManifest:send(manifest),getManifest:receive(manifest),sendRequest:send(request),getRequest:receive(request),sendPayload:send(payload),getPayload:receive(payload),payloadProgress:handler=>{payload.onReceiveProgress=(percent,{peerId,metadata})=>handler(percent,peerId,metadata)},sendDone:send(done),getDone:receive(done),sendError:send(errorAction),getError:receive(errorAction)}
}
async function beginP2pSend(){if(!p2pAvailable())throw new Error(t('WebRTC o Trystero non sono disponibili in questo browser'));const button=$('p2pCreateSession');button.disabled=true;try{await stopP2pSession(false);const items=await p2pBuildSendItems(),code=createP2pCode(),credentials=await p2pRoomCredentials(code),config=p2pJoinConfig(credentials),room=ChicTransferVendor.joinRoom(config,credentials.roomId,{onJoinError:details=>p2pJoinError('send',details)}),actions=p2pActions(room),manifest=p2pManifestFor(items);p2pRoom=room;p2pRoomActions=actions;p2pPeerId=null;p2pActiveRelayUrls=[...config.relayConfig.urls];p2pSessionItems=new Map(items.map(item=>[item.id,item]));$('p2pSessionCode').textContent=displayP2pCode(code);$('p2pQrCode').innerHTML=qrSvg(p2pQrPayload(code));$('p2pSendProgress').value=0;p2pSetView('p2pSendSessionView');p2pStartRelayWatch('send');room.onPeerJoin=peerId=>{if(p2pPeerId&&p2pPeerId!==peerId)return;p2pStopRelayWatch();p2pSetSignalingError();p2pPeerId=peerId;$('p2pSendStatus').textContent=t('Destinatario connesso · invio elenco…');actions.sendManifest(manifest,peerId).catch(error=>$('p2pSendStatus').textContent=error.message);p2pTouchTimeout()};room.onPeerLeave=peerId=>{if(peerId===p2pPeerId){p2pPeerId=null;$('p2pSendStatus').textContent=t('Destinatario disconnesso.')}};actions.getRequest(async(request,peerId)=>{try{if(peerId!==p2pPeerId||!Array.isArray(request?.ids))return;const requested=request.ids.map(id=>p2pSessionItems.get(id)).filter(Boolean),total=requested.reduce((sum,item)=>sum+item.bytes.length,0);let completed=0;for(const item of requested){await actions.sendPayload(item.bytes,peerId,{id:item.id},percent=>{$('p2pSendProgress').value=total?(completed+item.bytes.length*percent)/total:percent;$('p2pSendStatus').textContent=t('Invio '+item.name+' · '+Math.round(percent*100)+'%');p2pTouchTimeout()});completed+=item.bytes.length}$('p2pSendProgress').value=1;await actions.sendDone({ids:requested.map(item=>item.id)},peerId);$('p2pSendStatus').textContent=t('Trasferimento completato.')}catch(error){console.error(error);actions.sendError({message:error.message},peerId).catch(()=>{});$('p2pSendStatus').textContent=t('Invio non riuscito: '+error.message)}});actions.getError(error=>$('p2pSendStatus').textContent=t('Destinatario: '+(error?.message||t('errore'))));p2pTouchTimeout()}finally{button.disabled=false}}
function renderP2pReceiveManifest(manifest){const list=$('p2pReceiveItemList');list.replaceChildren(...manifest.items.map(item=>{const label=document.createElement('label');label.className='p2p-item';const input=document.createElement('input');input.type='checkbox';input.checked=true;input.dataset.p2pReceiveItem=item.id;input.dataset.p2pType=item.type;const main=document.createElement('span');main.className='p2p-item-main';const name=document.createElement('span');name.className='p2p-item-name';name.textContent=item.name;const meta=document.createElement('span');meta.className='p2p-item-meta';meta.textContent=item.type==='project'?t('Progetto chicCanva'):'Prompt Library';main.append(name,meta);const size=document.createElement('span');size.className='p2p-item-size';size.textContent=humanBytes(item.size);label.append(input,main,size);input.onchange=syncP2pReceiveLibraryOptions;return label}));syncP2pReceiveLibraryOptions();$('p2pReceiveProgress').value=0;$('p2pImportStatus').textContent='';p2pSetView('p2pReceiveItemsView')}
function syncP2pReceiveLibraryOptions(){$('p2pReceiveLibraryOptions').classList.toggle('hidden',!document.querySelector('[data-p2p-receive-item][data-p2p-type="prompt-library"]:checked'));$('p2pReceiveReplaceNames').closest('label').classList.toggle('hidden',$('p2pReceiveLibraryMode').value!=='append')}
async function beginP2pReceive(code){if(!p2pAvailable())throw new Error(t('WebRTC o Trystero non sono disponibili in questo browser'));if(!validateP2pCode(code))throw new Error(t('Il codice non è valido'));await stopP2pSession(false);const credentials=await p2pRoomCredentials(code),config=p2pJoinConfig(credentials),room=ChicTransferVendor.joinRoom(config,credentials.roomId,{onJoinError:details=>p2pJoinError('receive',details)}),actions=p2pActions(room);p2pRoom=room;p2pRoomActions=actions;p2pPeerId=null;p2pActiveRelayUrls=[...config.relayConfig.urls];p2pReceived.clear();p2pStartRelayWatch('receive');room.onPeerJoin=peerId=>{p2pStopRelayWatch();p2pSetSignalingError();if(!p2pPeerId)p2pPeerId=peerId;$('p2pReceiveStatus').textContent=t('Dispositivo trovato · attendo l’elenco…');p2pTouchTimeout()};room.onPeerLeave=peerId=>{if(peerId===p2pPeerId){p2pPeerId=null;$('p2pReceiveStatus').textContent=t('Dispositivo disconnesso.')}};actions.getManifest((manifest,peerId)=>{try{if(p2pPeerId&&peerId!==p2pPeerId)return;p2pPeerId=peerId;p2pManifest=validateP2pManifest(manifest);renderP2pReceiveManifest(p2pManifest);p2pTouchTimeout()}catch(error){$('p2pReceiveStatus').textContent=error.message}});actions.payloadProgress((percent,peerId,metadata)=>{const item=p2pManifest?.items.find(value=>value.id===metadata?.id);$('p2pReceiveProgress').value=percent;$('p2pImportStatus').textContent=t('Ricezione '+(item?.name||t('file'))+' · '+Math.round(percent*100)+'%');p2pTouchTimeout()});actions.getPayload((data,peerId,metadata)=>{if(peerId!==p2pPeerId||!metadata?.id)return;p2pReceived.set(metadata.id,data instanceof Uint8Array?data:new Uint8Array(data))});actions.getDone(async message=>{try{await completeP2pReceive(message?.ids||[])}catch(error){console.error(error);$('p2pImportStatus').textContent=t('Importazione non riuscita: '+error.message)}});actions.getError(error=>$('p2pImportStatus').textContent=t('Invio non riuscito: '+(error?.message||t('errore'))));p2pTouchTimeout()}
function importedProjectName(source){const suffix=t('Importato'),base=String(source||localizedProjectName(projectSerial)).replace(/\s+\((?:Imported|Importato)(?: \d+)?\)$/i,'').trim(),names=new Set(projects.map(project=>project.name.toLocaleLowerCase(appLocale())));let candidate=base+' ('+suffix+')',number=2;while(names.has(candidate.toLocaleLowerCase(appLocale())))candidate=base+' ('+suffix+' '+number+++')';return candidate.slice(0,100)}
async function completeP2pReceive(ids){const selected=ids.map(id=>p2pManifest.items.find(item=>item.id===id)).filter(Boolean);try{for(const item of selected){const bytes=p2pReceived.get(item.id);if(!bytes||bytes.length!==item.size)throw new Error(t('Il file «'+item.name+'» è incompleto'));if(await sha256Hex(bytes)!==item.sha256)throw new Error(t('Verifica non riuscita per «'+item.name+'»'))}for(const item of selected){const payload=JSON.parse(new TextDecoder().decode(p2pReceived.get(item.id)));if(item.type==='project'){normalizeCustomProject(payload);const name=importedProjectName(item.name);payload.name=name;await addProject(payload,name)}else{const mode=$('p2pReceiveLibraryMode').value;await applyPromptLibraryImport(payload,{mode,replaceSameName:mode==='append'&&$('p2pReceiveReplaceNames').checked})}}$('p2pReceiveProgress').value=1;$('p2pImportStatus').textContent=t(selected.length+' '+(selected.length===1?'elemento importato.':'elementi importati.'));toast($('p2pImportStatus').textContent);await stopP2pSession(false)}finally{$('p2pReceiveSelected').disabled=false}}
async function requestP2pSelected(){if(!p2pRoom||!p2pRoomActions||!p2pPeerId||!p2pManifest)return;const ids=[...document.querySelectorAll('[data-p2p-receive-item]:checked')].map(input=>input.dataset.p2pReceiveItem);if(!ids.length){$('p2pImportStatus').textContent=t('Seleziona almeno un elemento.');return}$('p2pReceiveSelected').disabled=true;p2pReceived.clear();$('p2pImportStatus').textContent=t('Richiesta dei file…');try{await p2pRoomActions.sendRequest({ids},p2pPeerId);p2pTouchTimeout()}catch(error){$('p2pImportStatus').textContent=error.message;$('p2pReceiveSelected').disabled=false}}
function decodeP2pQrValue(value){try{const url=new URL(value);return url.searchParams.get('p2p')||url.hash.match(/p2p=([^&]+)/)?.[1]||value}catch(error){return value}}
function stopP2pScanner(){cancelAnimationFrame(p2pScannerFrame);p2pScannerFrame=0;if(p2pCameraStream){for(const track of p2pCameraStream.getTracks())track.stop();p2pCameraStream=null}$('p2pScannerVideo').srcObject=null}
async function scanP2pFrame(){if(!p2pCameraStream)return;const video=$('p2pScannerVideo');if(video.readyState>=2){const surface=document.createElement('canvas'),width=Math.min(960,video.videoWidth||640),height=Math.round(width*(video.videoHeight||480)/(video.videoWidth||640));surface.width=width;surface.height=height;const context=surface.getContext('2d',{willReadFrequently:true});context.drawImage(video,0,0,width,height);let value='';try{if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['qr_code']}),results=await detector.detect(surface);value=results[0]?.rawValue||''}else{const image=context.getImageData(0,0,width,height),result=ChicTransferVendor.jsQR(image.data,width,height,{inversionAttempts:'attemptBoth'});value=result?.data||''}}catch(error){}surface.width=surface.height=1;if(value){const code=decodeP2pQrValue(value);if(validateP2pCode(code)){stopP2pScanner();$('p2pReceiveCode').value=displayP2pCode(code);p2pSetView('p2pReceiveCodeView');$('p2pReceiveStatus').textContent=t('QR letto. Premi Connetti per continuare.');return}}}p2pScannerFrame=requestAnimationFrame(()=>setTimeout(scanP2pFrame,90))}
async function startP2pScanner(){if(!navigator.mediaDevices?.getUserMedia)throw new Error(t('La fotocamera richiede HTTPS e un browser compatibile'));p2pViewBeforeScanner='p2pReceiveCodeView';p2pSetView('p2pScannerView');$('p2pScannerStatus').textContent=t('Richiesta accesso alla fotocamera…');try{p2pCameraStream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});const video=$('p2pScannerVideo');video.srcObject=p2pCameraStream;await video.play();$('p2pScannerStatus').textContent=t('Inquadra il QR mostrato dall’altro dispositivo.');scanP2pFrame()}catch(error){stopP2pScanner();p2pSetView(p2pViewBeforeScanner);throw error}}
function openP2pDialog(){if(!p2pAvailable()){toast(t('Condivisione P2P non disponibile in questo browser'));return}renderP2pSendProjects();$('p2pSendPromptLibrary').checked=false;$('p2pReceiveCode').value='';$('p2pCustomRelayUrl').value=storedP2pRelay();p2pSetSignalingError();p2pSetView('p2pStartView');$('p2pTransferDialog').showModal()}
function bindFileSharing(){
 $('shareGeneratedFileBtn').onclick=shareGeneratedArtifact;$('shareProjectJsonBtn').onclick=shareProjectArtifact;$('sharePromptLibraryBtn').onclick=sharePromptLibraryArtifact;$('shareFallbackDownload').onclick=()=>{if(shareFallbackArtifact)download(shareFallbackArtifact.fileName,shareFallbackArtifact.blob);shareFallbackArtifact=null;$('shareFallbackDialog').close()};$('shareFallbackCancel').onclick=()=>{shareFallbackArtifact=null;$('shareFallbackDialog').close()};$('shareFallbackDialog').oncancel=()=>shareFallbackArtifact=null;
 $('exportFormat')?.addEventListener('change',syncFileShareAvailability);$('exportScope')?.addEventListener('change',syncFileShareAvailability);syncFileShareAvailability();
 $('incomingShareConfirm').onclick=confirmIncomingShare;$('incomingShareSkip').onclick=()=>skipIncomingShare(false);$('incomingShareCancelAll').onclick=()=>skipIncomingShare(true);$('incomingShareClose').onclick=()=>skipIncomingShare(true);$('incomingShareDialog').oncancel=event=>{event.preventDefault();skipIncomingShare(true)};
 $('openP2pTransferBtn').onclick=openP2pDialog;$('closeP2pTransferBtn').onclick=async()=>{await stopP2pSession(false);$('p2pTransferDialog').close()};$('p2pTransferDialog').oncancel=event=>{event.preventDefault();stopP2pSession(false).finally(()=>$('p2pTransferDialog').close())};$('p2pChooseSend').onclick=()=>{renderP2pSendProjects();p2pSetView('p2pSendSetupView')};$('p2pChooseReceive').onclick=()=>p2pSetView('p2pReceiveCodeView');document.querySelectorAll('[data-p2p-back]').forEach(button=>button.onclick=()=>p2pSetView('p2pStartView'));document.querySelectorAll('[data-p2p-stop]').forEach(button=>button.onclick=()=>stopP2pSession(true));$('p2pSelectCurrent').onclick=()=>document.querySelectorAll('[data-p2p-project]').forEach(input=>input.checked=input.dataset.p2pProject===activeProjectId);$('p2pSelectAll').onclick=()=>document.querySelectorAll('[data-p2p-project]').forEach(input=>input.checked=true);$('p2pCreateSession').onclick=()=>beginP2pSend().catch(error=>$('p2pSendStatus').textContent=error.message);$('p2pCopyCode').onclick=()=>navigator.clipboard.writeText($('p2pSessionCode').textContent).then(()=>toast(t('Codice copiato'))).catch(()=>toast(t('Copia non riuscita')));$('p2pReceiveCode').oninput=event=>event.target.value=displayP2pCode(event.target.value);$('p2pConnect').onclick=()=>beginP2pReceive($('p2pReceiveCode').value).catch(error=>$('p2pReceiveStatus').textContent=error.message);$('p2pScanQr').onclick=()=>startP2pScanner().catch(error=>$('p2pReceiveStatus').textContent=error.message);$('p2pCloseScanner').onclick=()=>{stopP2pScanner();p2pSetView(p2pViewBeforeScanner)};$('p2pReceiveSelectAll').onclick=()=>{document.querySelectorAll('[data-p2p-receive-item]').forEach(input=>input.checked=true);syncP2pReceiveLibraryOptions()};$('p2pReceiveLibraryMode').onchange=syncP2pReceiveLibraryOptions;$('p2pReceiveSelected').onclick=requestP2pSelected;
 $('p2pOpenRelaySettings').onclick=openP2pRelaySettings;$('p2pErrorRelaySettings').onclick=openP2pRelaySettings;$('p2pCloseRelaySettings').onclick=()=>p2pSetView(p2pRelaySettingsReturnView);$('p2pSaveRelay').onclick=saveP2pRelay;$('p2pRemoveRelay').onclick=removeP2pRelay;
 window.addEventListener('pagehide',()=>{stopP2pScanner();if(p2pRoom)stopP2pSession(false)})
}
const fileSharingBaseInit=init;init=async function(){await fileSharingBaseInit();bindFileSharing();const url=new URL(location.href),p2pCode=url.searchParams.get('p2p');if(p2pCode){url.searchParams.delete('p2p');history.replaceState(null,'',url.pathname+(url.search?url.search:'')+url.hash);openP2pDialog();p2pSetView('p2pReceiveCodeView');$('p2pReceiveCode').value=displayP2pCode(p2pCode);$('p2pReceiveStatus').textContent=t('Codice ricevuto. Premi Connetti per continuare.')}await processShareTarget()};
