// Local, non-destructive image transformations and AI coloring-page setup.
function selectedEffectSource(){if(cropSession){toast('Conferma o annulla il crop prima di trasformare l’immagine');return null}const image=selectedImage(),asset=image&&state.assets[image.assetId];if(!image||!asset){toast('Seleziona un’immagine nel canvas');return null}return{image,asset}}
async function imagePixels(asset){const source=new Image();source.src=asset.dataUrl;await source.decode();const maxSide=4096,maxArea=16000000,scale=Math.min(1,maxSide/Math.max(source.naturalWidth,source.naturalHeight),Math.sqrt(maxArea/(source.naturalWidth*source.naturalHeight))),width=Math.max(1,Math.round(source.naturalWidth*scale)),height=Math.max(1,Math.round(source.naturalHeight*scale)),surface=document.createElement('canvas');surface.width=width;surface.height=height;const context=surface.getContext('2d',{willReadFrequently:true});context.drawImage(source,0,0,width,height);return{surface,context,pixels:context.getImageData(0,0,width,height),scale}}
function grayscalePixels(data,softness){const mix=clamp(Number(softness)/100,0,1),bytes=data.data;for(let i=0;i<bytes.length;i+=4){const luminance=.2126*bytes[i]+.7152*bytes[i+1]+.0722*bytes[i+2],line=luminance>=128?255:0,value=Math.round(line*(1-mix)+luminance*mix);bytes[i]=bytes[i+1]=bytes[i+2]=value}return data}
function outlinePixels(data,width,height,sensitivity){const src=new Float32Array(width*height),blur=new Float32Array(width*height),bytes=data.data;for(let i=0,p=0;i<bytes.length;i+=4,p++)src[p]=.2126*bytes[i]+.7152*bytes[i+1]+.0722*bytes[i+2];for(let y=0;y<height;y++)for(let x=0;x<width;x++){let sum=0,count=0;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const xx=x+ox,yy=y+oy;if(xx>=0&&xx<width&&yy>=0&&yy<height){sum+=src[yy*width+xx];count++}}blur[y*width+x]=sum/count}const threshold=145-clamp(Number(sensitivity),15,90)*1.15;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const at=(xx,yy)=>blur[clamp(yy,0,height-1)*width+clamp(xx,0,width-1)],gx=-at(x-1,y-1)+at(x+1,y-1)-2*at(x-1,y)+2*at(x+1,y)-at(x-1,y+1)+at(x+1,y+1),gy=-at(x-1,y-1)-2*at(x,y-1)-at(x+1,y-1)+at(x-1,y+1)+2*at(x,y+1)+at(x+1,y+1),magnitude=Math.hypot(gx,gy),edge=255-clamp((magnitude-threshold)*5,0,255),i=(y*width+x)*4,value=Math.round(edge);bytes[i]=bytes[i+1]=bytes[i+2]=value;bytes[i+3]=255}return data}
async function insertEffectCopy(source,processed,kind,meta){const dataUrl=processed.surface.toDataURL('image/png'),id=uid('asset'),pose=serializeObject(source.image),scale=processed.scale||1;state.assets[id]={id,dataUrl,originalDataUrl:dataUrl,mime:'image/png',name:(source.asset.name||'Immagine')+' · '+kind,kind:'image-effect',source:'Elaborazione locale Canvas',meta:{derivedFrom:source.asset.id,effect:kind,...meta}};updateAssetCount();const descriptor={...pose,id:uid('obj'),assetId:id,objectType:'image',left:pose.left+30,top:pose.top+30,width:pose.width*scale,height:pose.height*scale,cropX:(pose.cropX||0)*scale,cropY:(pose.cropY||0)*scale,scaleX:(pose.scaleX||1)/scale,scaleY:(pose.scaleY||1)/scale};const copy=await instantiateObject(descriptor);canvas.setActiveObject(copy);canvas.requestRenderAll();saveActivePage();return copy}
async function duplicateProcessedImage(mode){const source=selectedEffectSource();if(!source)return;const button=$(mode==='gray'?'duplicateGrayBtn':'duplicateOutlineBtn'),label=button.textContent,status=$('imageEffectStatus');button.disabled=true;button.innerHTML='<span class="spinner"></span> Elaborazione…';status.textContent='Preparazione immagine…';try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const processed=await imagePixels(source.asset);if(mode==='gray'){const softness=Number($('graySoftness').value);processed.context.putImageData(grayscalePixels(processed.pixels,softness),0,0);await insertEffectCopy(source,processed,'bianco e nero',{softness})}else{const sensitivity=Number($('outlineSensitivity').value);processed.context.putImageData(outlinePixels(processed.pixels,processed.surface.width,processed.surface.height,sensitivity),0,0);await insertEffectCopy(source,processed,'outline',{sensitivity})}status.textContent='Copia '+(mode==='gray'?'in bianco e nero':'outline')+' creata. Originale invariato.';toast('Copia elaborata inserita nel canvas')}catch(error){console.error(error);status.textContent='Trasformazione non riuscita: '+(error.message||error)}finally{button.disabled=false;button.textContent=label}}
async function prepareColoringAi(){const source=selectedEffectSource();if(!source)return;const button=$('prepareColoringAiBtn'),status=$('imageEffectStatus');button.disabled=true;status.textContent='Preparazione riferimento AI…';try{const dataUrl=source.image.toDataURL({format:'png'}),blob=await(await fetch(dataUrl)).blob();await setAiReference(new File([blob],'Riferimento dal canvas.png',{type:'image/png'}));$('aiProvider').value='openai-image-generation';$('aiProvider').dispatchEvent(new Event('change'));$('aiModel').value='gpt-image-2';$('aiQuality').value='low';$('aiStyle').value='Pagina da colorare';$('aiPrompt').value='Trasforma fedelmente il soggetto dell’immagine di riferimento in un disegno da colorare per bambini. Mantieni posa, proporzioni ed elementi riconoscibili. Usa contorni neri chiusi, puliti e ben separati, sfondo bianco, nessun colore, nessuna ombreggiatura e grandi aree facili da colorare.';syncReferenceUI();const aiJump=[...$('sidebar').querySelectorAll('.quick-jump button')].find(b=>b.textContent==='AI');aiJump?.click();$('aiCard').classList.remove('collapsed');$('aiCard').querySelector(':scope > .card-h')?.setAttribute('aria-expanded','true');$('aiPrompt').focus();status.textContent='Widget AI preparato. Controlla le impostazioni e premi Genera quando vuoi.';toast('AI preparata: la generazione non è ancora partita')}catch(error){console.error(error);status.textContent='Preparazione AI non riuscita: '+(error.message||error)}finally{button.disabled=false}}
duplicateProcessedImage=withHistory(duplicateProcessedImage);prepareColoringAi=withHistory(prepareColoringAi);
function updateImageEffectLabels(){const softness=Number($('graySoftness').value),label=softness<25?'Al tratto':softness<55?'Deciso':softness<80?'Bilanciato':'Soft';$('graySoftnessLabel').textContent=label;$('outlineSensitivityLabel').textContent=$('outlineSensitivity').value+'%'}
const baseRemoveSolidBackground=removeSolidBackground;
async function detectEdgeBackgroundColor(blob){const image=new Image(),url=URL.createObjectURL(blob);try{image.src=url;await image.decode();const scale=Math.min(1,256/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(2,Math.round(image.naturalWidth*scale)),height=Math.max(2,Math.round(image.naturalHeight*scale)),surface=document.createElement('canvas');surface.width=width;surface.height=height;const context=surface.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,width,height);const data=context.getImageData(0,0,width,height).data,buckets=new Map(),add=(x,y)=>{const i=(y*width+x)*4;if(data[i+3]<128)return;const key=(data[i]>>4)+','+(data[i+1]>>4)+','+(data[i+2]>>4),entry=buckets.get(key)||[0,0,0,0];entry[0]++;entry[1]+=data[i];entry[2]+=data[i+1];entry[3]+=data[i+2];buckets.set(key,entry)};for(let x=0;x<width;x++){add(x,0);add(x,height-1);if(height>4){add(x,1);add(x,height-2)}}for(let y=2;y<height-2;y++){add(0,y);add(width-1,y);if(width>4){add(1,y);add(width-2,y)}}const best=[...buckets.values()].sort((a,b)=>b[0]-a[0])[0];if(!best)throw new Error('Nessun colore opaco rilevato sui bordi');const hex=n=>Math.round(n/best[0]).toString(16).padStart(2,'0');return'#'+hex(best[1])+hex(best[2])+hex(best[3])}finally{URL.revokeObjectURL(url);image.src=''}}
removeSolidBackground=async function(blob){if($('bgAutoColor')?.checked){$('removeBgStatus').textContent='Rilevamento automatico del colore sui bordi…';const color=await detectEdgeBackgroundColor(blob);$('bgColor').value=color;$('bgColor').dispatchEvent(new Event('change',{bubbles:true}))}return baseRemoveSolidBackground(blob)};
let canvasColorTarget=null,canvasColorPreviousSkip=false;
const eyedropperIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 5 5 5M13 6l3-3a2 2 0 0 1 3 0l2 2a2 2 0 0 1 0 3l-3 3M14 7 5 16l-1 4 4-1 9-9"/><path d="M6 16h4"/></svg>';
function finishCanvasColorPick(cancelled=false){if(!canvasColorTarget)return;canvasColorTarget=null;canvas.skipTargetFind=canvasColorPreviousSkip;$('canvasShell').classList.remove('color-picking');document.querySelectorAll('.color-picker-button.active').forEach(button=>button.classList.remove('active'));if(cancelled)toast('Pipetta annullata')}
function beginCanvasColorPick(input,button){if(canvasColorTarget===input){finishCanvasColorPick(true);return}finishCanvasColorPick();canvasColorTarget=input;canvasColorPreviousSkip=canvas.skipTargetFind;canvas.skipTargetFind=true;$('canvasShell').classList.add('color-picking');button.classList.add('active');if(matchMedia('(max-width:720px)').matches&&state.sidebar.open)$('toggleSidebarBtn').click();toast('Pipetta attiva: tocca un punto del foglio')}
function canvasRasterPoint(event,element=canvas.lowerCanvasEl){const source=event?.touches?.[0]||event?.changedTouches?.[0]||event,rect=element.getBoundingClientRect(),scaleX=element.width/rect.width,scaleY=element.height/rect.height;return{x:clamp(Math.floor((source.clientX-rect.left)*scaleX),0,element.width-1),y:clamp(Math.floor((source.clientY-rect.top)*scaleY),0,element.height-1)}}
function sampleCanvasColor(options){if(!canvasColorTarget)return;const context=canvas.lowerCanvasEl.getContext('2d',{willReadFrequently:true}),point=canvasRasterPoint(options.e),rgba=context.getImageData(point.x,point.y,1,1).data,value='#'+[0,1,2].map(i=>(rgba[3]?rgba[i]:255).toString(16).padStart(2,'0')).join(''),target=canvasColorTarget;if(target.id==='bgColor'&&$('bgAutoColor'))$('bgAutoColor').checked=false;target.value=value;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));finishCanvasColorPick();toast('Colore campionato: '+value.toUpperCase())}
function setupCanvasColorPickers(){for(const input of document.querySelectorAll('input[type="color"]')){if(input.nextElementSibling?.classList.contains('color-picker-button'))continue;const button=document.createElement('button');button.type='button';button.className='iconbtn color-picker-button';button.innerHTML=eyedropperIcon;button.title='Pipetta · scegli un colore dal canvas';button.setAttribute('aria-label','Scegli dal canvas il colore per '+(input.title||input.id));button.onclick=()=>beginCanvasColorPick(input,button);input.insertAdjacentElement('afterend',button)}canvas.on('mouse:down',sampleCanvasColor);window.addEventListener('keydown',event=>{if(event.key==='Escape'&&canvasColorTarget)finishCanvasColorPick(true)},true)}
function syncAutomaticBackgroundColor(){const automatic=$('bgAutoColor')?.checked;$('bgColor').disabled=!!automatic;const picker=$('bgColor').nextElementSibling;if(picker?.classList.contains('color-picker-button'))picker.disabled=!!automatic}
function setupImageEffects(){$('graySoftness').oninput=updateImageEffectLabels;$('outlineSensitivity').oninput=updateImageEffectLabels;$('duplicateGrayBtn').onclick=()=>duplicateProcessedImage('gray');$('duplicateOutlineBtn').onclick=()=>duplicateProcessedImage('outline');$('prepareColoringAiBtn').onclick=prepareColoringAi;$('bgAutoColor').onchange=()=>{syncAutomaticBackgroundColor();scheduleAutosave()};setupCanvasColorPickers();syncAutomaticBackgroundColor();updateImageEffectLabels()}
const imageEffectsBindWorkspace=bindWorkspace;bindWorkspace=function(){imageEffectsBindWorkspace();setupImageEffects()};
