// PDF-to-PNG page import. PDF.js and its worker are embedded by build-workspace.py.
const PDFJS_VERSION='3.11.174',PDF_IMPORT_BASE_SCALE=1.5;
let pdfImportDocument=null,pdfImportLoadingTask=null,pdfImportFile=null,pdfImportWorkerUrl=null,pdfImportRunning=false,pdfImportCancelled=false;
function ensurePdfJs(){if(!window.pdfjsLib?.getDocument)throw new Error('Motore PDF.js non disponibile');if(!pdfImportWorkerUrl){const binary=atob(PDF_WORKER_BASE64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);pdfImportWorkerUrl=URL.createObjectURL(new Blob([bytes],{type:'text/javascript'}));pdfjsLib.GlobalWorkerOptions.workerSrc=pdfImportWorkerUrl}return pdfjsLib}
function cleanPdfProjectName(name){return (name||'PDF importato').replace(/\.pdf$/i,'').trim().slice(0,80)||'PDF importato'}
function selectedPdfPageNumbers(total,scope,page){if(scope==='single'){const value=Math.trunc(Number(page));if(value<1||value>total)throw new Error('Indica una pagina tra 1 e '+total);return[value]}return Array.from({length:total},(_,index)=>index+1)}
function pdfDestinationSize(orientation,viewport){const landscape=orientation==='landscape'||(orientation==='auto'&&viewport.width>viewport.height);return landscape?{widthMm:297,heightMm:210}:{widthMm:210,heightMm:297}}
async function closePdfImport(){if(pdfImportRunning){pdfImportCancelled=true;$('pdfImportStatus').textContent='Interruzione dopo la pagina corrente…';return}if($('pdfImportDialog').open)$('pdfImportDialog').close();try{await pdfImportDocument?.destroy?.()}catch(error){}pdfImportDocument=null;pdfImportLoadingTask=null;pdfImportFile=null;$('pdfFile').value=''}
async function preparePdfImport(file){
 if(!file)return;if(file.type&&file.type!=='application/pdf'&&!/\.pdf$/i.test(file.name)){toast('Seleziona un file PDF');return}
 const button=$('importPdfBtn'),status=$('pdfImportStatus');button.disabled=true;status.textContent='Lettura del PDF…';
 try{const lib=ensurePdfJs(),data=new Uint8Array(await file.arrayBuffer());pdfImportLoadingTask=lib.getDocument({data});pdfImportDocument=await pdfImportLoadingTask.promise;pdfImportFile=file;$('pdfImportInfo').textContent=file.name+' · '+pdfImportDocument.numPages+(pdfImportDocument.numPages===1?' pagina':' pagine');$('pdfImportPage').max=String(pdfImportDocument.numPages);$('pdfImportPage').value='1';document.querySelector('input[name="pdfImportScope"][value="all"]').checked=true;$('pdfImportPage').disabled=true;status.textContent='PDF pronto. Scegli le opzioni di importazione.';$('pdfImportDialog').showModal()}
 catch(error){console.error(error);status.textContent='PDF non leggibile: '+(error?.message||error);toast('Importazione PDF non disponibile')}
 finally{button.disabled=false;$('pdfFile').value=''}
}
async function renderPdfPageAsset(pageNumber,quality,orientation,assets){
 const pdfPage=await pdfImportDocument.getPage(pageNumber),base=pdfPage.getViewport({scale:1}),requested=PDF_IMPORT_BASE_SCALE*quality,maxScale=Math.min(requested,4096/Math.max(base.width,base.height),Math.sqrt(20000000/Math.max(1,base.width*base.height))),viewport=pdfPage.getViewport({scale:maxScale}),surface=document.createElement('canvas');surface.width=Math.max(1,Math.round(viewport.width));surface.height=Math.max(1,Math.round(viewport.height));const context=surface.getContext('2d',{alpha:false});context.fillStyle='#fff';context.fillRect(0,0,surface.width,surface.height);await pdfPage.render({canvasContext:context,viewport,intent:'print'}).promise;const dataUrl=surface.toDataURL('image/png'),assetId=uid('asset'),name=cleanPdfProjectName(pdfImportFile.name)+' · '+(appLanguage==='it'?'pagina ':'page ')+pageNumber+'.png';assets[assetId]={id:assetId,dataUrl,originalDataUrl:dataUrl,mime:'image/png',name,kind:'pdf',source:'PDF locale · PDF.js',meta:{pdfPage:pageNumber,pdfPages:pdfImportDocument.numPages,quality,pdfJsVersion:PDFJS_VERSION}};const size=pdfDestinationSize(orientation,base),pageWidth=size.widthMm*PX_PER_MM,pageHeight=size.heightMm*PX_PER_MM,scale=Math.min(pageWidth/surface.width,pageHeight/surface.height),page=makePage(localizedPageName(pageNumber)+' · '+cleanPdfProjectName(pdfImportFile.name),size.widthMm,size.heightMm);page.meta={source:'PDF importato',pdfPage:pageNumber,pdfFile:pdfImportFile.name};page.objects=[{id:uid('obj'),objectType:'image',assetId,left:pageWidth/2,top:pageHeight/2,originX:'center',originY:'center',scaleX:scale,scaleY:scale,width:surface.width,height:surface.height,angle:0,opacity:1,flipX:false,flipY:false,cropX:0,cropY:0}];surface.width=surface.height=1;pdfPage.cleanup?.();return page
}
async function confirmPdfImport(){
 if(pdfImportRunning||!pdfImportDocument)return;let numbers;try{numbers=selectedPdfPageNumbers(pdfImportDocument.numPages,document.querySelector('input[name="pdfImportScope"]:checked').value,$('pdfImportPage').value)}catch(error){$('pdfImportStatus').textContent=error.message;return}
 const destination=document.querySelector('input[name="pdfImportDestination"]:checked').value,orientation=$('pdfImportOrientation').value,quality=Number($('pdfImportQuality').value),button=$('pdfImportConfirm'),cancel=$('pdfImportCancel'),assets={},pages=[];let actionLocked=true;pdfImportRunning=true;pdfImportCancelled=false;button.disabled=true;cancel.textContent='Interrompi';actionDepth++;syncHistoryButtons();
 try{for(let index=0;index<numbers.length;index++){if(pdfImportCancelled)break;$('pdfImportStatus').textContent='Conversione pagina '+(index+1)+' / '+numbers.length+'…';pages.push(await renderPdfPageAsset(numbers[index],quality,orientation,assets))}if(pdfImportCancelled){$('pdfImportStatus').textContent='Importazione interrotta. Nessuna pagina aggiunta.';return}if(!pages.length)throw new Error('Nessuna pagina convertita');actionDepth--;actionLocked=false;syncHistoryButtons();if(destination==='current')saveActivePage();commitHistory();if(destination==='new'){const name=cleanPdfProjectName(pdfImportFile.name),payload=currentDocument(false);payload.name=name;payload.pages={whole:[],single:[],custom:pages};payload.state.pageIndex={whole:0,single:0,custom:0};payload.state.workspaceCustom=true;payload.assets=assets;await addProject(payload,name)}else{const first=state.pages.custom.length;Object.assign(state.assets,assets);state.pages.custom.push(...pages);state.pageIndex.custom=first;await loadPage(state.pages.custom[first]);commitHistory();storeActiveDocument();updateAssetCount();scheduleAutosave()}$('pdfImportStatus').textContent=pages.length+' '+(pages.length===1?'pagina importata.':'pagine importate.');toast($('pdfImportStatus').textContent);$('pdfImportDialog').close()}
 catch(error){console.error(error);$('pdfImportStatus').textContent='Importazione non riuscita: '+(error?.message||error);toast('Importazione PDF non riuscita')}
 finally{if(actionLocked)actionDepth--;syncHistoryButtons();pdfImportRunning=false;button.disabled=false;cancel.textContent='Annulla';try{await pdfImportDocument?.destroy?.()}catch(error){}pdfImportDocument=null;pdfImportLoadingTask=null;pdfImportFile=null;$('pdfFile').value=''}
}
function bindPdfImport(){$('importPdfBtn').onclick=()=>$('pdfFile').click();$('pdfFile').onchange=event=>preparePdfImport(event.target.files?.[0]);document.querySelectorAll('input[name="pdfImportScope"]').forEach(input=>input.onchange=()=>{$('pdfImportPage').disabled=document.querySelector('input[name="pdfImportScope"]:checked').value!=='single'});$('pdfImportQuality').oninput=()=>$('pdfImportQualityValue').textContent=$('pdfImportQuality').value+'×';$('pdfImportConfirm').onclick=confirmPdfImport;$('pdfImportCancel').onclick=closePdfImport;$('pdfImportDialog').oncancel=event=>{event.preventDefault();closePdfImport()}}
const pdfImportBaseInit=init;init=async function(){await pdfImportBaseInit();bindPdfImport()};
