// Workspace persistence, undo/redo and the complete emoji browser.
const MEMORY_KEY='chicCanva.autosave.v6', AUTOSAVE_DIRTY_KEY='chicCanva.autosave.pending.v7', AUTOSAVE_CURRENT='workspace-current', AUTOSAVE_PREVIOUS='workspace-previous', PREF_KEY='chicCanva.preferences.v6', BG_CACHE='chicCanva.models.imgly-1.7.0-ort-1.21.0';
let preferences={limit:30,history:false,autosave:true,model:'isnet_quint8',device:'auto'},historyEntries=[],historyCursor=-1,historyReady=false,historyRestoring=false,snapshotting=false,actionDepth=0,commitTimer=0,autosaveTimer=0,storageQueue=Promise.resolve(),memoryEpoch=0,bgCacheEpoch=0,bgWorking=false,emojiLimit=120,emojiFilterKey='',urlTarget='image',lastSavedPayload='',canvasGestureActive=false;
const cloneData=x=>JSON.parse(JSON.stringify(x));
const basePayload=projectPayload,baseSave=saveActivePage,baseSync=syncUiFromState;
const baseSelectionChanged=selectionChanged;selectionChanged=function(){if(!snapshotting)baseSelectionChanged()};
function capturePayload(){snapshotting=true;try{return basePayload()}finally{snapshotting=false}}
function readPreferences(){try{const p=JSON.parse(localStorage.getItem(PREF_KEY)||'null');if(p){preferences.limit=clamp(Number(p.limit)||30,1,100);preferences.history=!!p.history;preferences.autosave=p.autosave!==false;preferences.model=['isnet_quint8','isnet_fp16','isnet'].includes(p.model)?p.model:'isnet_quint8';preferences.device=['auto','cpu','gpu'].includes(p.device)?p.device:'auto'}}catch(e){console.warn('Preferenze non disponibili',e)}}
function writePreferences(){try{localStorage.setItem(PREF_KEY,JSON.stringify(preferences))}catch(e){memoryMessage('Preferenze non salvate: memoria del browser non disponibile.')}}
function memoryMessage(s){$('memoryStatus').textContent=s;$('settingsBtn').title=s}
function compactHistoryEntry(payload){const source=payload?.state||{},entry={state:{mode:source.mode||'custom',pageIndex:cloneData(source.pageIndex||{whole:0,single:0,custom:0}),workspaceCustom:source.workspaceCustom!==false,customCounter:Number(source.customCounter)||1},pages:cloneData(payload?.pages||{whole:[],single:[],custom:[]})};if(payload?.historyInfo)entry.historyInfo=cloneData(payload.historyInfo);return entry}
function historySnapshot(){return compactHistoryEntry(capturePayload())}
// Undo/redo follows the printable project: pages, page properties and their objects.
// Tool choices, draft text, prompts, references and UI preferences remain persistent
// project settings, but cannot create an undo step or change while travelling history.
function historySignature(payload){return JSON.stringify({pages:payload?.pages||{}})}
function syncHistoryButtons(){$('undoBtn').disabled=!historyReady||historyRestoring||actionDepth>0||historyCursor<=0;$('redoBtn').disabled=!historyReady||historyRestoring||actionDepth>0||historyCursor>=historyEntries.length-1;$('mobileUndo').disabled=$('undoBtn').disabled;$('mobileRedo').disabled=$('redoBtn').disabled;$('historyStatus').textContent=Math.max(0,historyCursor)+' / '+Math.max(0,historyEntries.length-1)}
function trimHistory(){const excess=historyEntries.length-(preferences.limit+1);if(excess>0){const front=Math.min(excess,historyCursor);historyEntries.splice(0,front);historyCursor-=front;if(historyEntries.length>preferences.limit+1)historyEntries.splice(preferences.limit+1)}syncHistoryButtons()}
function canvasTransformActive(){return canvasGestureActive||!!(canvas&&canvas._currentTransform)}
function commitHistory(){clearTimeout(commitTimer);if(canvasTransformActive()){commitTimer=setTimeout(commitHistory,250);return}if(!historyReady||historyRestoring||actionDepth||loadingPage||cropSession)return;const entry=historySnapshot(),current=historyEntries[historyCursor];if(!current||historySignature(entry)!==historySignature(current)){historyEntries.splice(historyCursor+1);historyEntries.push(entry);historyCursor=historyEntries.length-1;trimHistory();scheduleAutosave()}syncHistoryButtons()}
function scheduleCommit(){if(!historyReady||historyRestoring)return;clearTimeout(commitTimer);commitTimer=setTimeout(commitHistory,350)}
saveActivePage=function(){if(canvasTransformActive()){if(!snapshotting){scheduleCommit();scheduleAutosave()}return}baseSave();if(!snapshotting)scheduleCommit()};
function withHistory(fn){return function(...args){if(historyReady&&!actionDepth)commitHistory();actionDepth++;syncHistoryButtons();const done=()=>{actionDepth--;if(!actionDepth){scheduleCommit();syncHistoryButtons()}};try{const r=fn.apply(this,args);if(r&&typeof r.then==='function')return r.finally(done);done();return r}catch(e){done();throw e}}}
function referencedAssets(snapshots){const ids=new Set();for(const snap of snapshots)for(const pages of Object.values(snap.pages))for(const p of pages)for(const o of p.objects||[])if(o.assetId)ids.add(o.assetId);return Object.fromEntries([...ids].filter(id=>state.assets[id]).map(id=>[id,state.assets[id]]))}
function fullPayload(includeHistory=preferences.history){const p=capturePayload();p.version=6;p.state.emojiStroke=state.emojiStroke||1;if(includeHistory&&historyReady){commitHistory();p.history={version:1,limit:preferences.limit,cursor:historyCursor,entries:cloneData(historyEntries)}}p.assets=referencedAssets([{pages:p.pages},...(p.history?.entries||[])]);return p}
projectPayload=function(){return fullPayload()};
function validateProject(p){if(!p||!p.state||!p.pages||!['whole','single','custom'].every(k=>Array.isArray(p.pages[k])))throw new Error('Progetto non riconosciuto');for(const pages of Object.values(p.pages)){if(!Array.isArray(pages))throw new Error('Pagine non valide');for(const page of pages){if(!Number.isFinite(page.widthMm)||!Number.isFinite(page.heightMm)||page.widthMm<=0||page.heightMm<=0||!Array.isArray(page.objects))throw new Error('Dimensioni o oggetti non validi');for(const o of page.objects){if(o.assetId&&!p.assets?.[o.assetId])throw new Error('Asset mancante nel progetto')}}}return p}
async function restoreSnapshot(snap,assets=state.assets){if(cropSession)cancelCrop();historyRestoring=true;syncHistoryButtons();try{const s=cloneData(snap.state);for(const k of Object.keys(basePayload().state))if(k in s)state[k]=s[k];state.emojiStroke=clamp(Number(s.emojiStroke)||1,.5,3);state.pages=cloneData(snap.pages);state.assets=assets;state.mode=['whole','single','custom'].includes(state.mode)?state.mode:'whole';scaleBaseline=null;ensurePages();syncUiFromState();await loadPage(currentPageByState());updateAssetCount()}finally{historyRestoring=false;syncHistoryButtons()}}
async function travelHistory(delta){if(actionDepth||historyRestoring||loadingPage)return;if(cropSession){cancelCrop();toast('Crop annullato');return}commitHistory();const next=historyCursor+delta;if(next<0||next>=historyEntries.length)return;const old=historyCursor;historyCursor=next;try{await restoreSnapshot(historyEntries[next]);scheduleAutosave();toast(delta<0?'Modifica annullata':'Modifica ripristinata')}catch(e){historyCursor=old;toast('Ripristino non riuscito: '+e.message)}syncHistoryButtons()}
async function normalizeImportedAssets(input){const assets=cloneData(input||{});for(const asset of Object.values(assets)){if(!asset.mime?.includes('svg')&&!asset.dataUrl?.startsWith('data:image/svg+xml'))continue;for(const key of ['dataUrl','originalDataUrl']){const url=asset[key];if(!url)continue;try{const xml=new DOMParser().parseFromString(await(await fetch(url)).text(),'image/svg+xml'),root=xml.documentElement;if(xml.querySelector('parsererror'))continue;const box=(root.getAttribute('viewBox')||'0 0 72 72').split(/[ ,]+/).map(Number);if(root.hasAttribute('width')&&root.hasAttribute('height'))continue;root.setAttribute('width',String(box[2]||72));root.setAttribute('height',String(box[3]||72));root.setAttribute('xmlns','http://www.w3.org/2000/svg');asset[key]=await dataUrlFromBlob(new Blob([new XMLSerializer().serializeToString(xml)],{type:'image/svg+xml'}))}catch(e){console.warn('SVG import',e)}}}return assets}
async function adoptProject(p,withImportedHistory){validateProject(p);let imported=null;if(withImportedHistory&&p.history){const h=p.history;if(h.version!==1||!Array.isArray(h.entries)||h.entries.length>101||!Number.isInteger(h.cursor)||h.cursor<0||h.cursor>=h.entries.length)throw new Error('Storico non valido');for(const e of h.entries)validateProject({...e,assets:p.assets});if(historySignature(h.entries[h.cursor])!==historySignature(p))throw new Error('Storico non coerente con il progetto');imported={...cloneData(h),entries:h.entries.map(compactHistoryEntry)}}await restoreSnapshot(p,await normalizeImportedAssets(p.assets));if(imported){preferences.limit=clamp(Number(imported.limit)||preferences.limit,1,100);historyEntries=imported.entries;historyCursor=imported.cursor}else{historyEntries=[historySnapshot()];historyCursor=0}trimHistory();syncSettings();scheduleAutosave()}
importJsonFile=async function(file){if(bgWorking){toast('Attendi il completamento della rimozione sfondo');return}try{const p=JSON.parse(await file.text());await adoptProject(p,preferences.history);toast('Progetto importato'+(preferences.history&&p.history?' con cronologia':''))}catch(e){console.error(e);toast('Importazione non riuscita: '+e.message)}};
function dbOperation(mode,operation){return new Promise((resolve,reject)=>{const request=indexedDB.open('chicCanva-storage',1);request.onupgradeneeded=()=>request.result.createObjectStore('projects');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('projects',mode);let result;try{result=operation(tx.objectStore('projects'))}catch(e){db.close();reject(e);return}tx.oncomplete=()=>{db.close();resolve(result?.result)};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error||new Error('Salvataggio interrotto'))}}})}
// Identical original image URLs are omitted only in storage, restored when reading.
function encodeMemory(p){return JSON.stringify(p,(key,value)=>key==='created'?undefined:key==='assets'?Object.fromEntries(Object.entries(value).map(([id,a])=>{const b={...a};if(b.originalDataUrl===b.dataUrl)delete b.originalDataUrl;return[id,b]})):value)}
function decodeMemory(text){const p=JSON.parse(text);for(const a of Object.values(p.assets||{}))a.originalDataUrl??=a.dataUrl;return p}
function markAutosaveDirty(){try{localStorage.setItem(AUTOSAVE_DIRTY_KEY,new Date().toISOString())}catch(error){}}
function flushBeforeLeave(){if(!historyReady||!preferences.autosave)return true;if(actionDepth||loadingPage||historyRestoring||cropSession){markAutosaveDirty();return false}commitHistory();const payload=encodeMemory(fullPayload(true));if(payload===lastSavedPayload)return true;markAutosaveDirty();if(payload.length<1500000)try{const saved=new Date().toISOString();localStorage.setItem(MEMORY_KEY,JSON.stringify({version:2,saved,project:payload,pendingDatabase:true}));lastSavedPayload=payload;persistProject();return true}catch(error){}persistProject();return false}
function scheduleAutosave(){if(!historyReady||historyRestoring||!preferences.autosave)return;markAutosaveDirty();clearTimeout(autosaveTimer);autosaveTimer=setTimeout(persistProject,250)}
async function saveStableSnapshot(payload,saved){const previous=await dbOperation('readonly',store=>store.get(AUTOSAVE_CURRENT)).catch(()=>null);await dbOperation('readwrite',store=>{if(previous)store.put(previous,AUTOSAVE_PREVIOUS);return store.put({version:2,saved,project:payload},AUTOSAVE_CURRENT)});await dbOperation('readwrite',store=>{const cursor=store.openCursor();cursor.onsuccess=()=>{const item=cursor.result;if(item){if(item.key!==AUTOSAVE_CURRENT&&item.key!==AUTOSAVE_PREVIOUS)item.delete();item.continue()}}}).catch(()=>{})}
function persistProject(){clearTimeout(autosaveTimer);if(canvasTransformActive()){markAutosaveDirty();autosaveTimer=setTimeout(persistProject,250);return storageQueue}if(!historyReady||historyRestoring||actionDepth||loadingPage||!preferences.autosave||cropSession)return storageQueue;const epoch=memoryEpoch,payload=encodeMemory(fullPayload(true)),saved=new Date().toISOString();markAutosaveDirty();storageQueue=storageQueue.catch(()=>{}).then(async()=>{if(epoch!==memoryEpoch||!preferences.autosave)return;try{await saveStableSnapshot(payload,saved);if(epoch!==memoryEpoch||!preferences.autosave)return;localStorage.setItem(MEMORY_KEY,JSON.stringify({version:2,saved,database:true,record:AUTOSAVE_CURRENT}));localStorage.removeItem(AUTOSAVE_DIRTY_KEY);lastSavedPayload=payload;memoryMessage('Salvato alle '+new Date(saved).toLocaleTimeString('it-IT')+' · database protetto del browser')}catch(error){console.warn(error);memoryMessage('Autosalvataggio NON riuscito: spazio esaurito o memoria bloccata. Esporta il JSON per conservare il lavoro.')}});return storageQueue}
async function decodeStoredSnapshot(record,fallbackSaved){if(!record)return null;const saved=record.saved||fallbackSaved,projectText=typeof record==='string'?record:record.project;if(!projectText)return null;return{saved:saved||new Date().toISOString(),project:validateProject(decodeMemory(projectText))}}
async function readMemory(){let marker=null;try{marker=JSON.parse(localStorage.getItem(MEMORY_KEY)||'null')}catch(error){}if(marker?.project){try{return{saved:marker.saved,project:validateProject(decodeMemory(marker.project))}}catch(error){console.warn('Copia Local Storage non valida',error)}}let current=null;try{current=await dbOperation('readonly',store=>store.get(AUTOSAVE_CURRENT))}catch(error){if(!marker)return null}try{const decoded=await decodeStoredSnapshot(current,marker?.saved);if(decoded)return decoded}catch(error){console.warn('Autosave corrente non valido',error)}if(marker?.version===1&&marker.database&&marker.record){try{const legacy=await dbOperation('readonly',store=>store.get(marker.record)),decoded=await decodeStoredSnapshot(legacy,marker.saved);if(decoded)return decoded}catch(error){console.warn('Autosave precedente non valido',error)}}try{const previous=await dbOperation('readonly',store=>store.get(AUTOSAVE_PREVIOUS)),decoded=await decodeStoredSnapshot(previous,marker?.saved);if(decoded)return decoded}catch(error){console.warn('Copia di sicurezza non valida',error)}if(marker||localStorage.getItem(AUTOSAVE_DIRTY_KEY))throw new Error('salvataggio interrotto prima della prima copia completa');return null}
let persistentStorageRequested=false;async function requestPersistentAutosaveStorage(){if(persistentStorageRequested||!preferences.autosave||!navigator.storage?.persist)return;persistentStorageRequested=true;try{const already=await navigator.storage.persisted?.();const granted=already||await navigator.storage.persist();if(granted)memoryMessage('Archiviazione persistente attiva · i progetti sono protetti dalla pulizia automatica del browser.')}catch(error){console.warn('Storage persistente non disponibile',error)}}

async function clearAllMemory(){if(bgWorking){toast('Attendi la fine della rimozione sfondo');return}preferences.autosave=false;lastSavedPayload='';memoryEpoch++;bgCacheEpoch++;clearTimeout(autosaveTimer);await storageQueue.catch(()=>{});let failed=false;try{localStorage.removeItem(MEMORY_KEY);localStorage.removeItem(AUTOSAVE_DIRTY_KEY);localStorage.removeItem(PREF_KEY);localStorage.removeItem('chiccanva-colorizer-brush-engine');clearSearchTranslationCache?.()}catch(e){failed=true}try{await dbOperation('readwrite',s=>s.clear())}catch(e){failed=true}try{if('caches' in window)await caches.delete(BG_CACHE)}catch(e){failed=true}backgroundModulePromise=null;for(const name of ['__outlineOrtUrl','__chicGpuUrl']){if(globalThis[name])URL.revokeObjectURL(globalThis[name]);globalThis[name]=null}syncSettings();memoryMessage(failed?'Pulizia parziale: una memoria del browser non è accessibile. Puoi completarla dalle impostazioni del browser.':'Dati e modelli cancellati. Progetto aperto conservato; autosalvataggio disattivato.');toast(failed?'Pulizia parziale':'Memoria e cache dei modelli cancellate')}
// Only IMG.LY model/runtime downloads use this cache; never caches user images.
globalThis.__chicBgFetch=async function(input,options={}){const url=new URL(String(input));if(url.origin!=='https://staticimgly.com')return fetch(input,options);const epoch=bgCacheEpoch;let cache=null;try{if('caches' in window){cache=await caches.open(BG_CACHE);const hit=await cache.match(url.href);if(hit){$('bgCacheStatus').textContent='Modello e runtime: lettura dalla cache del browser.';return hit}}}catch(e){console.warn('Cache modelli non disponibile',e)}const response=await fetch(input,{...options,cache:'no-store'});if(response.ok&&cache&&epoch===bgCacheEpoch){try{await cache.put(url.href,response.clone());$('bgCacheStatus').textContent='Risorse salvate nella cache per i prossimi avvii.'}catch(e){$('bgCacheStatus').textContent='Cache piena o non disponibile: il download funzionerà senza salvataggio.'}}return response};

const EMOJI_GROUPS={'smileys-emotion':'Faccine ed emozioni','people-body':'Persone e corpo','component':'Componenti e varianti','animals-nature':'Animali e natura','food-drink':'Cibo e bevande','travel-places':'Viaggi e luoghi','activities':'Attività','objects':'Oggetti','symbols':'Simboli','flags':'Bandiere','extras-openmoji':'Extra OpenMoji','extras-unicode':'Extra Unicode'};
let emojiTranslatedQuery='',emojiTranslationNote='',emojiTranslationSerial=0,emojiSearchBusy=false;
function emojiActiveQuery(){return ($('emojiTranslate').checked?emojiTranslatedQuery:$('emojiSearch').value.trim()).toLocaleLowerCase()}
function emojiMatches(){const q=emojiActiveQuery(),category=$('emojiCategory').value;let all=emojiData.filter(e=>!q||`${e.annotation||''} ${e.tags||''} ${e.openmoji_tags||''} ${e.emoji||''} ${e.hexcode||''} ${EMOJI_GROUPS[e.group]||e.group} ${e.subgroups||''}`.toLocaleLowerCase().includes(q));if(q)return all;if(category!=='all'&&category!=='relevant')return all.filter(e=>e.group===category);if(category==='relevant'){const popular=new Set(graphemes('😀😊😍🥰😂😎🤔👏👍👋❤️⭐🌈☀️🌻🐶🐱🦋🍎🎈🎨📚✏️🏫⚽'));const score=e=>(popular.has(e.emoji)?200:0)+(!String(e.group).startsWith('extras')?50:0)+(/book|pencil|school|teacher/.test(e.annotation||'')?40:0)-(e.hexcode?.includes('-')?10:0);all=[...all].sort((a,b)=>score(b)-score(a)||(a.order||0)-(b.order||0))}return all}
renderEmojiGrid=function(){if(!$('emojiCategory'))return;const select=$('emojiCategory'),old=select.value||'relevant',groups=[...new Set(emojiData.map(e=>e.group).filter(Boolean))];if(select.options.length!==groups.length+2){select.replaceChildren();for(const [value,label] of [['relevant','Più rilevanti'],['all','Tutte le emoji'],...groups.map(g=>[g,EMOJI_GROUPS[g]||g.replaceAll('-',' ')])]){const option=new Option(label,value);select.add(option)}select.value=[...select.options].some(o=>o.value===old)?old:'relevant'}const key=select.value+'|'+$('emojiSearch').value+'|'+emojiTranslatedQuery;if(key!==emojiFilterKey){emojiLimit=120;emojiFilterKey=key;$('emojiGrid').scrollTop=0}const all=emojiMatches(),list=all.slice(0,emojiLimit),note=emojiTranslationNote?' · '+emojiTranslationNote:'';$('emojiCount').textContent=`${list.length} di ${all.length} emoji`+($('emojiSearch').value.trim()?' · ricerca globale':'')+note;$('emojiGrid').replaceChildren();for(const e of list){const b=document.createElement('button');b.className='emoji-btn';b.title=e.annotation||e.emoji;b.setAttribute('aria-label',b.title);const image=document.createElement('img');image.loading='lazy';image.src=openMojiUrl(e.hexcode,state.emojiStyle);image.alt='';b.append(image);b.onclick=()=>addOpenMoji(e);$('emojiGrid').append(b)}if(list.length<all.length){const more=document.createElement('button');more.className='btn emoji-more';more.textContent='Mostra altre 120';more.onclick=()=>{const top=$('emojiGrid').scrollTop;emojiLimit+=120;renderEmojiGrid();$('emojiGrid').scrollTop=top};$('emojiGrid').append(more)}if(!all.length)$('emojiCount').textContent=emojiData.length?'Nessuna emoji trovata.'+note:'Caricamento catalogo OpenMoji…'};
function syncEmojiSearchMode(){const translated=$('emojiTranslate').checked,button=$('emojiSearchBtn');button.classList.toggle('hidden',!translated);button.disabled=emojiSearchBusy;if(!translated){emojiTranslatedQuery='';emojiTranslationNote='';renderEmojiGrid()}else $('emojiCount').textContent=$('emojiSearch').value.trim()?'Premi Invio o la lente per tradurre e cercare.':'Scrivi una parola, poi premi Invio o la lente.'}
function setEmojiSearchBusy(busy,message='Traduzione e ricerca…'){emojiSearchBusy=busy;const button=$('emojiSearchBtn');button.disabled=busy;button.setAttribute('aria-busy',String(busy));button.innerHTML=busy?'<span class="spinner" aria-hidden="true"></span>':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" fill="none" stroke="currentColor" stroke-width="2"/><path d="m15.5 15.5 5 5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';$('emojiGrid').toggleAttribute('aria-busy',busy);if(busy){$('emojiCount').innerHTML='<span class="spinner" aria-hidden="true"></span> '+message;$('emojiGrid').innerHTML='<div class="emoji-search-loading"><span class="spinner" aria-hidden="true"></span><span>'+message+'</span></div>'}}
async function updateEmojiSearch(){const serial=++emojiTranslationSerial,keyword=$('emojiSearch').value.trim();emojiTranslatedQuery='';emojiTranslationNote='';if(!$('emojiTranslate').checked||!keyword){renderEmojiGrid();return}setEmojiSearchBusy(true);try{await new Promise(resolve=>setTimeout(resolve,0));const result=await translateEmojiKeyword(keyword);if(serial!==emojiTranslationSerial)return;emojiTranslatedQuery=result.translated;emojiTranslationNote=result.note;renderEmojiGrid();await new Promise(resolve=>setTimeout(resolve,0))}finally{if(serial===emojiTranslationSerial)setEmojiSearchBusy(false)}}
async function styleEmojiSvg(original,from,ink,factor){const recolored=await recolorEmojiSvg(original,from,ink),xml=new DOMParser().parseFromString(await(await fetch(recolored)).text(),'image/svg+xml'),root=xml.documentElement;for(const e of [root,...root.querySelectorAll('*')]){if(e.hasAttribute('stroke-width')){const n=parseFloat(e.getAttribute('stroke-width'));if(Number.isFinite(n))e.setAttribute('stroke-width',String(n*factor))}if(e.hasAttribute('style'))e.setAttribute('style',e.getAttribute('style').replace(/stroke-width\s*:\s*([\d.]+)/gi,(_,n)=>'stroke-width:'+(Number(n)*factor)))}return dataUrlFromBlob(new Blob([new XMLSerializer().serializeToString(xml)],{type:'image/svg+xml'}))}
const baseAssetFromUrl=assetFromUrl;
assetFromUrl=async function(url,meta={}){const id=await baseAssetFromUrl(url,meta),a=state.assets[id];if(a.kind==='emoji'&&a.meta?.style==='black'){a.originalDataUrl=a.dataUrl;a.meta.originalInk=a.meta.ink;a.meta.strokeFactor=state.emojiStroke||1;a.dataUrl=await styleEmojiSvg(a.originalDataUrl,a.meta.originalInk,a.meta.ink,a.meta.strokeFactor)}return id};
emojiAssetFor=async function(g,style=state.emojiStyle){const hex=emojiHex(g),key=`openmoji:${style}:${hex}:${style==='black'?state.emojiInk+':'+(state.emojiStroke||1):'original'}`;const found=Object.values(state.assets).find(a=>a.sourceKey===key);if(found)return found.id;const id=await assetFromUrl(openMojiUrl(hex,style),{name:'OpenMoji '+g,kind:'emoji',source:'OpenMoji 17.0.0',meta:{emoji:g,hex,style,license:'CC BY-SA 4.0'}});state.assets[id].sourceKey=key;return id};
applyEmojiInk=async function(){const selected=selectionObjects().filter(o=>o.objectType==='emoji');state.emojiInk=$('emojiInk').value;state.emojiStroke=clamp(Number($('emojiStroke').value)||1,.5,3);const page=currentPage;canvas.discardActiveObject();let count=0;for(const o of selected){const a=state.assets[o.assetId];if(a?.meta?.style!=='black')continue;const original=a.originalDataUrl||a.dataUrl,dataUrl=await styleEmojiSvg(original,a.meta.originalInk||a.meta.ink||'#000000',state.emojiInk,state.emojiStroke),id=uid('asset');state.assets[id]={...a,id,dataUrl,originalDataUrl:original,sourceKey:undefined,meta:{...a.meta,ink:state.emojiInk,strokeFactor:state.emojiStroke}};const im=new Image();im.src=dataUrl;await im.decode();if(currentPage!==page)break;o.setElement(im,{width:o.width,height:o.height});o.assetId=id;o.setCoords();count++}canvas.requestRenderAll();saveActivePage();toast(count?'Contorno aggiornato su '+count+' emoji':'Stile impostato per le prossime emoji outlined')};
function openImageUrl(target){urlTarget=target;$('urlTitle').textContent=target==='reference'?'Riferimento AI da URL':'Carica immagine da URL';$('imageUrlInput').value='';$('imageUrlStatus').textContent='';$('urlDialog').showModal();$('imageUrlInput').focus()}
async function fetchImageFile(address){let url;try{url=new URL(address)}catch(e){throw new Error('Inserisci un indirizzo completo https://…')}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error('Usa un URL HTTP o HTTPS senza credenziali');const response=await fetch(url.href,{signal:AbortSignal.timeout(20000),credentials:'omit'});if(!response.ok)throw new Error('Il sito risponde HTTP '+response.status);const blob=await response.blob();if(blob.size>12*1024*1024)throw new Error('Immagine troppo grande: massimo 12 MB');const type=blob.type.split(';')[0];if(!type.startsWith('image/'))throw new Error('Il link non restituisce un’immagine');const im=new Image(),temporary=URL.createObjectURL(blob);try{im.src=temporary;await im.decode();if(!im.naturalWidth||!im.naturalHeight)throw new Error('Immagine non leggibile')}finally{URL.revokeObjectURL(temporary)}return new File([blob],decodeURIComponent(url.pathname.split('/').at(-1)||'Immagine da URL'),{type})}
async function confirmImageUrl(){const btn=$('confirmImageUrl');btn.disabled=true;$('imageUrlStatus').textContent='Caricamento…';try{const file=await fetchImageFile($('imageUrlInput').value.trim());if(urlTarget==='reference')await setAiReference(file);else await handleImageUpload(file);$('urlDialog').close();scheduleCommit()}catch(e){$('imageUrlStatus').textContent=e instanceof TypeError?'Il sito non consente il caricamento (CORS), è bloccato o non raggiungibile. Puoi caricare il file dal computer.':e.message}finally{btn.disabled=false}}

function mobileBackgroundMode(){return /android|iphone|ipad|ipod|mobile/i.test(navigator.userAgent||'')||(matchMedia('(pointer:coarse)').matches&&matchMedia('(max-width:1024px)').matches)}
async function selectedBgDevice(){const choice=preferences.device;if(choice==='cpu')return'cpu';let adapter=null;try{adapter=await navigator.gpu?.requestAdapter()}catch(e){}if(adapter)return'gpu';$('removeBgStatus').textContent='WebGPU non disponibile: elaborazione su CPU.';return'cpu'}
async function makeBackgroundInput(dataUrl,limitMobile=false,status=null){const source=new Image();source.src=dataUrl;await source.decode();let width=source.naturalWidth,height=source.naturalHeight,scale=1;if(limitMobile){const maxSide=1280,maxPixels=1500000;scale=Math.min(1,maxSide/Math.max(width,height),Math.sqrt(maxPixels/(width*height)));if(scale<1){width=Math.max(1,Math.round(width*scale));height=Math.max(1,Math.round(height*scale));if(status)status.textContent='Modalità mobile · riduzione a '+width+' × '+height+' px…'}}const raster=document.createElement('canvas');raster.width=width;raster.height=height;const context=raster.getContext('2d',{alpha:true});context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(source,0,0,width,height);const blob=await new Promise((resolve,reject)=>raster.toBlob(value=>value?resolve(value):reject(new Error('Conversione PNG fallita')),'image/png'));context.clearRect(0,0,width,height);raster.width=raster.height=1;source.src='';return{blob,width,height,reduced:scale<1}}
async function runMobileBackgroundWorker(blob,device,status){const moduleSource=loadBackgroundModule.toString(),workerCode=`let backgroundModulePromise=null;const BG_CACHE=${JSON.stringify(BG_CACHE)};globalThis.__chicBgFetch=async function(input,options={}){const url=new URL(String(input));let cache=null;try{if('caches' in globalThis)cache=await caches.open(BG_CACHE);const hit=cache&&await cache.match(url.href);if(hit)return hit}catch(error){}const response=await fetch(input,{...options,cache:'no-store'});if(response.ok&&cache)try{await cache.put(url.href,response.clone())}catch(error){}return response};${moduleSource};self.onmessage=async function(event){try{const data=event.data,mod=await loadBackgroundModule(),output=await mod.removeBackground(new Blob([data.buffer],{type:data.mime||'image/png'}),{proxyToWorker:false,model:'isnet_quint8',device:data.device,progress:(key,current,total)=>self.postMessage({type:'progress',key,current,total}),output:{format:'image/png',quality:1}}),buffer=await output.arrayBuffer();self.postMessage({type:'result',buffer,mime:output.type||'image/png'},[buffer])}catch(error){self.postMessage({type:'error',message:error&&error.message?error.message:String(error)})}};`;const workerUrl=URL.createObjectURL(new Blob([workerCode],{type:'text/javascript'})),worker=new Worker(workerUrl),input=await blob.arrayBuffer();try{return await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Elaborazione mobile scaduta')),300000);worker.onmessage=event=>{const data=event.data;if(data.type==='progress'){status.textContent='AI mobile · '+data.key+' '+(data.total?Math.round(data.current/data.total*100)+'%':'');return}clearTimeout(timeout);if(data.type==='result')resolve(new Blob([data.buffer],{type:data.mime}));else reject(new Error(data.message||'Worker background-removal non riuscito'))};worker.onerror=event=>{clearTimeout(timeout);reject(new Error(event.message||'Worker background-removal non disponibile'))};worker.postMessage({buffer:input,mime:blob.type,device},[input])})}finally{worker.terminate();URL.revokeObjectURL(workerUrl);status.textContent='Elaborazione conclusa · memoria AI mobile liberata.'}}
async function performAiBackgroundRemoval(blob,status){const mobile=mobileBackgroundMode(),model=mobile?'isnet_quint8':preferences.model;let used=await selectedBgDevice(),fallback=false,out;if(mobile){try{out=await runMobileBackgroundWorker(blob,used,status)}catch(error){if(used!=='gpu')throw error;fallback=true;used='cpu';status.textContent='WebGPU non riuscito: nuovo tentativo mobile su CPU…';out=await runMobileBackgroundWorker(blob,'cpu',status)}}else{const mod=await loadBackgroundModule(),config={proxyToWorker:false,model,device:used,progress:(key,current,total)=>{status.textContent='AI '+(used==='gpu'?'WebGPU':'CPU')+' · '+key+' '+(total?Math.round(current/total*100)+'%':'')},output:{format:'image/png',quality:1}};try{out=await mod.removeBackground(blob,config)}catch(error){if(used!=='gpu')throw error;fallback=true;used='cpu';status.textContent='WebGPU non riuscito: nuovo tentativo su CPU…';out=await mod.removeBackground(blob,{...config,device:'cpu'})}}return{out,used,fallback,model,mobile}}
removeBackgroundSelected=async function(){if(bgWorking)return;if(location.protocol==='file:'&&$('bgMethod').value==='ai'){toast('Per la rimozione AI apri l’app tramite webserver');return}const img=selectedImage(),asset=img&&state.assets[img.assetId];if(!asset){toast('Seleziona un’immagine');return}if(cropSession){toast('Conferma o annulla il crop prima di rimuovere lo sfondo');return}saveActivePage();canvas.discardActiveObject();const pose=serializeObject(img),page=currentPage,button=$('removeBgBtn'),label=button.innerHTML,method=$('bgMethod').value;bgWorking=true;button.disabled=true;$('clearMemory').disabled=true;button.innerHTML='<span class="spinner"></span> Elaborazione…';button.setAttribute('aria-busy','true');$('canvasShell').classList.add('bg-busy');const st=$('removeBgStatus');st.textContent='Preparazione immagine…';let used='cpu',fallback=false,model=null,mobile=false,reduced=false;try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const prepared=await makeBackgroundInput(asset.dataUrl,method==='ai'&&mobileBackgroundMode(),st);reduced=prepared.reduced;let out;if(method==='ai'){const result=await performAiBackgroundRemoval(prepared.blob,st);({out,used,fallback,model,mobile}=result)}else out=await removeSolidBackground(prepared.blob);const dataUrl=await dataUrlFromBlob(out),id=uid('asset');state.assets[id]={id,dataUrl,originalDataUrl:dataUrl,mime:'image/png',name:(asset.name||'immagine')+' senza sfondo',kind:'bgremoved',source:method==='ai'?'IMG.LY background-removal':'Rimozione sfondo uniforme',meta:{derivedFrom:asset.id,model:method==='ai'?model:null,device:used,mobile,reduced}};const descriptor={...pose,id:uid('obj'),assetId:id,objectType:'bgremoved',left:pose.left+30,top:pose.top+30};if(currentPage===page){const result=await instantiateObject(descriptor);canvas.setActiveObject(result);canvas.requestRenderAll();saveActivePage()}else page.objects.push(descriptor);st.textContent='Background rimosso. Creata una copia; originale invariato.'+(method==='ai'?' '+(mobile?'Modalità mobile, RAM liberata':'Modello mantenuto in memoria')+(reduced?' · immagine ottimizzata':'')+' · '+(used==='gpu'?'WebGPU':'CPU')+(fallback?' dopo ripiego.':'.'):'')}catch(error){console.error(error);st.textContent='Rimozione non riuscita: '+(error.message||error)+'. Per il download dei modelli verifica l’accesso a staticimgly.com.';toast('Background removal non riuscito')}finally{bgWorking=false;button.disabled=false;$('clearMemory').disabled=false;button.innerHTML=label;button.removeAttribute('aria-busy');$('canvasShell').classList.remove('bg-busy')}};

function syncSettings(){$('historyLimit').value=preferences.limit;$('includeHistory').checked=preferences.history;$('autosaveEnabled').checked=preferences.autosave;const mobile=mobileBackgroundMode();$('bgModel').value=mobile?'isnet_quint8':preferences.model;$('bgModel').disabled=mobile;$('bgModel').title=mobile?'Su mobile chicCanva usa il modello piccolo in un processo isolato per contenere la RAM':'';$('bgDevice').value=preferences.device;if(mobile)$('bgCacheStatus').textContent='Modalità mobile: modello piccolo, immagini grandi ottimizzate e memoria liberata dopo ogni uso. Il download del modello resta nella cache del browser.'}
syncUiFromState=function(){baseSync();if($('emojiStroke')){$('emojiStroke').value=state.emojiStroke||1;$('emojiStrokeValue').textContent=(state.emojiStroke||1)+'×'}syncSettings()};
function bindPending(){
 const requestPersistence=()=>requestPersistentAutosaveStorage();document.addEventListener('pointerdown',requestPersistence,{once:true,capture:true});document.addEventListener('keydown',requestPersistence,{once:true,capture:true});
 $('mobileUndo').onclick=()=>travelHistory(-1);$('mobileRedo').onclick=()=>travelHistory(1);$('mobileSettings').onclick=()=>$('settingsDialog').showModal();
 $('emojiCategory').onchange=renderEmojiGrid;$('emojiSearch').oninput=()=>{if($('emojiTranslate').checked){$('emojiCount').textContent='Premi Invio o la lente per tradurre e cercare.';return}emojiTranslatedQuery='';emojiTranslationNote='';renderEmojiGrid()};$('emojiSearch').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();updateEmojiSearch()}};$('emojiSearchBtn').onclick=updateEmojiSearch;$('emojiTranslate').onchange=()=>{emojiTranslationSerial++;setEmojiSearchBusy(false);syncEmojiSearchMode()};syncEmojiSearchMode();
 $('emojiStroke').oninput=()=>{state.emojiStroke=Number($('emojiStroke').value);$('emojiStrokeValue').textContent=state.emojiStroke+'×';scheduleCommit()};
 $('imageFromUrl').onclick=()=>openImageUrl('image');$('referenceFromUrl').onclick=()=>openImageUrl('reference');$('confirmImageUrl').onclick=withHistory(confirmImageUrl);$('cancelImageUrl').onclick=()=>$('urlDialog').close();
 $('undoBtn').onclick=()=>travelHistory(-1);$('redoBtn').onclick=()=>travelHistory(1);$('settingsBtn').onclick=()=>$('settingsDialog').showModal();$('closeSettings').onclick=()=>$('settingsDialog').close();$('clearMemory').onclick=clearAllMemory;
 $('historyLimit').onchange=()=>{preferences.limit=clamp(Number($('historyLimit').value)||30,1,100);trimHistory();syncSettings();writePreferences();scheduleAutosave()};$('includeHistory').onchange=()=>{preferences.history=$('includeHistory').checked;writePreferences()};$('autosaveEnabled').onchange=()=>{preferences.autosave=$('autosaveEnabled').checked;writePreferences();if(preferences.autosave){memoryMessage('Autosalvataggio attivato.');scheduleAutosave()}else{clearTimeout(autosaveTimer);memoryMessage('Autosalvataggio disattivato. Le copie precedenti restano in memoria finché non le cancelli.')}};
 $('bgModel').onchange=()=>{preferences.model=$('bgModel').value;writePreferences()};$('bgDevice').onchange=()=>{preferences.device=$('bgDevice').value;writePreferences()};const bgChange=$('bgMethod').onchange;$('bgMethod').onchange=()=>{bgChange?.();$('bgAiOptions').classList.toggle('hidden',$('bgMethod').value!=='ai')};
 document.addEventListener('click',e=>{if(e.target.closest('#undoBtn,#redoBtn,#mobileUndo,#mobileRedo,#memoryDialog,#settingsDialog,#urlDialog'))return;commitHistory();setTimeout(()=>{scheduleCommit();scheduleAutosave()},0)},true);
 document.addEventListener('change',()=>{scheduleCommit();scheduleAutosave()});document.addEventListener('input',e=>{if(e.target.id==='textInput'){scheduleCommit();scheduleAutosave()}});
 window.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.querySelector('dialog[open]'))return;const k=e.key.toLowerCase();if(k==='z'||k==='y'){e.preventDefault();e.stopImmediatePropagation();travelHistory(k==='y'||e.shiftKey?1:-1)}},true);
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){commitHistory();persistProject()}});window.addEventListener('pagehide',()=>{flushBeforeLeave()});window.addEventListener('beforeunload',e=>{if(!flushBeforeLeave()){e.preventDefault();e.returnValue=''}});
 // Fabric binds the live pointer transform to the current object/ActiveSelection.
 // Page serialization temporarily discards the active object, so even an autosave that
 // fires later would cancel a long drag.  Defer every snapshot until pointer release.
 canvas.on('mouse:down',event=>{canvasGestureActive=!!event?.target;if(!canvasGestureActive)commitHistory()});canvas.on('mouse:up',()=>{canvasGestureActive=false;scheduleCommit();scheduleAutosave()});canvas.on('object:modified',()=>{scheduleCommit();scheduleAutosave()});
}
// Wrap operations before their handlers are bound, retaining asynchronous transaction boundaries.
addTextUnified=withHistory(addTextUnified);addOpenMoji=withHistory(addOpenMoji);applyEmojiInk=withHistory(applyEmojiInk);handleImageUpload=withHistory(handleImageUpload);setAiReference=withHistory(setAiReference);removeBackgroundSelected=withHistory(removeBackgroundSelected);generateAi=withHistory(generateAi);duplicateSelection=withHistory(duplicateSelection);resetCrop=withHistory(resetCrop);addCustomPage=withHistory(addCustomPage);applyTextStyle=withHistory(applyTextStyle);applyFontToSelectionOrFuture=withHistory(applyFontToSelectionOrFuture);
const baseLoad=loadPage;loadPage=async function(...args){await baseLoad(...args);scheduleCommit();scheduleAutosave()};
const baseInit=init;
init=async function(){readPreferences();await baseInit();bindPending();state.emojiStroke=state.emojiStroke||1;syncSettings();renderEmojiGrid();let memory=null;try{memory=await readMemory()}catch(e){memoryMessage('Autosalvataggio non leggibile: '+e.message+'. Non è stato sovrascritto.');preferences.autosave=false;syncSettings()}if(memory){$('memoryInfo').textContent='Ultimo salvataggio: '+new Date(memory.saved).toLocaleString('it-IT')+' · '+Object.values(memory.project.pages).reduce((n,p)=>n+p.length,0)+' pagine.';const resume=await new Promise(resolve=>{$('resumeMemory').onclick=()=>resolve(true);$('newMemory').onclick=()=>resolve(false);$('memoryDialog').oncancel=e=>e.preventDefault();$('memoryDialog').showModal()});$('memoryDialog').close();if(resume){try{await adoptProject(memory.project,true);memoryMessage('Progetto recuperato con cronologia.')}catch(e){preferences.autosave=false;memoryMessage('Recupero non riuscito: '+e.message+'. Copia salvata conservata.')}}else{memoryEpoch++;localStorage.removeItem(MEMORY_KEY);await dbOperation('readwrite',s=>s.clear()).catch(()=>{})}}if(!historyEntries.length){historyEntries=[historySnapshot()];historyCursor=0}historyReady=true;syncHistoryButtons();syncSettings()};
