// Vector shapes and an isolated drawing mode for the Fabric canvas.
let shapeMode=null,shapeStart=null,shapeDraft=null,shapeTrace=[],shapeInteractionState=[],shapeEditing=null;
DOCUMENT_FIELDS.push('shapeFill','shapeStroke','shapeStrokeWidth','shapeNoFill');
const SHAPE_TRACE_MODES=new Set(['polyline','polygon','free-smooth','free-raw']);
const SHAPE_LABELS={rect:'Rettangolo',square:'Quadrato',roundrect:'Rettangolo arrotondato',ellipse:'Ovale',circle:'Cerchio',triangle:'Triangolo',diamond:'Rombo',pentagon:'Pentagono',hexagon:'Esagono',star:'Stella',star8:'Stella a 8 punte',heart:'Cuore',moon:'Luna',arrow:'Freccia',callout:'Fumetto',thought:'Fumetto pensiero',line:'Segmento',arrowline:'Linea con freccia',polyline:'Spezzata',polygon:'Poligono', 'free-smooth':'Mano libera liscia','free-raw':'Mano libera raw'};

function shapePaint(){return{fill:$('shapeNoFill').checked?'rgba(255,255,255,0)':$('shapeFill').value,stroke:$('shapeStroke').value,strokeWidth:Number($('shapeStrokeWidth').value)||0,strokeUniform:true,paintFirst:'fill',objectCaching:false,perPixelTargetFind:false}}
function markShape(object,kind){object.objectType='shape';object.chicShapeKind=kind;object.projectId=object.projectId||uid('obj');object.setControlVisible('mtr',state.rotateEnabled);return object}
function regularShapePoints(width,height,sides,rotation=-Math.PI/2,inner=1){const points=[],steps=inner<1?sides*2:sides;for(let i=0;i<steps;i++){const radius=inner<1&&i%2?inner:1,angle=rotation+i*Math.PI*2/steps;points.push({x:Math.cos(angle)*width/2*radius,y:Math.sin(angle)*height/2*radius})}return points}
function pathShape(path,left,top,width,height,kind,paint=shapePaint()){const object=new fabric.Path(path,{...paint,left,top,originX:'center',originY:'center'});object.set({scaleX:width/Math.max(1,object.width),scaleY:height/Math.max(1,object.height)});return markShape(object,kind)}
function polygonShape(points,left,top,kind,paint=shapePaint()){return markShape(new fabric.Polygon(points,{...paint,left,top,originX:'center',originY:'center'}),kind)}
function constrainShapeBox(kind,start,end){let dx=end.x-start.x,dy=end.y-start.y;if(kind==='square'||kind==='circle'){const size=Math.max(Math.abs(dx),Math.abs(dy));dx=(dx<0?-1:1)*size;dy=(dy<0?-1:1)*size}return{x:Math.min(start.x,start.x+dx),y:Math.min(start.y,start.y+dy),width:Math.max(2,Math.abs(dx)),height:Math.max(2,Math.abs(dy)),dx,dy}}
function createShapeDraft(kind,start,end){
 const box=constrainShapeBox(kind,start,end),cx=box.x+box.width/2,cy=box.y+box.height/2,paint=shapePaint();let object;
 if(kind==='rect'||kind==='square'||kind==='roundrect')object=new fabric.Rect({...paint,left:cx,top:cy,originX:'center',originY:'center',width:box.width,height:box.height,rx:kind==='roundrect'?Math.min(box.width,box.height)*.16:0,ry:kind==='roundrect'?Math.min(box.width,box.height)*.16:0});
 else if(kind==='ellipse'||kind==='circle')object=new fabric.Ellipse({...paint,left:cx,top:cy,originX:'center',originY:'center',rx:box.width/2,ry:box.height/2});
 else if(['triangle','diamond','pentagon','hexagon','star','star8','callout'].includes(kind)){
  let points=kind==='triangle'?regularShapePoints(box.width,box.height,3):kind==='diamond'?regularShapePoints(box.width,box.height,4):kind==='pentagon'?regularShapePoints(box.width,box.height,5):kind==='hexagon'?regularShapePoints(box.width,box.height,6):kind==='star'?regularShapePoints(box.width,box.height,5,-Math.PI/2,.43):kind==='star8'?regularShapePoints(box.width,box.height,8,-Math.PI/2,.52):[{x:-box.width/2,y:-box.height/2},{x:box.width/2,y:-box.height/2},{x:box.width/2,y:box.height*.2},{x:box.width*.18,y:box.height*.2},{x:-box.width*.16,y:box.height/2},{x:-box.width*.06,y:box.height*.2},{x:-box.width/2,y:box.height*.2}];
  object=polygonShape(points,cx,cy,kind,paint)
 }else if(kind==='heart')object=pathShape('M 0 78 C -12 62 -82 24 -82 -28 C -82 -78 -20 -92 0 -48 C 20 -92 82 -78 82 -28 C 82 24 12 62 0 78 Z',cx,cy,box.width,box.height,kind,paint);
 else if(kind==='moon')object=pathShape('M 48 -86 C -42 -68 -70 47 10 86 C -42 24 -18 -48 48 -86 Z',cx,cy,box.width,box.height,kind,paint);
 else if(kind==='arrow')object=pathShape('M -96 -25 L 28 -25 L 28 -62 L 96 0 L 28 62 L 28 25 L -96 25 Z',cx,cy,box.width,box.height,kind,paint);
 else if(kind==='thought')object=pathShape('M -82 18 C -108 -20 -72 -57 -38 -48 C -24 -84 28 -82 42 -49 C 83 -62 109 -17 82 15 C 104 48 60 76 31 57 C 5 86 -40 75 -47 50 C -73 58 -98 43 -82 18 Z M -35 77 A 12 12 0 1 0 -11 77 A 12 12 0 1 0 -35 77 Z M -61 99 A 7 7 0 1 0 -47 99 A 7 7 0 1 0 -61 99 Z',cx,cy,box.width,box.height,kind,paint);
 else if(kind==='line')object=markShape(new fabric.Line([start.x,start.y,end.x,end.y],{...paint,fill:null}),kind);
 else if(kind==='arrowline'){
  const dx=end.x-start.x,dy=end.y-start.y,length=Math.max(1,Math.hypot(dx,dy)),ux=dx/length,uy=dy/length,head=Math.min(30,Math.max(12,length*.22)),wing=head*.55,hx=end.x-ux*head,hy=end.y-uy*head,path=`M ${start.x} ${start.y} L ${end.x} ${end.y} M ${end.x} ${end.y} L ${hx-uy*wing} ${hy+ux*wing} M ${end.x} ${end.y} L ${hx+uy*wing} ${hy-ux*wing}`;object=markShape(new fabric.Path(path,{...paint,fill:null}),kind)
 }
 if(!object)return null;object.excludeProject=true;object.selectable=false;object.evented=false;return markShape(object,kind)
}

function tracePath(points,smooth){if(points.length<2)return'';if(!smooth)return'M '+points.map((p,i)=>(i?'L ':'')+p.x+' '+p.y).join(' ');let path=`M ${points[0].x} ${points[0].y}`;for(let i=0;i<points.length-1;i++){const p0=points[Math.max(0,i-1)],p1=points[i],p2=points[i+1],p3=points[Math.min(points.length-1,i+2)],t=.18,c1={x:p1.x+(p2.x-p0.x)*t,y:p1.y+(p2.y-p0.y)*t},c2={x:p2.x-(p3.x-p1.x)*t,y:p2.y-(p3.y-p1.y)*t};path+=` C ${c1.x} ${c1.y} ${c2.x} ${c2.y} ${p2.x} ${p2.y}`}return path}
function tracedPointShape(points,kind,paint=shapePaint()){
 const minX=Math.min(...points.map(point=>point.x)),maxX=Math.max(...points.map(point=>point.x)),minY=Math.min(...points.map(point=>point.y)),maxY=Math.max(...points.map(point=>point.y));
 const local=points.map(point=>({x:point.x-minX,y:point.y-minY})),common={...paint,left:(minX+maxX)/2,top:(minY+maxY)/2,originX:'center',originY:'center'};
 return markShape(kind==='polygon'?new fabric.Polygon(local,common):new fabric.Polyline(local,{...common,fill:'rgba(255,255,255,0)'}),kind)
}
function updateTraceDraft(pointer){
 if(shapeDraft){canvas.remove(shapeDraft);shapeDraft=null}const points=pointer?[...shapeTrace,pointer]:shapeTrace;if(points.length<2)return;
 if(shapeMode==='polygon'||shapeMode==='polyline')shapeDraft=tracedPointShape(points,shapeMode);
 else shapeDraft=markShape(new fabric.Path(tracePath(points,shapeMode==='free-smooth'),{...shapePaint(),fill:null}),shapeMode);
 shapeDraft.excludeProject=true;shapeDraft.selectable=false;shapeDraft.evented=false;canvas.add(shapeDraft);canvas.requestRenderAll()
}
function disableShapeInteractions(){shapeInteractionState=canvas.getObjects().filter(o=>!o.excludeProject).map(object=>({object,selectable:object.selectable,evented:object.evented}));canvas.discardActiveObject();shapeInteractionState.forEach(entry=>entry.object.set({selectable:false,evented:false}));canvas.selection=false;canvas.skipTargetFind=true;canvas.upperCanvasEl.closest('.canvas-container')?.classList.add('shape-drawing')}
function restoreShapeInteractions(){for(const entry of shapeInteractionState)if(canvas.contains(entry.object))entry.object.set({selectable:entry.selectable,evented:entry.evented});shapeInteractionState=[];canvas.selection=state.selectionMode;canvas.skipTargetFind=false;canvas.upperCanvasEl.closest('.canvas-container')?.classList.remove('shape-drawing')}
function beginShapeMode(kind){if(workspaceBusy()||cropSession){toast('Completa prima l’operazione in corso');return}if(state.regionMode)setRegionMode(false);finishCanvasColorPick?.();cancelShapeDrawing(false);shapeMode=kind;shapeTrace=[];shapeStart=null;disableShapeInteractions();document.querySelectorAll('#shapeTools [data-shape]').forEach(button=>button.classList.toggle('active',button.dataset.shape===kind));$('shapeStatus').textContent=SHAPE_TRACE_MODES.has(kind)?(kind==='polygon'||kind==='polyline'?'Tocca per aggiungere punti; doppio tocco o “Termina” per concludere.':'Trascina sul foglio per disegnare.'):'Trascina sul foglio per creare '+SHAPE_LABELS[kind].toLocaleLowerCase('it-IT')+'.'}
function finishShapeObject(object){if(!object)return;object.excludeProject=false;object.selectable=true;object.evented=true;object.projectId=object.projectId||uid('obj');shapeDraft=null;shapeMode=null;shapeStart=null;shapeTrace=[];restoreShapeInteractions();document.querySelectorAll('#shapeTools [data-shape]').forEach(button=>button.classList.remove('active'));canvas.setActiveObject(object);object.setCoords();canvas.requestRenderAll();saveActivePage();scheduleCommit();scheduleAutosave();selectionChanged();$('shapeStatus').textContent=(SHAPE_LABELS[object.chicShapeKind]||'Forma')+' inserita. Puoi spostarla, ridimensionarla e ruotarla.'}
function finishTraceDrawing(){if(!shapeMode)return;if(shapeTrace.length<2){cancelShapeDrawing();return}if(shapeDraft)canvas.remove(shapeDraft);let object;if(shapeMode==='polygon'||shapeMode==='polyline')object=tracedPointShape(shapeTrace,shapeMode);else object=markShape(new fabric.Path(tracePath(shapeTrace,shapeMode==='free-smooth'),{...shapePaint(),fill:null}),shapeMode);canvas.add(object);finishShapeObject(object)}
function cancelShapeDrawing(notify=true){if(shapeDraft)canvas.remove(shapeDraft);shapeDraft=null;shapeMode=null;shapeStart=null;shapeTrace=[];if(shapeInteractionState.length)restoreShapeInteractions();document.querySelectorAll('#shapeTools [data-shape]').forEach(button=>button.classList.remove('active'));canvas?.requestRenderAll();if(notify&&$('shapeStatus'))$('shapeStatus').textContent='Disegno annullato.'}
function shapePointer(options){return canvas.getPointer(options.e)}
function shapeMouseDown(options){if(!shapeMode)return;const point=shapePointer(options);options.e?.preventDefault?.();if(shapeMode==='polygon'||shapeMode==='polyline'){shapeTrace.push(point);updateTraceDraft();return}shapeStart=point;shapeTrace=[point];if(!SHAPE_TRACE_MODES.has(shapeMode)){shapeDraft=createShapeDraft(shapeMode,point,{x:point.x+2,y:point.y+2});if(shapeDraft)canvas.add(shapeDraft)}}
function shapeMouseMove(options){if(!shapeMode||!shapeStart&&shapeMode!=='polygon'&&shapeMode!=='polyline')return;const point=shapePointer(options);if(shapeMode==='free-smooth'||shapeMode==='free-raw'){const last=shapeTrace.at(-1);if(!last||Math.hypot(point.x-last.x,point.y-last.y)>2){shapeTrace.push(point);updateTraceDraft()}}else if(shapeMode!=='polygon'&&shapeMode!=='polyline'){if(shapeDraft)canvas.remove(shapeDraft);shapeDraft=createShapeDraft(shapeMode,shapeStart,point);if(shapeDraft)canvas.add(shapeDraft);canvas.requestRenderAll()}else updateTraceDraft(point)}
function shapeMouseUp(options){if(!shapeMode||!shapeStart)return;if(shapeMode==='free-smooth'||shapeMode==='free-raw'){shapeTrace.push(shapePointer(options));finishTraceDrawing();return}if(!SHAPE_TRACE_MODES.has(shapeMode)){const object=shapeDraft;if(!object)return;const bounds=object.getBoundingRect(true,true);if(bounds.width<5&&bounds.height<5){cancelShapeDrawing();return}finishShapeObject(object)}}

function shapeDescriptor(object){
 const base={id:object.projectId||uid('obj'),objectType:'shape',shapeKind:object.chicShapeKind||'shape',fabricType:object.type,left:object.left,top:object.top,scaleX:object.scaleX??1,scaleY:object.scaleY??1,angle:object.angle||0,opacity:object.opacity??1,originX:object.originX||'center',originY:object.originY||'center',flipX:!!object.flipX,flipY:!!object.flipY,fill:object.fill,stroke:object.stroke,strokeWidth:object.strokeWidth||0,strokeUniform:object.strokeUniform!==false,locked:!!object.chicLocked};object.projectId=base.id;
 if(object.type==='rect')base.geometry={width:object.width,height:object.height,rx:object.rx||0,ry:object.ry||0};
 else if(object.type==='ellipse')base.geometry={rx:object.rx,ry:object.ry};
 else if(object.type==='line')base.geometry={x1:object.x1,y1:object.y1,x2:object.x2,y2:object.y2};
 else if(object.type==='polygon'||object.type==='polyline')base.geometry={points:object.points.map(point=>({x:point.x,y:point.y}))};
 else base.geometry={path:cloneData(object.path)};
 return base
}
function instantiateShape(d,target){const common={left:d.left,top:d.top,scaleX:d.scaleX??1,scaleY:d.scaleY??1,angle:d.angle||0,opacity:d.opacity??1,originX:d.originX||'center',originY:d.originY||'center',flipX:!!d.flipX,flipY:!!d.flipY,fill:d.fill,stroke:d.stroke,strokeWidth:d.strokeWidth||0,strokeUniform:d.strokeUniform!==false,objectCaching:false};let object;if(d.fabricType==='rect')object=new fabric.Rect({...common,...d.geometry});else if(d.fabricType==='ellipse')object=new fabric.Ellipse({...common,...d.geometry});else if(d.fabricType==='line')object=new fabric.Line([d.geometry.x1,d.geometry.y1,d.geometry.x2,d.geometry.y2],common);else if(d.fabricType==='polygon')object=new fabric.Polygon(d.geometry.points,common);else if(d.fabricType==='polyline')object=new fabric.Polyline(d.geometry.points,common);else object=new fabric.Path(d.geometry.path,common);markShape(object,d.shapeKind);object.projectId=d.id||uid('obj');if(d.locked)applyObjectLock(object,true);target.add(object);return object}
const shapesSerializeObject=serializeObject;serializeObject=function(object){if(object?.excludeProject)return null;if(object?.objectType==='shape')return shapeDescriptor(object);return shapesSerializeObject(object)};
const shapesInstantiateObject=instantiateObject;instantiateObject=async function(d,target=canvas){if(d?.objectType==='shape')return instantiateShape(d,target);return shapesInstantiateObject(d,target)};

function applyShapeStyle(){const objects=selectionObjects().filter(object=>object.objectType==='shape');$('shapeStrokeValue').textContent=(Number($('shapeStrokeWidth').value)||0)+' px';if(!objects.length)return;for(const object of objects)object.set({...shapePaint(),dirty:true});canvas.requestRenderAll();saveActivePage();scheduleCommit();scheduleAutosave()}
function polygonPositionHandler(dim,finalMatrix,object){const point=object.points[this.pointIndex],position={x:point.x-object.pathOffset.x,y:point.y-object.pathOffset.y};return fabric.util.transformPoint(position,fabric.util.multiplyTransformMatrices(object.canvas.viewportTransform,object.calcTransformMatrix()))}
function polygonPointAction(eventData,transform,x,y){const object=transform.target,local=object.toLocalPoint(new fabric.Point(x,y),'center','center'),base=object._getNonTransformedDimensions(),size=object._getTransformedDimensions(0,0);object.points[this.pointIndex]={x:local.x*base.x/size.x+object.pathOffset.x,y:local.y*base.y/size.y+object.pathOffset.y};object.dirty=true;return true}
function endShapePointEdit(){if(!shapeEditing)return;shapeEditing.controls=shapeEditing.chicOriginalControls||fabric.Object.prototype.controls;delete shapeEditing.chicOriginalControls;shapeEditing.hasBorders=true;shapeEditing=null;$('shapeEditPoints').classList.remove('active');canvas.upperCanvasEl.closest('.canvas-container')?.classList.remove('shape-editing');canvas.requestRenderAll();saveActivePage();scheduleCommit()}
function toggleShapePointEdit(){const object=selectionObjects()[0];if(shapeEditing){endShapePointEdit();return}if(!object||object.objectType!=='shape'||!['polygon','polyline'].includes(object.type)){toast('La modifica punti è disponibile per poligoni, stelle, fumetti e spezzate. Per le altre forme usa le maniglie laterali.');return}const touch=typeof canvasTouchUiActive==='function'&&canvasTouchUiActive(),visual=touch?20:14,hit=touch?44:20;shapeEditing=object;object.chicOriginalControls=object.controls;const controls={};object.points.forEach((point,index)=>{controls['p'+index]=new fabric.Control({pointIndex:index,positionHandler:polygonPositionHandler,actionHandler:polygonPointAction,actionName:'modifyShapePoint',cursorStyle:'crosshair',cornerColor:'#7549b8',cornerStyle:'circle',sizeX:visual,sizeY:visual,touchSizeX:hit,touchSizeY:hit})});object.controls=controls;object.hasBorders=false;$('shapeEditPoints').classList.add('active');canvas.upperCanvasEl.closest('.canvas-container')?.classList.add('shape-editing');canvas.requestRenderAll();$('shapeStatus').textContent='Trascina i punti viola; premi di nuovo “Modifica punti” quando hai finito.'}
const shapesSelectionChanged=selectionChanged;selectionChanged=function(){if(shapeEditing&&canvas.getActiveObject()!==shapeEditing)endShapePointEdit();shapesSelectionChanged();const object=selectionObjects()[0];$('shapeEditPoints').disabled=selectionObjects().length!==1||object?.objectType!=='shape';if(object?.objectType==='shape'){$('shapeFill').value=/^#[0-9a-f]{6}$/i.test(object.fill)?object.fill:'#ffffff';$('shapeNoFill').checked=!object.fill||object.fill==='rgba(255,255,255,0)'||object.fill==='transparent';$('shapeStroke').value=/^#[0-9a-f]{6}$/i.test(object.stroke)?object.stroke:'#000000';$('shapeStrokeWidth').value=object.strokeWidth||0;$('shapeStrokeValue').textContent=(object.strokeWidth||0)+' px'}};

function openShapesSection(){if(!state.sidebar.open)$('toggleSidebarBtn').click();const card=$('shapesCard'),cards=[...$('sidebar').querySelectorAll(':scope > .card')];if(preferences.accordion)cards.forEach(item=>item.classList.toggle('collapsed',item!==card));card.classList.remove('collapsed');card.querySelector(':scope > .card-h')?.setAttribute('aria-expanded','true');card.scrollIntoView({behavior:'smooth',block:'start'})}
function setupShapes(){
 const imageCard=$('uploadImageBtn').closest('.card');imageCard.parentNode.insertBefore($('shapesCard'),imageCard);
 const jump=document.createElement('button');jump.type='button';jump.textContent='✦ Forme';jump.title='Forme e disegno';jump.onclick=openShapesSection;$('sidebar').querySelector('.quick-jump')?.append(jump);
 for(const button of document.querySelectorAll('#shapeTools [data-shape]'))button.onclick=()=>beginShapeMode(button.dataset.shape);
 $('shapeFinish').onclick=finishTraceDrawing;$('shapeCancel').onclick=()=>cancelShapeDrawing();$('shapeEditPoints').onclick=toggleShapePointEdit;
 $('shapeFill').oninput=applyShapeStyle;$('shapeStroke').oninput=applyShapeStyle;$('shapeStrokeWidth').oninput=applyShapeStyle;$('shapeNoFill').onchange=applyShapeStyle;
 canvas.on('mouse:down',shapeMouseDown);canvas.on('mouse:move',shapeMouseMove);canvas.on('mouse:up',shapeMouseUp);canvas.on('mouse:dblclick',()=>{if(shapeMode==='polygon'||shapeMode==='polyline'){shapeTrace.pop();finishTraceDrawing()}});
 window.addEventListener('keydown',event=>{if(event.key==='Escape'&&shapeMode){event.preventDefault();cancelShapeDrawing()}else if(event.key==='Enter'&&(shapeMode==='polygon'||shapeMode==='polyline')){event.preventDefault();finishTraceDrawing()}},true)
}
const shapesBaseInit=init;init=async function(){await shapesBaseInit();setupShapes()};
