// v7: independent projects using the same custom-page editor.
let projects=[],activeProjectId=null,workspaceReady=false,projectSwitching=false,projectSerial=1,projectClipboard=null,pasteSerial=0,projectDialogAction=null,projectDialogId=null,fontPreviewTimer=0;
const DOCUMENT_FIELDS=['splitText','fitAxis','specialText','specialUppercase','specialEmoji','specialExplicit','specialPrev','specialNext','specialApostrophe','specialOrientation','specialFit','specialDestination','specialOperation','bgAutoColor','bgEverywhere','bgColor','bgTolerance','aiChromaKey','aiRemoveBackground'];
const v6Capture=capturePayload,v6FullPayload=fullPayload,v6Restore=restoreSnapshot,v6Adopt=adoptProject,v6Commit=commitHistory,v6Sync=syncUiFromState;
function documentFields(){return Object.fromEntries(DOCUMENT_FIELDS.map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]))}
function restoreDocumentFields(ui={}){for(const id of DOCUMENT_FIELDS)if(id in ui){if($(id).type==='checkbox')$(id).checked=!!ui[id];else $(id).value=ui[id]}updateTextModeUI();$('specialCurrentOptions').classList.toggle('hidden',$('specialDestination').value!=='current')}
capturePayload=function(){const p=v6Capture();p.state.workspaceCustom=true;p.state.documentFields=documentFields();return p};
function activeProject(){return projects.find(p=>p.id===activeProjectId)}
function contentSignature(payload){return historySignature(payload)}
function currentDocument(includeHistory=true){const p=v6FullPayload(includeHistory);p.version=7;p.name=activeProject()?.name||'Progetto';p.state.workspaceCustom=true;p.state.documentFields=documentFields();return cloneData(p)}
function storeActiveDocument(){if(!workspaceReady||projectSwitching||historyRestoring||loadingPage)return;const record=activeProject();if(record)record.payload=currentDocument(true)}
fullPayload=function(includeHistory=preferences.history){const p=v6FullPayload(includeHistory);p.version=7;p.name=activeProject()?.name||'Progetto';if(workspaceReady){const current=activeProject();if(current&&!projectSwitching&&!historyRestoring){current.payload=cloneData({...p,history:{version:1,limit:preferences.limit,cursor:historyCursor,entries:cloneData(historyEntries)}})}p.workspace={version:1,activeId:activeProjectId,serial:projectSerial,projects:cloneData(projects)}}return p};
projectPayload=function(){return currentDocument(preferences.history)};
const v6Decode=decodeMemory;decodeMemory=function(text){const p=v6Decode(text);for(const record of p.workspace?.projects||[])for(const a of Object.values(record.payload?.assets||{}))a.originalDataUrl??=a.dataUrl;return p};
function normalizeCustomSnapshot(snap){const result=cloneData(snap);if(!result.state.workspaceCustom)throw new Error('Usa un progetto chicCanva v7');result.state.mode='custom';result.pages.whole=[];result.pages.single=[];return result}
function normalizeCustomProject(input){validateProject(input);if(input.version!==7)throw new Error('Formato richiesto: chicCanva v7');const p=normalizeCustomSnapshot(input);p.version=7;delete p.workspace;if(p.history){p.history.entries=p.history.entries.map(normalizeCustomSnapshot)}return p}
ensurePages=function(){state.mode='custom';state.pages.whole=[];state.pages.single=[];if(!state.pages.custom.length)state.pages.custom=[makePage('Pagina 1',210,297)];state.pageIndex={whole:0,single:0,custom:clamp(state.pageIndex?.custom||0,0,state.pages.custom.length-1)}};
restoreSnapshot=async function(snap,assets=state.assets){const migrated=normalizeCustomSnapshot(snap);await v6Restore(migrated,assets);restoreDocumentFields(migrated.state.documentFields);refreshFontPreviews();};
adoptProject=async function(p,includeHistory){const migrated=normalizeCustomProject(p);await v6Adopt(migrated,includeHistory);restoreDocumentFields(migrated.state.documentFields)};
commitHistory=function(){v6Commit();if(workspaceReady)renderProjectTabs()};
function workspaceBusy(){return projectSwitching||actionDepth>0||loadingPage||historyRestoring||bgWorking}
function renderProjectTabs(){const box=$('projectTabs');if(!box)return;box.replaceChildren();for(const project of projects){const tab=document.createElement('div');tab.className='project-tab'+(project.id===activeProjectId?' active':'');const b=document.createElement('button');b.className='project-name';b.textContent=project.name;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(project.id===activeProjectId));b.title=project.name;b.onclick=()=>activateProject(project.id).catch(e=>toast(e.message));const close=document.createElement('button');close.className='project-close';close.textContent='×';close.setAttribute('aria-label','Chiudi '+project.name);close.onclick=()=>requestCloseProject(project.id);tab.append(b,close);box.append(tab)}box.setAttribute('aria-busy',String(projectSwitching))}
async function activateProject(id){if(id===activeProjectId)return;if(workspaceBusy()){toast('Attendi il completamento dell’operazione');return}if(cropSession){toast('Conferma o annulla il crop prima di cambiare progetto');return}commitHistory();storeActiveDocument();const target=projects.find(p=>p.id===id);if(!target)return;const previous=activeProjectId;projectSwitching=true;closePreview();hideContext();try{activeProjectId=id;await adoptProject(target.payload,true);renderProjectTabs()}catch(e){activeProjectId=previous;await adoptProject(activeProject().payload,true);throw e}finally{projectSwitching=false;renderProjectTabs();scheduleAutosave()}}
function blankProjectPayload(name){const p=currentDocument(false);delete p.workspace;delete p.history;p.name=name;p.assets={};p.pages={whole:[],single:[],custom:[makePage('Pagina 1',210,297)]};p.state={...p.state,mode:'custom',workspaceCustom:true,pageIndex:{whole:0,single:0,custom:0},text:'',aiReference:null,customCounter:1,strokeColor:'#000000',emojiInk:'#000000',documentFields:{...documentFields(),specialText:'',specialDestination:'new',specialOperation:'append'}};return p}
async function addProject(payload,name){if(workspaceBusy())throw new Error('Attendi il completamento dell’operazione');const converted=normalizeCustomProject(payload);commitHistory();storeActiveDocument();const record={id:uid('project'),name:(name||payload.name||'Progetto '+projectSerial++).slice(0,100),payload:converted,lastExport:null};projects.push(record);const old=activeProjectId;projectSwitching=true;activeProjectId=record.id;try{await adoptProject(converted,!!converted.history);renderProjectTabs()}catch(e){projects.pop();activeProjectId=old;if(activeProject())await adoptProject(activeProject().payload,true);throw e}finally{projectSwitching=false;renderProjectTabs();scheduleAutosave()}return record}
function requestDeletePage(){if(state.pages.custom.length<=1){toast('Mantieni almeno una pagina');return}const page=state.pages.custom[state.pageIndex.custom];$('deletePageInfo').textContent='Vuoi eliminare «'+(page?.name||'questa pagina')+'»?';$('deletePageDialog').showModal();setTimeout(()=>$('deletePageCancel').focus(),0)}
function requestNewProject(){if(workspaceBusy()){toast('Attendi il completamento dell’operazione');return}projectDialogAction='new';$('projectDialogTitle').textContent='Crea un nuovo progetto';$('projectDialogInfo').textContent='Il progetto aperto resterà disponibile nella sua scheda.';$('projectNameRow').classList.remove('hidden');$('projectNameInput').value='Progetto '+projectSerial;$('projectConfirm').textContent='Crea progetto';$('projectExportClose').classList.add('hidden');$('projectDialog').showModal()}
function requestCloseProject(id){if(workspaceBusy()){toast('Attendi il completamento dell’operazione');return}commitHistory();storeActiveDocument();const p=projects.find(p=>p.id===id);if(!p)return;projectDialogAction='close';projectDialogId=id;$('projectDialogTitle').textContent='Chiudi '+p.name;$('projectDialogInfo').textContent=(p.lastExport===contentSignature(p.payload)?'La versione attuale è stata esportata. ':'Questa versione non risulta esportata: salva una copia JSON prima di chiudere. ')+'La chiusura rimuove il progetto anche dall’autosalvataggio del browser.';$('projectNameRow').classList.add('hidden');$('projectConfirm').textContent='Chiudi progetto';$('projectExportClose').classList.remove('hidden');$('projectDialog').showModal()}
async function closeProject(id,exportFirst=false){if(workspaceBusy())return;storeActiveDocument();const p=projects.find(p=>p.id===id);if(!p)return;if(exportFirst)exportProjectRecord(p);const wasActive=id===activeProjectId;projects=projects.filter(p=>p.id!==id);if(!projects.length){const payload=blankProjectPayload('Progetto '+projectSerial++);projects=[{id:uid('project'),name:payload.name,payload,lastExport:null}]}if(wasActive){projectSwitching=true;activeProjectId=projects[0].id;try{await adoptProject(projects[0].payload,true)}finally{projectSwitching=false}}renderProjectTabs();memoryEpoch++;await storageQueue.catch(()=>{});if(preferences.autosave)await persistProject();toast('Progetto chiuso e rimosso dall’autosalvataggio')}
function exportProjectRecord(record){if(record.id===activeProjectId)storeActiveDocument();const p=cloneData(record.payload);if(!preferences.history)delete p.history;delete p.workspace;p.name=record.name;download(record.name.replace(/[<>:"/\\|?*]/g,'_')+'.json',new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));record.lastExport=contentSignature(record.payload);scheduleAutosave();return p}
exportJson=function(){commitHistory();storeActiveDocument();const record=activeProject();if(record){exportProjectRecord(record);$('projectStatus').textContent='Progetto «'+record.name+'» esportato.'}};
importJsonFile=async function(file){try{if(workspaceBusy())throw new Error('Attendi il completamento dell’operazione');const p=JSON.parse(await file.text());if(p.workspace){const records=p.workspace.projects;if(!Array.isArray(records)||!records.length)throw new Error('Workspace vuoto');for(const r of records)normalizeCustomProject(r.payload);for(const r of records){const copy=cloneData(r.payload);if(!preferences.history)delete copy.history;await addProject(copy,r.name)}}else{const copy=cloneData(p);if(!preferences.history)delete copy.history;await addProject(copy,p.name||file.name.replace(/\.json$/i,''))}toast('Importato in una nuova scheda')}catch(e){console.error(e);toast('Importazione non riuscita: '+e.message)}};

// Compound letter/symbol objects retain their vectors and editable crop data.
const v6Serialize=serializeObject,v6Instantiate=instantiateObject;
serializeObject=function(o){if(o.objectType!=='group')return v6Serialize(o);return{id:o.projectId||uid('obj'),objectType:'group',left:o.left,top:o.top,scaleX:o.scaleX,scaleY:o.scaleY,angle:o.angle||0,originX:o.originX,originY:o.originY,flipX:!!o.flipX,flipY:!!o.flipY,opacity:o.opacity,width:o.width,height:o.height,children:o.getObjects().map(serializeObject).filter(Boolean)}};
instantiateObject=async function(d,target=canvas){if(d.objectType!=='group')return v6Instantiate(d,target);const temporary=new fabric.StaticCanvas(null),children=[];try{for(const child of d.children||[]){const o=await instantiateObject(child,temporary);if(o)children.push(o)}children.forEach(o=>temporary.remove(o));const group=new fabric.Group(children,{left:d.left,top:d.top,width:d.width,height:d.height,originX:d.originX||'center',originY:d.originY||'center',scaleX:d.scaleX??1,scaleY:d.scaleY??1,angle:d.angle||0,opacity:d.opacity??1,flipX:!!d.flipX,flipY:!!d.flipY},true);group.objectType='group';group.projectId=d.id||uid('obj');target.add(group);return group}finally{temporary.dispose()}};
function visitDescriptors(objects,fn){for(const o of objects||[]){fn(o);if(o.children)visitDescriptors(o.children,fn)}}
referencedAssets=function(snapshots){const ids=new Set();for(const snap of snapshots)for(const pages of Object.values(snap.pages))for(const p of pages)visitDescriptors(p.objects,o=>{if(o.assetId)ids.add(o.assetId)});return Object.fromEntries([...ids].filter(id=>state.assets[id]).map(id=>[id,state.assets[id]]))};
const v6Validate=validateProject;validateProject=function(p){v6Validate(p);for(const pages of Object.values(p.pages))for(const page of pages)visitDescriptors(page.objects,o=>{if(o.assetId&&!p.assets?.[o.assetId])throw new Error('Asset mancante nel gruppo')});return p};
async function tokenObject(token,target){const gs=graphemes(token);if(!(state.smartEmoji&&gs.some(isEmoji))){const o=makeTextObj(token,0,0,100);target.add(o);return o}const pieces=[];let x=0;for(const g of gs){let o;if(isEmoji(g))o=await instantiateObject(await makeGlyphDescriptor(g,0,0,100),target);else{o=makeTextObj(g,0,0,100);target.add(o)}if(!o)continue;o.set({left:x+o.getScaledWidth()/2,top:60});x+=o.getScaledWidth()+3;pieces.push(o)}if(pieces.length===1)return pieces[0];pieces.forEach(o=>target.remove(o));const group=new fabric.Group(pieces,{originX:'center',originY:'center'});group.objectType='group';group.projectId=uid('obj');target.add(group);return group}
textObjects=async function(text,split,target){const objects=[];let y=60;for(const line of text.split('\n')){const tokens=split?groupGraphemes(graphemes(line)).map(g=>g.join('')):[line];let x=0;for(const token of tokens){if(!token.trim())continue;const o=await tokenObject(token,target);o.set({left:x+o.getScaledWidth()/2,top:y});o.setCoords();x+=o.getScaledWidth()+8;objects.push(o)}y+=130}return objects};
// Preserve spaces while applying the same grouping rules to a row of separate objects.
async function splitTextObjects(text,target){const objects=[];let y=60;for(const line of text.split('\n')){let x=0;const raw=graphemes(line),groups=groupGraphemes(raw);let offset=0;for(const group of groups){while(offset<raw.length&&/^\s$/.test(raw[offset])){x+=28;offset++}const token=group.join(''),o=await tokenObject(token,target);o.set({left:x+o.getScaledWidth()/2,top:y});o.setCoords();x+=o.getScaledWidth()+8;objects.push(o);let left=group.length;while(offset<raw.length&&left){if(!/^\s$/.test(raw[offset]))left--;offset++}}y+=130}return objects}
addTextUnified=withHistory(async function(){if(loadingPage)return;syncStateFromUI();if(!state.text.trim())return;const b=$('buildTextBtn');b.disabled=true;try{saveActivePage();await loadFont(state.font);const text=state.uppercase?state.text.toLocaleUpperCase('it-IT'):state.text,objects=$('splitText').checked?await splitTextObjects(text,canvas):await textObjects(text,false,canvas);fitObjectList(objects,canvas.width,canvas.height);canvas.requestRenderAll();saveActivePage();toast('Testo aggiunto')}finally{b.disabled=false}});
updateTextModeUI=function(){state.mode='custom';$('splitTextRow').classList.remove('hidden');$('rebuildTextBtn').classList.add('hidden');$('singleOptions').classList.remove('hidden');$('orientationSeg').classList.add('hidden');$('orientationSeg').previousElementSibling.classList.add('hidden');$('customCardTitle').closest('.card').classList.remove('hidden');$('textModeHelp').textContent='Aggiunge una frase o singole lettere/gruppi alla pagina corrente.';$('previewBtn').disabled=false;for(const e of document.querySelectorAll('[data-symbol-options]'))e.classList.toggle('hidden',!$('splitText').checked)};
renderCustomChips=function(){const box=$('customPageChips');box.replaceChildren();state.pages.custom.forEach((p,i)=>{const b=document.createElement('button');b.className='page-chip'+(i===state.pageIndex.custom?' active':'');b.textContent=i+1;b.title=p.name;b.onclick=async()=>{if(workspaceBusy())return;saveActivePage();state.pageIndex.custom=i;await loadPage(p)};box.append(b)})};
previewSingleScale=function(){if(loadingPage)return;if(!scaleBaseline){saveActivePage();scaleBaseline=cloneData(state.pages.custom.map(p=>p.objects))}const f=clamp(Number($('singleScale').value)||100,10,500)/100;state.pages.custom.forEach((p,i)=>{p.objects=scaleBaseline[i].map(o=>({...o,left:p.widthMm*PX_PER_MM/2+(o.left-p.widthMm*PX_PER_MM/2)*f,top:p.heightMm*PX_PER_MM/2+(o.top-p.heightMm*PX_PER_MM/2)*f,scaleX:o.scaleX*f,scaleY:o.scaleY*f}))});const byId=new Map(currentPage.objects.map(o=>[o.id,o]));canvas.discardActiveObject();canvas.getObjects().forEach(o=>{const d=byId.get(o.projectId);if(d){o.set({left:d.left,top:d.top,scaleX:d.scaleX,scaleY:d.scaleY,dirty:true});o.setCoords()}});canvas.requestRenderAll();scheduleCommit()};

function copySelection(){if(cropSession||workspaceBusy()){toast('Completa l’operazione in corso');return}const selected=selectionObjects().filter(o=>!o.excludeProject);if(!selected.length){toast('Seleziona uno o più oggetti da copiare');return}canvas.discardActiveObject();const objects=selected.map(serializeObject);projectClipboard=cloneData({objects,assets:referencedAssets([{pages:{custom:[{objects}]}}])});pasteSerial=0;canvas.setActiveObject(selected.length===1?selected[0]:new fabric.ActiveSelection(selected,{canvas}));canvas.requestRenderAll();toast('Copiati '+selected.length+' oggetti · incolla anche in un’altra pagina o progetto')}
async function pasteSelection(){if(!projectClipboard){toast('Copia prima gli oggetti con Ctrl+C o dal menu');return}if(cropSession||loadingPage)return;pasteSerial++;const data=cloneData(projectClipboard),assetMap=new Map();for(const [old,a] of Object.entries(data.assets)){const id=uid('asset');assetMap.set(old,id);state.assets[id]={...a,id}}visitDescriptors(data.objects,o=>{o.id=uid('obj');if(o.assetId)o.assetId=assetMap.get(o.assetId)||o.assetId});canvas.discardActiveObject();const copies=[];for(const d of data.objects){d.left+=20*pasteSerial;d.top+=20*pasteSerial;copies.push(await instantiateObject(d))}canvas.setActiveObject(copies.length===1?copies[0]:new fabric.ActiveSelection(copies,{canvas}));canvas.requestRenderAll();saveActivePage();toast('Oggetti incollati')}
pasteSelection=withHistory(pasteSelection);

function paintFontSample(id,font){const el=$(id);if(!el||!font)return;el.textContent='Outline';el.style.fontFamily=JSON.stringify(font)+',sans-serif';el.style.color=fontMeta(font).native||!state.outline?'#000000':'transparent';el.style.webkitTextStroke=!fontMeta(font).native&&state.outline?'1px #000000':'0'}
function refreshFontPreviews(){if(!$('currentFontSample'))return;$('currentFontName').textContent=state.font;paintFontSample('currentFontSample',state.font);const suggested=state.wizard.result?.name;if(suggested){paintFontSample('wizardFontSample',suggested);clearTimeout(fontPreviewTimer);fontPreviewTimer=setTimeout(()=>loadFont(suggested),180)}loadFont(state.font)}
const v6RenderFonts=renderFontResults;renderFontResults=function(){v6RenderFonts();for(const b of document.querySelectorAll('#fontResults [data-font]'))b.onclick=withHistory(b.onclick);refreshFontPreviews()};
const v6Wizard=updateWizard;updateWizard=function(){v6Wizard();refreshFontPreviews()};
syncUiFromState=function(){v6Sync();refreshFontPreviews()};
openPreview=function(){saveActivePage();const panel=$('previewPanel'),grid=$('previewGrid'),pages=[...state.pages.custom];panel.classList.remove('hidden');grid.replaceChildren();previewObserver?.disconnect();previewObserver=new IntersectionObserver(entries=>entries.forEach(async e=>{if(!e.isIntersecting)return;previewObserver.unobserve(e.target);const p=pages.find(p=>p.id===e.target.dataset.page);if(!p)return;try{const url=await renderPageDataUrl(p,Math.min(60,420/(p.widthMm*PX_PER_MM)*96));if(!e.target.isConnected)return;const img=document.createElement('img');img.src=url;img.alt=p.name;e.target.querySelector('.preview-sheet').append(img)}catch(e){e.target?.append?.('Anteprima non disponibile')}}),{root:panel,rootMargin:'400px'});pages.forEach((p,i)=>{const tile=document.createElement('button');tile.className='preview-page';tile.dataset.page=p.id;const sheet=document.createElement('div');sheet.className='preview-sheet';sheet.style.aspectRatio=p.widthMm+'/'+p.heightMm;const label=document.createElement('span');label.textContent=(i+1)+'. '+p.name+' · '+(p.widthMm>p.heightMm?'orizzontale':'verticale');tile.append(sheet,label);tile.onclick=async()=>{closePreview();saveActivePage();state.pageIndex.custom=i;await loadPage(p)};grid.append(tile);previewObserver.observe(tile)})};
function askPdfScope(){$('pdfProjectInfo').textContent=(activeProject()?.name||'Progetto')+' · '+state.pages.custom.length+' pagine';$('pdfDialog').showModal()}

async function generateLetterPages(){
 if(workspaceBusy())return;const text=$('specialText').value;if(!text.trim()){toast('Inserisci il testo della funzione speciale');return}
 const explicit=$('specialExplicit').checked,destination=$('specialDestination').value,replace=$('specialOperation').value==='replace';
 if(destination==='current'&&replace&&!confirm('Rimpiazzare tutte le pagine del progetto aperto? Potrai annullare la modifica.'))return;
 const original={rules:cloneData(state.symbolRules),smart:state.smartEmoji,axis:$('fitAxis').value};syncStateFromUI();
 const options={rules:{prev:$('specialPrev').value,next:$('specialNext').value,smartApostrophe:$('specialApostrophe').checked},smart:$('specialEmoji').checked,axis:$('specialFit').value,text:$('specialUppercase').checked?text.toLocaleUpperCase('it-IT'):text};
 const [w,h]=$('specialOrientation').value==='landscape'?[297,210]:[210,297],button=$('runSpecial');button.disabled=true;actionDepth++;syncHistoryButtons();const pages=[];let error=null;
 try{
  state.symbolRules=options.rules;state.smartEmoji=options.smart;$('fitAxis').value=options.axis==='constant'?'contain':options.axis;await loadFont(state.font);
  const groups=explicit?options.text.split('^').map(x=>x.trim()).filter(Boolean):groupGraphemes(graphemes(options.text)).map(x=>x.join('')),prepared=[];
  for(let i=0;i<groups.length;i++){
   const token=groups[i],sc=new fabric.StaticCanvas(null,{width:w*PX_PER_MM,height:h*PX_PER_MM});
   try{const object=await tokenObject(token,sc);object.setCoords();const bounds=object.getBoundingRect(true,true);prepared.push({token,descriptor:serializeObject(object),width:Math.max(1,bounds.width),height:Math.max(1,bounds.height)})}finally{sc.dispose()}
   $('specialStatus').textContent='Preparazione '+(i+1)+' / '+groups.length
  }
  const commonScale=options.axis==='constant'?Math.min(...prepared.map(item=>Math.min(w*PX_PER_MM*.84/item.width,h*PX_PER_MM*.84/item.height))):null;
  for(let i=0;i<prepared.length;i++){
   const item=prepared[i],page=makePage('Pagina '+(i+1)+' · '+item.token,w,h),sc=new fabric.StaticCanvas(null,{width:w*PX_PER_MM,height:h*PX_PER_MM});
   try{const object=await instantiateObject(item.descriptor,sc);if(commonScale){object.set({left:sc.width/2,top:sc.height/2,scaleX:(object.scaleX||1)*commonScale,scaleY:(object.scaleY||1)*commonScale,dirty:true});object.setCoords()}else fitObjectList([object],sc.width,sc.height);page.objects=[serializeObject(object)];page.meta={special:'letters',group:item.token,explicit,fit:options.axis};pages.push(page)}finally{sc.dispose()}
  }
 }catch(e){error=e}finally{state.symbolRules=original.rules;state.smartEmoji=original.smart;$('fitAxis').value=original.axis;actionDepth--;button.disabled=false;syncHistoryButtons()}
 if(error){$('specialStatus').textContent='Generazione non riuscita: '+error.message;return}if(!pages.length)return;commitHistory();
 if(destination==='new'){const payload=currentDocument(false);payload.pages={whole:[],single:[],custom:pages};payload.state.pageIndex={whole:0,single:0,custom:0};payload.state.workspaceCustom=true;payload.assets=referencedAssets([{pages:payload.pages}]);await addProject(payload,(explicit?'Gruppi':'Lettere')+' · '+text.slice(0,35))}
 else{const first=replace?0:state.pages.custom.length;state.pages.custom=replace?pages:[...state.pages.custom,...pages];state.pageIndex.custom=first;scaleBaseline=null;await loadPage(state.pages.custom[first]);commitHistory();storeActiveDocument();scheduleAutosave()}
 $('specialStatus').textContent=pages.length+' pagine create.';toast(pages.length+' pagine create')
}
function bindWorkspace(){
 $('newProjectBtn').onclick=requestNewProject;$('delCustomPage').onclick=requestDeletePage;$('deletePageCancel').onclick=()=>$('deletePageDialog').close();$('deletePageConfirm').onclick=()=>{$('deletePageDialog').close();deleteCustomPage()};$('quickAddPage').onclick=()=>addCustomPage();$('splitText').onchange=()=>{updateTextModeUI();scheduleCommit()};$('specialDestination').onchange=()=>$('specialCurrentOptions').classList.toggle('hidden',$('specialDestination').value!=='current');$('specialFit').onchange=()=>{$('specialFitHelp').textContent=$('specialFit').value==='constant'?'La frase o il gruppo più grande determina la scala; tutte le pagine mantengono caratteri della stessa dimensione.':'Ogni gruppo viene adattato separatamente.';scheduleCommit()};$('specialUseText').onclick=()=>{$('specialText').value=$('textInput').value};$('runSpecial').onclick=()=>generateLetterPages().catch(e=>toast(e.message));
 $('projectCancel').onclick=()=>$('projectDialog').close();$('projectConfirm').onclick=async()=>{$('projectDialog').close();try{if(projectDialogAction==='new'){const name=$('projectNameInput').value.trim()||'Progetto '+projectSerial;projectSerial++;await addProject(blankProjectPayload(name),name)}else await closeProject(projectDialogId)}catch(e){toast(e.message)}};$('projectExportClose').onclick=async()=>{$('projectDialog').close();await closeProject(projectDialogId,true)};
 $('copyTool').onclick=copySelection;$('pasteTool').onclick=pasteSelection;for(const b of document.querySelectorAll('#objectMenu [data-action="copy"]'))b.onclick=()=>{hideContext();copySelection()};for(const b of document.querySelectorAll('#objectMenu [data-action="paste"]'))b.onclick=()=>{hideContext();pasteSelection()};canvas.upperCanvasEl.addEventListener('contextmenu',e=>{if(!projectClipboard||cropSession||loadingPage)return;const m=$('objectMenu');m.classList.remove('hidden');m.style.left=clamp(e.clientX,8,innerWidth-220)+'px';m.style.top=clamp(e.clientY,8,innerHeight-m.offsetHeight-8)+'px'});
 window.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.querySelector('dialog[open]')||!$('helpLayer').classList.contains('hidden'))return;const key=e.key.toLowerCase();if(key==='c'||key==='v'){e.preventDefault();e.stopImmediatePropagation();if(key==='c')copySelection();else pasteSmartClipboard()}},true);
 $('exportPdfBtn').onclick=askPdfScope;$('pdfCancel').onclick=()=>$('pdfDialog').close();$('pdfConfirm').onclick=async()=>{$('pdfMode').value=document.querySelector('input[name="pdfScope"]:checked').value;$('pdfDialog').close();await exportPdf()};$('pdfMode').querySelector('option[value="all"]')?.remove();$('pdfMode').querySelector('option[value="set"]').textContent='Tutte le pagine del progetto corrente';
 const pageCard=$('customCardTitle').closest('.card'),sidebar=$('sidebar'),mobile=$('mobileSettings').closest('.card');sidebar.insertBefore(pageCard,mobile?.nextSibling||sidebar.firstChild);pageCard.after($('specialCard'));$('singleOptions').querySelector('.small').textContent='Scala oggetti su tutte le pagine del progetto';pageCard.querySelector('.card-b').append($('singleOptions'));const nav=sidebar.querySelector('.quick-jump');nav.replaceChildren();for(const [name,id] of [['Pagina','customCardTitle'],['Speciali','specialCard'],['Testo','textInput'],['Font','fontMode'],['Emoji','emojiSearch'],['Immagini','uploadImageBtn'],['Clipart','clipartCard'],['AI','aiCard'],['Export','pdfMode']]){const b=document.createElement('button');b.textContent=name;b.title='Apri '+name;b.onclick=()=>{const card=$(id).closest('.card'),cards=[...sidebar.querySelectorAll(':scope > .card')].filter(item=>item.querySelector(':scope > .card-h'));if(preferences.accordion)cards.forEach(item=>item.classList.toggle('collapsed',item!==card));card.classList.remove('collapsed');cards.forEach(item=>item.querySelector(':scope > .card-h')?.setAttribute('aria-expanded',String(!item.classList.contains('collapsed'))));preferences.collapsed=cards.filter(item=>item.classList.contains('collapsed')).map(item=>item.dataset.section);writePreferences();card.scrollIntoView({behavior:'smooth',block:'start'})};nav.append(b)}
 $('applyWizard').onclick=withHistory($('applyWizard').onclick);updateTextModeUI();renderProjectTabs();refreshFontPreviews();
}
init=async function(){readPreferences();state.mode='custom';state.strokeColor='#000000';state.emojiInk='#000000';state.pages={whole:[],single:[],custom:[]};ensurePages();fontObserver=('IntersectionObserver' in window)?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){loadFont(e.target.dataset.font);fontObserver.unobserve(e.target)}}),{root:$('fontResults'),rootMargin:'80px'}):null;initCanvas();bindUi();bindUpgrades();bindChic();bindPending();bindWorkspace();syncUiFromState();initFontCatalog();setupPuter();loadEmojiCatalog();await loadPage(currentPageByState());let memory=null;try{memory=await readMemory()}catch(e){preferences.autosave=false;memoryMessage('Memoria non leggibile: '+e.message+'. Copia precedente conservata.')}let recovered=false;if(memory){$('memoryInfo').textContent='Ultimo salvataggio: '+new Date(memory.saved).toLocaleString('it-IT')+' · '+(memory.project.workspace?.projects.length||1)+' progetti.';const resume=await new Promise(resolve=>{$('resumeMemory').onclick=()=>resolve(true);$('newMemory').onclick=()=>resolve(false);$('memoryDialog').oncancel=e=>e.preventDefault();$('memoryDialog').showModal()});$('memoryDialog').close();if(resume){try{if(memory.project.workspace){const ws=memory.project.workspace;if(ws.version!==1||!Array.isArray(ws.projects)||!ws.projects.length)throw new Error('Workspace non valido');const records=ws.projects.map(r=>({...r,payload:normalizeCustomProject(r.payload)}));projects=records;activeProjectId=records.some(r=>r.id===ws.activeId)?ws.activeId:records[0].id;projectSerial=ws.serial||records.length+1}else{projects=[{id:uid('project'),name:memory.project.name||'Progetto recuperato',payload:normalizeCustomProject(memory.project),lastExport:null}];activeProjectId=projects[0].id}await adoptProject(activeProject().payload,true);recovered=true;memoryMessage('Progetti recuperati con cronologia.')}catch(e){projects=[];activeProjectId=null;preferences.autosave=false;memoryMessage('Recupero non riuscito: '+e.message+'. Dati salvati conservati.')}}else{memoryEpoch++;localStorage.removeItem(MEMORY_KEY);await dbOperation('readwrite',s=>s.clear()).catch(()=>{})}}if(!recovered){try{await addTextUnified()}catch(e){console.warn('Esempio iniziale non disponibile',e);saveActivePage()}historyEntries=[historySnapshot()];historyCursor=0;projects=[{id:uid('project'),name:'Progetto 1',payload:currentDocument(true),lastExport:null}];activeProjectId=projects[0].id;projectSerial=2}historyReady=true;workspaceReady=true;storeActiveDocument();syncSettings();syncHistoryButtons();renderProjectTabs();refreshFontPreviews();scheduleAutosave();};
